feat: 适配「词祭」界面主题
MaaAssistantArknights/MaaAssistantArknights pull request #10331
Opened 2024-08-22 16:10 UTC by SherkeyXD

2024-08-22 17:08 UTC, Constrat commented
I'm guessing no solution currently for Mall task since it's full OCR. And OCRing this is kinda hard, triangles, squares lol
```json
    "Mall": {
        "algorithm": "OcrDetect",
        "action": "ClickSelf",
        "ocrReplace": [["米购", "采购"]],
        "text": ["采购", "购中", "中心", "到期"],
        "roi": [740, 440, 200, 100],
        "next": ["CreditStoreOcr", "Mall", "Mall@CloseAnnos#next"],
        "postDelay": 500
    },
```

Does this work? 
![image](https://github.com/user-attachments/assets/e70b47f0-7583-412c-84df-f3952a637a25)

2024-08-22 17:09 UTC, SherkeyXD commented
> I'm guessing no solution currently for Mall task since it's full OCR. And OCRing this is kinda hard, triangles, squares lol
> ```json
>     "Mall": {
>         "algorithm": "OcrDetect",
>         "action": "ClickSelf",
>         "ocrReplace": [["米购", "采购"]],
>         "text": ["采购", "购中", "中心", "到期"],
>         "roi": [740, 440, 200, 100],
>         "next": ["CreditStoreOcr", "Mall", "Mall@CloseAnnos#next"],
>         "postDelay": 500
>     },
> ```
> 
> Does this work? 
> ![image](https://github.com/user-attachments/assets/e70b47f0-7583-412c-84df-f3952a637a25)
> 

Maybe we should shift itlol template lol

2024-08-22 17:13 UTC, Constrat commented
Yeah... We survived the Sami one, but this one introduces too much garbage. You can check if the task works by just entering the interface selection, since Credit Store just detects it (or just DebugTask lol)

2024-08-23 06:19 UTC, SherkeyXD commented
Done shifting

2024-08-23 06:27 UTC, Manicsteiner commented
这样的采购中心template显然是不行的，上半部分都可能被挡住 #10194

2024-08-23 06:28 UTC, SherkeyXD commented
草 那我一会放右边去

2024-08-23 09:45 UTC, Constrat commented
Wait before merge, so we add Global templates, as modifying the main tasks.json will break all other clients

2024-08-23 09:50 UTC, Constrat requested changes

2024-08-23 09:50 UTC, Constrat commented on resource/tasks.json
> +        "template": ["Mall.png", "MallDark.png", "MallSami.png", "MallMistCity.png", "MallSiege.png", "MallSarkaz.png"],
```suggestion
        "template": ["MallOrigin.png", "MallDark.png", "MallSami.png", "MallMistCity.png", "MallSiege.png", "MallSarkaz.png"],
```

2024-08-23 09:51 UTC, Constrat commented on resource/tasks.json
> +        "template": ["Mall.png", "MallDark.png", "MallSami.png", "MallMistCity.png", "MallSiege.png", "MallSarkaz.png"],
Unless you want to change the template name, which is probably better as that would follow the format we've been using already.

2024-08-23 09:59 UTC, Constrat requested changes

2024-08-23 09:59 UTC, Constrat commented on resource/tasks.json
> -        "algorithm": "OcrDetect",
Oh, this is the issue!

2024-08-23 10:01 UTC, Constrat commented
Let's just change the template name to keep consistency:
MallOrigin.png -> Mall.png

2024-08-23 10:04 UTC, Constrat commented on resource/tasks.json
> -        "algorithm": "OcrDetect",
Fixed with 
1f37351

2024-08-23 10:09 UTC, SherkeyXD commented
I misnamed it lol
Thanks for the fix

2024-08-23 10:18 UTC, Constrat commented
Still failing 
![image](https://github.com/user-attachments/assets/d9ceac83-456c-45c7-939d-0f089c58c6fc)

2024-08-23 15:09 UTC, Constrat commented
By the way, there's no rush in merging. The theme was just preloaded so we have a lot of time to implement both `KR` and `txwy`

2024-08-23 15:21 UTC, Manicsteiner commented
> Should come out in September.

And Rainbow Six Siege theme will comes to Yostar servers soon on September 5th

2024-08-23 15:23 UTC, Constrat commented
Oh yeah, that's true. But that might be extending it a bit too much. We can do that separately since no breaking changes are happening on the CN with that.

2024-08-30 19:08 UTC, SherkeyXD commented
Is it ready?

2024-08-30 19:10 UTC, Constrat commented
> Is it ready?

I think txwy misses the templates :P

2024-09-01 15:36 UTC, ABA2396 approved these changes

2024-09-01 15:38 UTC, merged