feat: 生息演算2刷开局清空编队干员
MaaAssistantArknights/MaaAssistantArknights pull request #10348
Opened 2024-08-23 22:32 UTC by Daydreamer114

2024-08-23 22:46 UTC, Daydreamer114 commented
[名为侯国玉](https://www.bilibili.com/video/BV1oe4y1x7cJ)

2024-08-24 06:55 UTC, SherkeyXD commented
为什么是7-12清空编队（

2024-08-24 06:56 UTC, Daydreamer114 commented
7-12需要更多饮料，初始的不够；
但是0-6即使有编队成员也能正常打

2024-08-24 06:57 UTC, SherkeyXD approved these changes

2024-08-24 07:30 UTC, status102 requested changes
语言文件要改都改

2024-08-24 09:34 UTC, Daydreamer114 commented
@status102 改完了

2024-08-24 12:59 UTC, closed without merging