perf: 全肉鸽招募适配娜仁图亚、艾拉
MaaAssistantArknights/MaaAssistantArknights pull request #10385
Opened 2024-08-27 11:34 UTC by Daydreamer114

fix #10382

2024-08-27 17:26 UTC, Lancarus commented
写都写了干脆把佩佩/衡沙和莎草都同步了算了，用那个tools

2024-08-27 17:26 UTC, Lancarus submitted a review, later dismissed

2024-08-27 23:58 UTC, Daydreamer114 commented
草，后面这俩我一次都没用过，我到时候看看

2024-08-28 03:54 UTC, Lancarus commented
> 草，后面这俩我一次都没用过，我到时候看看

萨卡兹里面写了，复制粘贴一下就好了

2024-08-28 12:15 UTC, HoshinoAyako requested changes

2024-08-28 12:15 UTC, HoshinoAyako commented on resource/roguelike/Mizuki/recruitment.json
> +                    "skill": 2,
不是应该改成1技能仅使用一次吗？

2024-08-28 12:19 UTC, HoshinoAyako requested changes

2024-08-28 12:19 UTC, HoshinoAyako commented on resource/roguelike/Mizuki/recruitment.json
> +                    "skill_usage": 2,
按issues改的

2024-08-28 13:53 UTC, Daydreamer114 commented
哥们，咱们该咋写咋写，提issue的人又不是写肉鸽的人

2024-08-28 13:56 UTC, Daydreamer114 commented
我标题也写了，是适配，而不是修复

2024-08-29 04:15 UTC, HoshinoAyako approved these changes

2024-08-29 04:32 UTC, HoshinoAyako approved these changes

2024-08-29 04:57 UTC, HoshinoAyako commented
> 我标题也写了，是适配，而不是修复
> 他这个issue的意义在于提醒我们太阳甩在身后的干员适配没做完，而不是娜仁图亚要用一技能
> 
> 你改吧，我unsubscribe了

对不起。是我误解了。
我原以为是按照issuse来适配的。
是我唐突了。佬请forcepush吧。

2024-09-01 08:50 UTC, merged