docs: 更新并优化肉鸽文档
MaaAssistantArknights/MaaAssistantArknights pull request #10591
Opened 2024-09-12 18:05 UTC by Daydreamer514

2024-09-12 18:06 UTC, Daydreamer114 commented
@Lancarus

2024-09-12 18:10 UTC, Alan-Charred approved these changes

2024-09-13 01:20 UTC, shikakihuso commented
阵容完备度检测写清楚点，是组内干员重复会点两下，组间重复不会

2024-09-13 02:04 UTC, Daydreamer114 commented on docs/zh-cn/protocol/integrated-strategy-schema.md
> +但一个强力干员（如维什戴尔）可以出现在多个干员组中，在阵容完备度检测中可能因为存在于多个干员组而一个人满足大于 1 的 threshold
实际代码工作方式未求证

2024-09-13 10:23 UTC, Daydreamer114 commented on docs/zh-cn/protocol/integrated-strategy-schema.md
> +然后将预备干员移至最末，形成新的顺序，按照新的顺序进行选择
我还在确定，基于这个逻辑，为什么临时招募的干员会优先编队
我猜是临时招募会被默认排在靠前的位置

2024-09-15 07:43 UTC, Daydreamer114 commented
@MaaAssistantArknights/global-support-team 

I have noticed that IS schema already have some difference between other languages version and Chinese version.
This is a relatively comprehensive content update. If you have time, please help with the document translation.
And also, feel free to point out if any part of the text is ambiguous.

Regards.

2024-09-17 05:52 UTC, Lancarus commented on docs/zh-cn/protocol/integrated-strategy-schema.md
> +参考例子：1.傀影肉鸽的益达，2.水月肉鸽的益达，3.萨米肉鸽的益达，4.萨卡兹肉鸽的益达
。。。后面两个肉鸽根据益达也就算了，前面两个所有作业都根据益达用法优化了？

2024-09-17 05:53 UTC, Lancarus commented on docs/zh-cn/protocol/integrated-strategy-schema.md
> +:::
这属于废话

2024-09-17 05:54 UTC, Lancarus commented on docs/zh-cn/protocol/integrated-strategy-schema.md
> +（对于一定要和完全不想要的干员，可以特殊地赋予极高和极低的分数，详见 `Sarkaz` 中的 `维什戴尔` 和 `玛露西尔` ）
既然举例子就举数值正常的例子，不要举这种玩烂梗的例子

2024-09-17 05:56 UTC, Lancarus commented on docs/zh-cn/protocol/integrated-strategy-schema.md
> +定制化策略优先与通用战斗策略，当定制化策略中的所有步骤都尝试执行完毕后，省下的干员或者倒下再部署的干员会按照通用战斗策略不断部署
错别字剩下

2024-09-17 06:00 UTC, Lancarus commented on docs/zh-cn/protocol/integrated-strategy-schema.md
> +一个强力干员（如维什戴尔）可以出现在多个干员组中，在阵容完备度检测中可能因为一个人存在于多个干员组而一个人满足了大于 1 的 threshold 检查
引入了"threshold 检查"的概念但前文未作说明

2024-09-17 06:02 UTC, Lancarus commented on docs/zh-cn/protocol/integrated-strategy-schema.md
> +一个强力干员（如维什戴尔）可以出现在多个干员组中，在阵容完备度检测中可能因为一个人存在于多个干员组而一个人满足了大于 1 的 threshold 检查
重复干员的检测应该完善bug和逻辑而不是用蹩脚的理由写在说明书里不让别人用

2024-09-17 15:26 UTC, Daydreamer114 commented on docs/zh-cn/protocol/integrated-strategy-schema.md
> +一个强力干员（如维什戴尔）可以出现在多个干员组中，在阵容完备度检测中可能因为一个人存在于多个干员组而一个人满足了大于 1 的 threshold 检查
在#10634 中继续

2024-09-23 07:34 UTC, status102 requested changes
请不要使用小号进行提交，你的大号已经是组织的成员
@Daydreamer114

2024-09-23 07:40 UTC, closed without merging