refactor(fix): 阵容完备度中单个干员重复出现于多个干员组的问题
MaaAssistantArknights/MaaAssistantArknights pull request #10634
Opened 2024-09-17 14:19 UTC by Daydreamer514

2024-09-17 14:21 UTC, Daydreamer114 commented on src/MaaCore/Task/Roguelike/RoguelikeFormationTaskPlugin.cpp
> -                count++;
relate to [6e5f333](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/6e5f333bd83a591eaaef1fadc11f4001be9cb471)
@zzyyyl 这个 count 是不是应该放在这个 if 里面，表示成功选中了才计数？

2024-09-18 16:20 UTC, Daydreamer114 commented
修复已经完成，但是重构还没有
目前注释好像也不是很全，明天继续弄

2024-09-19 00:31 UTC, Daydreamer114 commented on src/MaaCore/Task/Roguelike/RoguelikeRecruitTaskPlugin.cpp
> +
对于当前的写法，复杂度为：
{ (此策略组的干员组数)
    { (已有干员数)
        { (干员所在干员组数)
        }}}
我想到了另一个更直观的方法：
{ (干员组内干员数)
    将所有干员整合为unordered_set
}
{ (干员数)
    { (干员的字符串长度)
    }}

2024-09-19 00:38 UTC, Daydreamer114 commented on src/MaaCore/Task/Roguelike/RoguelikeRecruitTaskPlugin.cpp
> +
对于上面的方法，总运行次数甚至可能小于下面的“所有干员组的干员数总和”？

2024-09-19 00:39 UTC, Daydreamer114 commented on src/MaaCore/Task/Roguelike/RoguelikeRecruitTaskPlugin.cpp
> +
```
{ (所有干员组的干员数总和)
    将所有干员整合为unordered_set
}
```

这个操作应该是一次性的，不需要每次都算一遍……？

2024-09-19 04:33 UTC, Daydreamer114 commented
基本重构已经完成，但可以继续找复用
异常处理应该有挺大问题
注释接着写

2024-09-22 11:47 UTC, Daydreamer114 commented on src/MaaCore/Config/Roguelike/RoguelikeRecruitConfig.cpp
> +}
这个异常处理有什么建议吗（）

2024-09-23 07:33 UTC, status102 requested changes
请不要使用小号进行提交，你的大号已经是组织的成员
@Daydreamer114

2024-09-23 07:41 UTC, closed without merging