feat: 自动编队自动借助战
MaaAssistantArknights/MaaAssistantArknights pull request #10797
Opened 2024-10-13 07:52 UTC by Daydreamer114

2024-10-13 08:04 UTC, status102 commented on src/MaaCore/Task/Miscellaneous/BattleFormationTask.cpp
>          auto limit = 12 - m_size_of_operators_in_formation;
这是预期修改吗

2024-10-13 08:50 UTC, status102 requested changes

2024-10-13 08:50 UTC, status102 commented on src/MaaCore/Task/Miscellaneous/BattleFormationTask.cpp
>      }
卡网络会返true，后续逻辑也有问题

2024-10-13 09:50 UTC, Daydreamer114 commented on src/MaaCore/Task/Miscellaneous/BattleFormationTask.cpp
>          auto limit = 12 - m_size_of_operators_in_formation;
不是，我当时不知道你的 commit，resolve conflict的时候直接把你的 revert 了，还没加回来

2024-10-13 10:00 UTC, Daydreamer114 commented on src/MaaCore/Task/Miscellaneous/BattleFormationTask.cpp
>      }
为啥卡网络要返回 true？
后续逻辑有啥问题，本地已经能用了

2024-10-13 10:09 UTC, status102 commented on src/MaaCore/Task/Miscellaneous/BattleFormationTask.cpp
>      }
> 为啥卡网络要返回 true？ 后续逻辑有啥问题，本地已经能用了

Bug：卡网络会返true，然后卡在其他界面上
加个允许用助战的开关，以及助战会导致信赖和补充自定干员不可用

2024-10-13 14:50 UTC, Daydreamer114 commented on src/MaaCore/Task/Miscellaneous/BattleFormationTask.cpp
>          auto limit = 12 - m_size_of_operators_in_formation;
哦对了，你删 .cpp 的函数的时候没删 .h 的

2024-10-13 14:56 UTC, Daydreamer114 commented on src/MaaCore/Task/Miscellaneous/BattleFormationTask.cpp
>      }
TODO

> Bug：卡网络会返true，然后卡在其他界面上

卡网络只有点进助战、第一次点一个职业、点刷新会卡
如果退出 select_support_operator 之后会卡网络，就退完加个检测；但招募是成功了的

> 加个允许用助战的开关

等 charred 老师写

> 助战会导致信赖和补充自定干员不可用

把 select_support_operator 返回 true 的 return 删了，只要不是真缺干员就可以继续；但是界面不是预想中的界面了，还得回快速招募

2024-10-13 16:56 UTC, Daydreamer114 commented on src/MaaCore/Task/Miscellaneous/BattleFormationTask.cpp
>      }
不太对，确认招募助战应该没有网络活动

2024-10-13 23:03 UTC, Alan-Charred commented
还没看完，准备一边改一边确认逻辑。我目前是想把助战选取功能单独拎出来。
请容我确认一下：目前助战功能只需要考虑普通战斗、保全、肉鸽，这三个地方。基本上是一致的，唯一的区别是肉鸽招募锁定了职业。是吧？

2024-10-14 03:25 UTC, Daydreamer114 commented
![MuMu12-20241014-112433](https://github.com/user-attachments/assets/6ece2339-6691-4f1e-9a55-e78d114a3a72)

2024-10-14 03:29 UTC, Daydreamer114 commented
还有判断练度的时候 roi 不一样
肉鸽的精英化、等级的位置比自动作战低
可以传一下模式然后拼接任务名来区分 roi

肉鸽职业是锁着的，选职业这步肉鸽就可以跳了，我是用任务链给作战写的

保全的其他流程是跟作战一样的，只是有20人上限

2024-10-14 06:15 UTC, Daydreamer114 commented
Charred 老师看看 #9473 能不能改改 base branch，搞进来

2024-10-15 06:39 UTC, Alan-Charred commented
> 还有判断练度的时候 roi 不一样 肉鸽的精英化、等级的位置比自动作战低 可以传一下模式然后拼接任务名来区分 roi
> 
> 肉鸽职业是锁着的，选职业这步肉鸽就可以跳了，我是用任务链给作战写的
> 
> 保全的其他流程是跟作战一样的，只是有20人上限 右上角的弹窗，在基建访问好友的流程里是 ocr 的，可以参考一下

那就先留着这个课题，以后再改成通用的。Orz

2024-10-16 02:38 UTC, closed without merging