fix: 修复日服艾雅法拉识别错误
MaaAssistantArknights/MaaAssistantArknights pull request #10862
Opened 2024-10-19 07:02 UTC by Saratoga-Official

エ会识别成方括号

2024-10-19 09:05 UTC, Daydreamer114 requested changes
想想纯烬小羊，不能用全匹配

2024-10-19 15:01 UTC, Saratoga-Official commented
> 想想纯烬小羊，不能用 .*

那怎么改

2024-10-19 15:08 UTC, closed without merging

2024-10-20 05:17 UTC, Daydreamer114 commented
你可以把 log 贴上来，然后 at global-support-team

2024-10-20 05:23 UTC, Saratoga-Official commented
log不用贴了吧，就第一个エ会识别成方括号
cc@Manicsteiner

2024-10-20 05:37 UTC, Manicsteiner commented
印象里确实出过类似的问题，但是基本只有小概率出现，一般重新找一次就能识别，所以就没改
想改的话用个转义符号就是了