feat: 肉鸽月度小队奖励/访谈记录策略 #7058
MaaAssistantArknights/MaaAssistantArknights pull request #11423
Opened 2024-12-24 11:53 UTC by BxFS

2024-12-24 13:43 UTC, BxFS commented
为每层结束创建一个策略(#7058, #7972)，并在高级设置追加自动切换未获得奖励的月度小队/深入探索选项(#7219)？

2024-12-25 22:16 UTC, Daydreamer114 commented on resource/tasks.json
>      },
这东西每个肉鸽的底色都不一样吧，如果 skip 的形状一样的话，可以考虑给四个肉鸽做成同一个 skip 任务，指定一个匹配的灰度范围；

confirm 完了再检查一下 skip 可能有用？可以考虑把 skip 留到第二个？

看到你把月度策略写到 gui 里了，记得适配一下开始探索的识别，以及 disable 一下选难度的功能

加油）

2024-12-26 06:07 UTC, BxFS commented on resource/tasks.json
>      },
后端写差不多了，现在有两个问题：
傀影肉鸽自动跳出来的对话会把@NextLevel用来识别的界面自动挤下去，接下来等一串超时之后对话已经结束了，右上角的skip会变成×导致识别成结束肉鸽；这部分目前加了个@DialogTimeout在@Stages里面接一下，但显然应该有更好的办法处理
另外就是task没找到template的时候是哪个状态？NodeStatus::RetryFailed？用ProcessTask的返回状态在plugin里决定下一步行为（而不是用task的onErrorNext）是常规操作吗？

2024-12-26 08:45 UTC, Daydreamer114 commented on resource/tasks.json
>      },
> 另外就是task没找到template的时候是哪个状态？NodeStatus::RetryFailed？

如果能进一个task，说明肯定是找到了；执行完这个 task 之后会去识别所有 next，重复retry times（默认20次）之后应该是retry failed

> 用ProcessTask的返回状态在plugin里决定下一步行为（而不是用task的onErrorNext）是常规操作吗？

如果是单个 task 这么写没问题，但如果是任务链的话，返回状态是最后一个任务的状态，这时返回 failed 只能知道有一步错了，意义不大

2024-12-26 08:50 UTC, Daydreamer114 commented on resource/tasks.json
>      },
> 这部分目前加了个DialogTimeout在Stages里面接一下，但显然应该有更好的办法处理

stages#next -> dialog timeout -> next level ？
反正已经是史山了，我个人觉得没问题）

2024-12-26 11:13 UTC, BxFS commented
月度差不多了，做深入探索倒在通关一次本体的要求上
先挂一晚上.jpg

2024-12-26 11:39 UTC, BxFS commented on resource/tasks.json
>      },
> 如果能进一个task，说明肯定是找到了；执行完这个 task 之后会去识别所有 next，重复retry times（默认20次）之后应该是retry failed
测了一下，进task没找到会不执行action或next直接并且回false
这个retry次数能改吗？我看task.json里没这个项目

> 如果是单个 task 这么写没问题，但如果是任务链的话，返回状态是最后一个任务的状态，这时返回 failed 只能知道有一步错了，意义不大
这倒没啥问题，只要不是直接送往error handling就行

> stages#next -> dialog timeout -> next level ？
stages#next -> next level -> dialog skip -> dialog timeout, 主要是担心往stages里塞太多东西影响性能，要不再上一个plugin

2024-12-26 17:14 UTC, Daydreamer114 commented on resource/tasks.json
>      },
> 测了一下，进task没找到会不执行action或next直接并且回false 这个retry次数能改吗？我看task.json里没这个项目

好像还真没法在 tasks 改，可以去群里问问

> stages#next -> next level -> dialog skip -> dialog timeout, 主要是担心往stages里塞太多东西影响性能，要不再上一个plugin

哦哦我之前理解错了，刚重新看了遍流程
next level 之后直接出的对话，这么着没问题；进 stages#next 基本上都得有 drops flag 的识别，是这个位置
![image](https://github.com/user-attachments/assets/bed87c8b-6a5d-4e5e-a8bb-ae5d9d632580)
对话是不出现这个图标的，那我盲猜写进 stages#next 也没用
跳完对话之后，可以考虑接进 drops flag
```json
    "Roguelike@DropsFlag_default": {
        "template": "Roguelike@DropsFlag.png",
        "baseTask": "Roguelike@DropsFlag",
        "next": [
            "Roguelike@GetDrops#next",
            "Roguelike@GetDropCompleted",
            "Roguelike@GetDropLeave",
            "Roguelike@StageTraderLeave",
            "Roguelike@Stages#next",
            "Roguelike@StageEncounterOptions#next",
            "Roguelike@StageEncounterSpecialClose",
            "Roguelike@EnterAfterRecruit",
            "Roguelike@CloseEvent",
            "Roguelike@DialogSkip",
            "Roguelike@RecruitOther"
        ]
    },
```
这一个 #next 就接进来一堆 next，所以性能你其实不用太担心）

2024-12-27 03:14 UTC, BxFS commented
入口和自动切换都写好了，深入调查那边缺测试但应该能用
现在发现的新问题是每个深入调查都有较大的机制(这个大概只影响策略)/流程(比如缺少开场招募和不待人进战斗额外触发一个确认窗口)/目标(不一定默认往后推就能达成)改动，多少得每个都适配一下，现在一共37个深入调查超这个pr的scope了

2024-12-27 06:45 UTC, Daydreamer114 commented
> 多少得每个都适配一下，目前三个肉鸽一共37个深入调查超这个pr的scope了

别别别，每个深入调查都特殊化也太抽象了

我记得特殊掉东西的时候，下面有一个对勾吧，识别那个行吗，具体拿了什么就不管了

2024-12-27 06:57 UTC, BxFS commented
> > 多少得每个都适配一下，目前三个肉鸽一共37个深入调查超这个pr的scope了
> 
> 别别别，每个深入调查都特殊化也太抽象了
> 
> 我记得特殊掉东西的时候，下面有一个对勾吧，识别那个行吗，具体拿了什么就不管了

拿东西这部分已经hack上去了，能拿
问题出在现存流程和策略直接套上去不一定能完成部分深入调查，有的会卡住，有的可能需要重复很多次才能碰巧满足达成条件

2024-12-27 07:33 UTC, BxFS commented
差不多了，现在缺一个测试

2025-01-01 16:05 UTC, Daydreamer114 commented
![MuMu12-20250102-000331](https://github.com/user-attachments/assets/245081c4-aa94-4546-b7fa-d7ea291f85dd)
刷月度小队（讲述者列表）在最最开始就卡住了

另外要检查一下当前用户给到了哪个页面，现在设为刷深度也能直接进常规；页面不对的话可以直接帮用户点了

2025-01-02 02:30 UTC, BxFS commented
> ![MuMu12-20250102-000331](https://private-user-images.githubusercontent.com/74444214/399574137-245081c4-aa94-4546-b7fa-d7ea291f85dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU3NDc4MzgsIm5iZiI6MTczNTc0NzUzOCwicGF0aCI6Ii83NDQ0NDIxNC8zOTk1NzQxMzctMjQ1MDgxYzQtYWE5NC00NTQ2LWI3ZmEtZDdlYTI5MWY4NWRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTAxVDE2MDUzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4Y2M4OTY2OGUzYjFlMWI4YmU0MGY1ZTdhMWVmNzM1YWRkZGE5OWQ0OGE0MWI1OTIxNmI3ODE4NzFiODMwYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OkiThe5xEGN39pEgnto5bhxmiR6RlW7zUtbNXQJ3aR4) 刷月度小队（讲述者列表）在最最开始就卡住了
> 


能复现，看log是卡在startexplore#next上了，initialdrop只有0.26
……然后去看template，所有initialdrop都是傀影的initialdrop复制粘贴
已经把其他三个肉鸽的initialdrop都截了，能正常进月度

> 另外要检查一下当前用户给到了哪个页面，现在设为刷深度也能直接进常规；页面不对的话可以直接帮用户点了


目前在开始的时候有一个task看深度/月度标签是否未选中，应该会先切过去，我没能复现这个
但如果你深度都刷完了是会主动切回常规继续行动的（我当时还没搞明白怎么结束整个任务，丢进todo了），这个行为刚改成结束肉鸽

2025-01-02 05:34 UTC, BxFS commented
拿这个月的42测了一遍，正常跑了两圈结束，看起来没什么问题

2025-01-08 09:11 UTC, BxFS commented
俺寻思可以用了.jpg
单人测起来挺慢的，三层通过率也很堪忧，如果勾选了月度小队通信容易在三层撞一下午的墙，但只是捡蚊子腿应该很快

2025-01-10 12:20 UTC, status102 reviewed
这只有简中服能用吧，模板考虑一下国际服适配

2025-01-10 12:36 UTC, BxFS commented
> 这只有简中服能用吧，模板考虑一下国际服适配

适配是肯定要做的，群里之前有人提过这事；暂时想的是先让除了我以外的人看看基本功能有没有正确实现，还有考虑一下一部分template能不能换用OCR这样，都弄完了再适配

2025-01-12 03:59 UTC, status102 commented on src/MaaCore/Task/Roguelike/RoguelikeDifficultySelectionTaskPlugin.cpp
> +    }
这个往上放到load_params会好点

2025-01-12 07:08 UTC, BxFS commented on src/MaaCore/Task/Roguelike/RoguelikeDifficultySelectionTaskPlugin.cpp
> +    }
[2fa18e7](https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/11423/commits/2fa18e7a6b7bf82c4fcd33625171cd2a71f800f3)

2025-01-12 09:12 UTC, status102 commented on src/MaaCore/Task/Roguelike/RoguelikeIterateMonthlySquadPlugin.cpp
> +                     .run()) {
ProcessTask放if里面折3行不太好看，改改

2025-01-12 09:12 UTC, status102 commented on src/MaaCore/Task/Roguelike/RoguelikeDeepExplorationSpecialParameters.cpp
> +    return true;
删删，默认return true的

2025-01-13 03:12 UTC, BxFS commented
感觉适合从template换成ocr的只有小队通讯的入口那里，其他template或多或少都依赖某个图标一起变化

2025-01-13 03:12 UTC, BxFS commented on src/MaaCore/Task/Roguelike/RoguelikeIterateMonthlySquadPlugin.cpp
> +                     .run()) {
[f16235f](https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/11423/commits/f16235f3f3abd892d2de9032581ab70aac1d4105)

2025-01-13 03:12 UTC, BxFS commented on src/MaaCore/Task/Roguelike/RoguelikeDeepExplorationSpecialParameters.cpp
> +    return true;
[f16235f](https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/11423/commits/f16235f3f3abd892d2de9032581ab70aac1d4105)

2025-01-13 11:18 UTC, BxFS commented
![1](https://github.com/user-attachments/assets/87a0bb19-ba62-4420-a159-8e9ac751f2db)
Phantom@Roguelike@Comms.png
Phantom@Roguelike@MonthlySquadRewardMiss.png
Phantom@Roguelike@DeepExploration.png
also Phantom@Roguelike@DeepExplorationNotUnlocked.png if you can find a specimen yet to unlock DE

![2](https://github.com/user-attachments/assets/27d0fe38-89ea-4b2e-855d-e21fbaf7137b)
Phantom@Roguelike@DeepExplorationRewardMiss.png
Phantom@Roguelike@MonthlySquad.png

![3](https://github.com/user-attachments/assets/d85738a2-cf86-4331-b314-30c2679e2f85)
Mizuki@Roguelike@Comms.png
Mizuki@Roguelike@MonthlySquadRewardMiss.png
Mizuki@Roguelike@DeepExploration.png
also Mizuki@Roguelike@DeepExplorationNotUnlocked.png if you can find a specimen yet to unlock DE

![4](https://github.com/user-attachments/assets/74fb7a90-427d-4da3-89e1-43ada54f6b45)
Mizuki@Roguelike@DeepExplorationRewardMiss.png
Mizuki@Roguelike@MonthlySquad.png

![5](https://github.com/user-attachments/assets/89d4211a-849d-4d7d-8f6c-5f6b4e9aa866)
Mizuki@Roguelike@CommsMiss.png

![6](https://github.com/user-attachments/assets/6a8d69b6-4075-4ddd-9e1f-4a50c036857f)
Sami@Roguelike@Comms.png
Sami@Roguelike@MonthlySquadRewardMiss.png
Sami@Roguelike@DeepExploration.png
also Sami@Roguelike@DeepExplorationNotUnlocked.png if you can find a specimen yet to unlock DE

![7](https://github.com/user-attachments/assets/29a75f98-9cff-4a00-a946-67abf7b3c867)
Sami@Roguelike@DeepExplorationRewardMiss.png
Sami@Roguelike@MonthlySquad.png

![8](https://github.com/user-attachments/assets/d3da088e-5e3c-4cbc-b035-3b6982f21380)
Sami@Roguelike@CommsMiss.png

![9](https://github.com/user-attachments/assets/9830b466-042c-45e2-a3e1-a3870866a8fc)
Sarkaz@Roguelike@MonthlySquad.png

![10](https://github.com/user-attachments/assets/f5aa9c22-c0a1-48d0-9777-a5ad3858503b)
Sarkaz@Roguelike@Comms.png
Sarkaz@Roguelike@MonthlySquadRewardMiss.png

![11](https://github.com/user-attachments/assets/7056dd99-23b8-44c4-822e-d8e7a8a65eec)
Sarkaz@Roguelike@CommsMiss.png

![12](https://github.com/user-attachments/assets/ee94ba15-a377-4b12-9b35-209dc7c9cf10)
Roguelike@NoOp.png  (this one is unused as of yet; to get this you'll need to enter any roguelike without any operator, for example rejecting all)

施工中.jpg
先看看对不对劲

2025-01-13 11:21 UTC, status102 commented
> 施工中.jpg
> 先看看对不对劲
> github就不能选择不at人吗.jpg

可以加``做成代码块

2025-01-15 05:10 UTC, BxFS commented
@Constrat would it be a good idea to batphone global team now

2025-01-15 09:04 UTC, Constrat commented
@BxFS Thank you very much for providing the templates.

Aren't some of these duplicates that could be reused?
Like:
`Roguelike@CommsMiss.png` for Mizuki, Sami and Sarkaz
`Roguelike@DeepExplorationEnd.png` for all
`Roguelike@InitialDrop.png`
`Roguelike@SquadRewardMiss.png`
`Roguelike@Comms.png` for Sarkaz and Sami

These are just some of them (I'm sorry I'm in a bit of a hurry right now.)

Please check all the templates and try to remove all duplicates (unless strictly necessary). We have the `"template":` field for this exact reason.

After that we I will modify the ignore list https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/dev/tools/OverseasClients/ignore_list_of_templates.txt 

So that we can start on adapting it for other clients as well.

2025-01-15 09:10 UTC, BxFS commented
> Aren't some of these duplicates that could be reused? Like: `Roguelike@CommsMiss.png` for Mizuki, Sami and Sarkaz `Roguelike@DeepExplorationEnd.png` for all `Roguelike@InitialDrop.png` `Roguelike@SquadRewardMiss.png` `Roguelike@Comms.png` for Sarkaz and Sami
> 
> These are just some of them (I'm sorry I'm in a bit of a hurry right now.)


I'll look into that. 
As for InitialDrop.png, I pr'd these once I figured it looks like a bug, and that pr was merged (by you), but I forgot to remove it from my branch and did a rebase so here we are

2025-01-16 06:59 UTC, BxFS commented
``Roguelike@NoneSelected`` and both CommsMiss.png may need attention from global team, otherwise just double check if it actually works.

2025-01-16 09:43 UTC, status102 requested changes

2025-01-16 09:43 UTC, status102 commented on src/MaaCore/Task/Roguelike/RoguelikeIterateDeepExplorationPlugin.cpp
> +        ProcessTask(*this, { m_config->get_theme() + "@Roguelike@DeepExplorationComplain" }).run();
直接发callback

2025-01-16 09:45 UTC, status102 commented on resource/tasks.json
> +        "onErrorNext": ["Phantom@Roguelike@DialogTimeout", "Phantom@Roguelike@Stages#next"]
无效

2025-01-16 09:47 UTC, status102 commented on resource/tasks.json
> +    },
这俩也是

2025-01-16 09:47 UTC, status102 commented on resource/tasks.json
> +    },
还有这

2025-01-16 09:50 UTC, status102 commented on resource/tasks.json
> +        "preDelay": 500,
这个是为啥

2025-01-16 09:59 UTC, BxFS commented on resource/tasks.json
> +        "onErrorNext": ["Phantom@Roguelike@DialogTimeout", "Phantom@Roguelike@Stages#next"]
傀影这里会自动跳过，用月度小队进跳过的速度似乎会变快，StrategyChange几乎每次都只能扫到后面的对话，不这么改就会在对话界面卡住20次回begin

2025-01-16 10:00 UTC, BxFS commented on resource/tasks.json
> +    },
这也挂了asstProxy

2025-01-16 10:09 UTC, BxFS commented on resource/tasks.json
> +        "preDelay": 500,
钩在StartExplore上的插件返回的瞬间就会点之前扫到的StartExplore，偶尔会在没完全返回的时候点出去，然后卡住

2025-01-16 10:15 UTC, status102 commented on resource/tasks.json
> +        "onErrorNext": ["Phantom@Roguelike@DialogTimeout", "Phantom@Roguelike@Stages#next"]
噢，有个地方搞错了抱歉

2025-01-16 10:20 UTC, status102 commented on resource/tasks.json
> +    },
参照Medicinexxxxxxxx插件，ProcessTask拿来当callback太浪费了

2025-01-16 10:20 UTC, status102 commented on resource/tasks.json
> +        "preDelay": 500,
哪个插件，看看

2025-01-16 10:46 UTC, BxFS commented on resource/tasks.json
> +        "preDelay": 500,
就这两个新插件，选上自动切换的时候退出循环到startexplore之间就靠这个delay撑着
我的记忆里是需要两次点return.png的通讯和之前另一个pr里的检查肉鸽等级会出问题，这两个都需要挂在startexplore上而且都需要换到其他界面完成操作再换回来
这么一想是不是应该加postdelay在return task上

2025-01-16 11:31 UTC, BxFS commented on src/MaaCore/Task/Roguelike/RoguelikeIterateDeepExplorationPlugin.cpp
> +        ProcessTask(*this, { m_config->get_theme() + "@Roguelike@DeepExplorationComplain" }).run();
[920030a](https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/11423/commits/920030ae74b0266186f392b493d89a6be047c340)

2025-01-16 11:31 UTC, BxFS commented on resource/tasks.json
> +    },
[920030a](https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/11423/commits/920030ae74b0266186f392b493d89a6be047c340)

2025-01-16 11:31 UTC, BxFS commented on resource/tasks.json
> +    },
[920030a](https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/11423/commits/920030ae74b0266186f392b493d89a6be047c340)

2025-01-16 14:49 UTC, Constrat commented
Oh, the new templates look very clean. If Official did not give you any troubles removing texts I don't even think a big adaptation is necessary.

Btw in my earlier messages I didn't explicitly mean to remove texts. (If texts are necessary to get a good score, feel free to use) I just mean that some templates (with text included) were identical between IS'es.

Anyway this is a huge help on your adaptation side. Thank you very much.

2025-01-16 15:11 UTC, Constrat commented
Oh right. Backgrounds do change so splitting between Mizuki, Sami and Sarkaz would be useless anyway. In our case we just need to match the "white" part so technically you can just blackout the entire background (what you don't want) and mask it like this:

`"maskRange": [1, 255]`

![image](https://github.com/user-attachments/assets/39d8ea03-52f3-45ab-a278-9cdf1a35d108)

This is very rudimental.
@ABA2396 is more of an expert in this field.

2025-01-17 12:23 UTC, status102 commented on src/MaaCore/Task/Roguelike/RoguelikeIterateDeepExplorationPlugin.h
> +    bool completed;
```suggestion
    bool m_checkComms;
    bool m_completed;
```

2025-01-17 12:24 UTC, status102 commented on src/MaaCore/Task/Roguelike/RoguelikeIterateMonthlySquadPlugin.cpp
> +                     .run()) {
commit没了

2025-01-17 14:10 UTC, BxFS commented on src/MaaCore/Task/Roguelike/RoguelikeIterateDeepExplorationPlugin.h
> +    bool completed;
[5b6ece8](https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/11423/commits/5b6ece8ff3cbf00dfca54d2d5bbee93298680386)

2025-01-17 14:19 UTC, BxFS commented
> @BxFS Regarding the mask range. I think that ``Roguelike@DeepExplorationNotUnlocked.png`` might also give issues since it's without maskRange. From what I can see it's taken from the Mizuki IS right? 

Yep, done in [5b6ece8](https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/11423/commits/5b6ece8ff3cbf00dfca54d2d5bbee93298680386), probably going to test it tomorrow when I get my hand on an account with most of DE not unlocked yet. Or we can always discard this part and provide a more generic complainant if DE.png is not found where it should be.

> Also next time, create a branch different from `dev`. It's a pain in the ass moving between this `dev` and our `dev` since git does not consider them different. Just the remote changes.

Sadly I wasn't aware of this back when I went through the documents:
![image](https://github.com/user-attachments/assets/31f04b8e-8bfe-45dd-8c4e-184cf7e5bdf4)
It made no reference about disrupting upstream. But I'll keep it in mind for future..
Any chance to resolve this here from my end?

2025-01-17 14:26 UTC, Constrat commented
> Any chance to resolve this here from my end?
We would "lose" the comments in this PR since we would close it. But you can just create a new branch starting from your HEAD dev. And opening a new PR from here with that new branch.

Actually it wouldn't be that stupid since we are already quite deep in this PR. And github optimization doesn't help at all with big PRs.

If all conversations are resolved you can just migrate to a new PR. I noticed a lot of 
![{A683F6BF-44AB-42CA-9E1F-CA31D2715BF8}](https://github.com/user-attachments/assets/a0be72cc-06d3-473d-90cc-5a4ae0a92f3b)
but you add the commit as comment. You can Resolve Conversation once you  made the requested changes.

If some conversations are not resolved just add them them to the main comment of the new PR

2025-01-17 14:52 UTC, BxFS commented
Branch switched and PR moved to #11566 per recommendation from @Constrat. Closing this one.

2025-01-17 14:52 UTC, closed without merging

2025-01-17 14:54 UTC, BxFS commented
> If all conversations are resolved you can just migrate to a new PR. I noticed a lot of ![{A683F6BF-44AB-42CA-9E1F-CA31D2715BF8}](https://private-user-images.githubusercontent.com/56174894/404333941-a0be72cc-06d3-473d-90cc-5a4ae0a92f3b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzcxMjU3NTQsIm5iZiI6MTczNzEyNTQ1NCwicGF0aCI6Ii81NjE3NDg5NC80MDQzMzM5NDEtYTBiZTcyY2MtMDZkMy00NzNkLTkwY2MtNWE0YWUwYTkyZjNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTE3VDE0NTA1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxNTRiODIxYzZmMjNiMzBiMWYzYmRjZWY5YWEwNWIxMTBiMjFmMTMwOTEwYTAwNGM5MzA0ZTZmMmZiODVhYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.W1Wm9lcN6mhYxoDUeFdwZ_emZpLp_oQLSGeq4UKOA_k) but you add the commit as comment. You can Resolve Conversation once you made the requested changes.

I kinda felt that I should leave the reviewer to decided if the conversation is actually resolved by that commit, but that's probably just me.

2025-01-18 08:43 UTC, status102 commented on resource/tasks.json
> +        "preDelay": 500,
> 这么一想是不是应该加postdelay在return task上

大致是这样，现在这样就算没用到月度小队也引入了延迟

2025-01-19 02:26 UTC, BxFS commented on resource/tasks.json
> +        "preDelay": 500,
[02e9704](https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/11566/commits/02e97048e4bfcc902f3b6c8f799749143690510a)

2025-01-19 02:29 UTC, BxFS commented on src/MaaCore/Task/Roguelike/RoguelikeIterateMonthlySquadPlugin.cpp
> +                     .run()) {
我又去试了一下，放一行会被clang format打回来