fix: 给 `run()` 加个接收异常的机制
MaaAssistantArknights/MaaAssistantArknights pull request #1215
Opened 2022-07-18 01:38 UTC by zzyyyl

https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/1158 （并没有修复）

2022-07-18 01:42 UTC, MistEO commented
不太好，这个 try 太大了，感觉性能损失有点严重

2022-07-18 01:45 UTC, zzyyyl commented
> 不太好，这个 try 太大了，感觉性能损失有点严重

确实，那对于异常后直接程序终止有没有好一点的解决办法（

2022-07-18 02:02 UTC, MistEO commented
> > 不太好，这个 try 太大了，感觉性能损失有点严重
> 
> 确实，那对于异常后直接程序终止有没有好一点的解决办法（

多做点越界访问检查之类的，从根本上解决（）

2022-07-18 02:15 UTC, zzyyyl commented
> > > 不太好，这个 try 太大了，感觉性能损失有点严重
> > 
> > 确实，那对于异常后直接程序终止有没有好一点的解决办法（
> 
> 多做点越界访问检查之类的，从根本上解决（）

#1158 里提到的不带检查的 `.at()` 是你写的吧 （
虽然暂时还不知道 #1158 的 crash 是不是这个问题导致的（

2022-07-18 02:47 UTC, zzyyyl commented
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/40c07ee4a7806a99d6d4c589693f19c340cbcd75/src/MeoAssistant/RoguelikeBattleTaskPlugin.cpp#L635-L639
我有个疑问，L636 为什么不是 `max_score = cur_result.second + extra_dist_score`，是不是写错了（

2022-07-18 03:17 UTC, MistEO commented
> https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/40c07ee4a7806a99d6d4c589693f19c340cbcd75/src/MeoAssistant/RoguelikeBattleTaskPlugin.cpp#L635-L639
> 我有个疑问，L636 为什么不是 `max_score = cur_result.second + extra_dist_score`，是不是写错了（

哦草，好像确实（

2022-07-18 07:27 UTC, horror-proton commented
好耶, 也许可以顺便把 `dx` 和 `dy` 多余的 `=0` 去掉

2022-07-18 07:36 UTC, zzyyyl commented
欸，为什么要把医疗反着设啊（

2022-07-18 09:33 UTC, MistEO requested changes

2022-07-18 09:33 UTC, MistEO commented on src/MeoAssistant/RoguelikeBattleTaskPlugin.cpp
> +    DirectionAttackRangeMap.emplace_back(std::move(RightDirection), std::move(right_attack_range));
这 static const 咋还 move

2022-07-18 09:33 UTC, MistEO commented on src/MeoAssistant/RoguelikeBattleTaskPlugin.cpp
> +    static constexpr auto sgn = [](const int &x) -> int {
这花里胡哨的前缀其实整不整都一样，没有捕获的 lambda 会退化成普通函数符号的

不过倒也没影响

2022-07-18 09:33 UTC, MistEO commented on src/MeoAssistant/RoguelikeBattleTaskPlugin.cpp
> +    if (loc.x == home_loc.x) {
为啥是 `loc.x == home_loc.x`

2022-07-18 09:54 UTC, zzyyyl commented on src/MeoAssistant/RoguelikeBattleTaskPlugin.cpp
> +    if (loc.x == home_loc.x) {
以医疗为例子，原来的逻辑是
``` cpp
if (std::abs(dx) < std::abs(dy)) base_direction = { 0, -dy };
else base_direction = { -dx, 0 };
```
|  |-1|0|1|←dx|
|:---:|:---:|:---:|:---:|:---:|
|-1|(1,0)|(0,1)|(-1,0)| |
|0|(1,0)|(0,0)|(-1,0)| |
|1|(1,0)|(0,-1)|(-1,0)| |
|↑dy| | | | ↖base_direction(x,y)|

与下面的代码意义相同
``` cpp
if (dx == 0) base_direction = { 0, -dy };
else base_direction = { -dx, 0 };
```

~~（你再看看，我觉得我应该没理解错~~

2022-07-18 09:55 UTC, zzyyyl commented on src/MeoAssistant/RoguelikeBattleTaskPlugin.cpp
> +    static constexpr auto sgn = [](const int &x) -> int {
~~（看着 nb 就行~~

2022-07-18 10:03 UTC, horror-proton commented on src/MeoAssistant/RoguelikeBattleTaskPlugin.cpp
> +    if (loc.x == home_loc.x) {
非医疗的 base_direction 大概是这样, 医疗反过来, 其中 H 是蓝门, 如果有 sign 函数的话会更容易表达 (
```
    ← ← ↑ → →
    ← ← ↑ → →
    ← ← H → →
    ← ← ↓ → →
    ← ← ↓ → →
```

2022-07-18 10:09 UTC, zzyyyl commented on src/MeoAssistant/RoguelikeBattleTaskPlugin.cpp
> +    DirectionAttackRangeMap.emplace_back(std::move(RightDirection), std::move(right_attack_range));
稍微改了下，您再看看

2022-07-18 10:13 UTC, zzyyyl commented on src/MeoAssistant/RoguelikeBattleTaskPlugin.cpp
> +    DirectionAttackRangeMap.emplace_back(std::move(RightDirection), std::move(right_attack_range));
> 其实 UpDirection 这种应该作为 `Point` 的 static constexpr 成员函数, 这样就可以直接用 `Point:: UpDirection()` 这样了 (不建议作为成员变量, 但我说不出为什么, 反正 `chrono` 里的 `zero()` `one()` 啥的也是成员函数

因为成员变量浪费空间吧（大概

2022-07-18 10:23 UTC, zzyyyl commented
按照 https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/1215#discussion_r923176269 改了一下，再来看看

2022-07-19 02:11 UTC, zzyyyl commented
@MistEO

2022-07-19 03:04 UTC, MistEO requested changes
其他应该没啥问题 XD

2022-07-19 03:04 UTC, MistEO commented on src/MeoAssistant/AsstTypes.h
> +        static constexpr Point RightDirection() { return Point(1, 0); }
`up()`, `right()` 这种就好了，大驼峰函数名不符合 maa 的代码规范（~~maa 有代码规范么~~

2022-07-19 03:05 UTC, zzyyyl commented on src/MeoAssistant/AsstTypes.h
> +        static constexpr Point RightDirection() { return Point(1, 0); }
草（

2022-07-19 03:18 UTC, MistEO approved these changes

2022-07-19 03:41 UTC, horror-proton approved these changes
话说这个 `Point` 应该没有被用在其他方向可能混乱的地方吧

2022-07-19 03:49 UTC, merged