Dev feat. 新增繁中服自動公招
MaaAssistantArknights/MaaAssistantArknights pull request #1276
Opened 2022-07-21 16:55 UTC by rockerhank

新增繁中服自動公招 需要的task內的 tags的OCR辨識  以及OCR所需的圖片

2022-07-21 17:08 UTC, MistEO requested changes

2022-07-21 17:08 UTC, MistEO commented on resource/global/txwy/resource/tasks.json
> +	"RecruitBegin": {
读取资源是增量更新的，和简中这边完全相同的 task 不需要额外复制一份。

暂时来说没影响。不过以后如果简中的 task 更新了什么，这边也要跟着改，比较麻烦

2022-07-21 17:08 UTC, MistEO commented on resource/global/txwy/resource/tasks.json
> +	"RecruitBegin": {
下面一些没有文字的图片也是同样的

2022-07-22 09:15 UTC, rockerhank commented
OK

MistEO ***@***.***> 於 2022年7月22日 週五 凌晨1:09寫道：

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In resource/global/txwy/resource/tasks.json
> <https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/1276#discussion_r926917584>
> :
>
> > @@ -58,5 +58,306 @@
>
>          "next": [
>
>              "ClickCorner"
>
>          ]
>
> +    },	
>
> +	"RecruitBegin": {
>
>
> 读取资源是增量更新的，和简中这边完全相同的 task 不需要额外复制一份。
>
> 暂时来说没影响。不过以后如果简中的 task 更新了什么，这边也要跟着改，比较麻烦
> ------------------------------
>
> In resource/global/txwy/resource/tasks.json
> <https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/1276#discussion_r926918546>
> :
>
> > @@ -58,5 +58,306 @@
>
>          "next": [
>
>              "ClickCorner"
>
>          ]
>
> +    },	
>
> +	"RecruitBegin": {
>
>
> 下面一些没有文字的图片也是同样的
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/1276#pullrequestreview-1046875542>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMRTW7EH6ELZ2XDZBXUZNBLVVF72XANCNFSM54IKS52Q>
> .
> You are receiving this because you authored the thread.Message ID:
> <MaaAssistantArknights/MaaAssistantArknights/pull/1276/review/1046875542@
> github.com>
>

2022-07-23 03:42 UTC, merged