重构公招相关的部分代码
MaaAssistantArknights/MaaAssistantArknights pull request #1327
Opened 2022-07-25 15:11 UTC by horror-proton

#### ~~最近 issue 里面关于公招的 bug 比较少, 来制造一波~~
- 移除 `RecruitCalcTask`, 将其主要功能放入 `asst::AutoRecruitTask::recruit_calc_task` 中 (想不出函数名)
- 将 `RecruitTask` 中的 `RecruitBegin` 任务也移动到 `AutoRecruitTask` 中
- 优化公招 tags 组合对应干员集合的计算方法
- 因公招时间和 tags 调整失败的槽位能在之后打开重试
- json 消息是复制粘贴过来的, 不清楚有没有搞对

#### 一些迷惑内容
- 因为要适应公招识别 (只计算不招募) 的任务, 强行把识别选 tag 专门分出 `recruit_calc_task` 函数, 但是又有些信息要传出, 使用了传出参数
- `RecruitTask` 现在变成只负责把设置转发到 `AutoRecruitTask` 了, 这是正常用法吗? 
- `AutoRecruitTask` 的 `m_retry_times` 被设为了 0, 导致 `asst::AutoRecruitTask::_run` 开头的几行没有机会重试
- `asst::AutoRecruitTask::_run` 的可读性好像根本没提高
- 判断是否是公招识别任务的函数在 `recruit_calc_task` 内部也有调用, 理想的情况是这个函数不需要知道自己在执行哪一种
- 有几行太长了

#### 一些疑问
- `RecruitImageAnalyzer` 已经识别了确认按钮的位置, 结果 `AutoRecruitTask::confirm` 又识别了一次 (因为原来就是这么写的, 保留后者比较好写, 但可能会导致多截一张图)
- 使用加急许可为 true 时最大招募次数指什么, 是确认招募的次数, 还是加急许可的使用张数 (虽然大多数时候这两个是一样的)

### **没有在糟糕的网络环境下测过, 可能需要更仔细地测试**

~~希望别出什么事故~~

2022-07-25 15:31 UTC, MistEO reviewed
其他的等我明天慢慢看_(:з」∠)_

2022-07-25 15:33 UTC, zzyyyl commented
我超，大动作啊（

2022-07-25 15:35 UTC, MistEO commented
> 我超，大动作啊（

正好接下来还有 i18n 和大改的肉鸽 + 基建，alpha 版，发！XD

2022-07-25 16:07 UTC, horror-proton commented on src/MeoAssistant/AutoRecruitTask.cpp
> +                    result.push_back(temp2 * rcs_with_single_tag[k]);
草, 这里忘记改了

2022-07-25 16:23 UTC, lhhxxxxx commented on src/MeoAssistant/AutoRecruitTask.cpp
> +            results_json["robot"] = m_skip_robot && has_robot_tag;
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/a0f65684c1d1300903e657923f6a02ecbba550e7/src/MeoAsstGui/Helper/AsstProxy.cs#L607-L653

https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/a0f65684c1d1300903e657923f6a02ecbba550e7/src/MeoAsstGui/Helper/ToastNotification.cs#L430-L462

这块这么写的的主要原因是考虑到回调的写法，回调中小车和五六星的不同处主要在于：
* 通知颜色不同
* 小车提示以及提示性文本在没有选中跳过小车时不显示

如果要去掉这块的硬编码，整个公招回调的逻辑恐怕也需要重写

2022-07-25 16:25 UTC, MistEO commented on src/MeoAssistant/AutoRecruitTask.cpp
> +            results_json["robot"] = m_skip_robot && has_robot_tag;
- 通知颜色不同：传 `special tags`, UI 自行判断颜色，UI 的事情 UI 决定
- 小车提示以及提示性文本在没有选中跳过小车时不显示：由 UI 自行判断是否勾选了该选项再确定是否弹窗

改动并不大我感觉（

2022-07-25 16:49 UTC, lhhxxxxx requested changes
检查的不是很仔细，玛丽再看看

2022-07-25 16:49 UTC, lhhxxxxx commented on src/MeoAssistant/AutoRecruitTask.cpp
> +            info["what"] = "RecruitSpecialTag";
这边是不是应该是RecruitRobotTag

2022-07-25 16:49 UTC, lhhxxxxx commented on src/MeoAssistant/AutoRecruitTask.cpp
> +            results_json["robot"] = m_skip_robot && has_robot_tag;
这个robot控制小车提示以及提示性文本在没有选中跳过小车时不显示
这个不显示应当是基于任务开始的状态而非GUI保存的状态，这里加上这个参数是为了方便GUI的处理，尤其是可以中途修改配置的支持多任务的GUI

2022-07-25 16:49 UTC, lhhxxxxx commented on src/MeoAssistant/RecruitConfiger.h
> +            min_level = 6;
改成7吧，毕竟下面是0

2022-07-25 16:49 UTC, lhhxxxxx commented on src/MeoAssistant/RecruitConfiger.h
> +                min_level = (std::min)(min_level, op.level);
为什么加括号（）

2022-07-25 16:49 UTC, lhhxxxxx commented on src/MeoAssistant/RecruitConfiger.h
> +            avg_level = sum / double(opers.size());
使用static_cast

2022-07-25 16:49 UTC, lhhxxxxx commented on src/MeoAssistant/RecruitConfiger.h
> +        bool has_tag(const std::string &tag) const {
标记为[[nodiscard]]

2022-07-25 16:49 UTC, lhhxxxxx commented on src/MeoAssistant/AutoRecruitTask.cpp
> +    while ((m_use_expedited || !m_pending_recruit_slot.empty()) && recruit_times != m_max_times) {
Comparison of integers of different signs: 'size_t' (aka 'unsigned long long') and 'int' [clang-diagnostic-sign-compare]

2022-07-25 16:49 UTC, lhhxxxxx commented on src/MeoAssistant/AutoRecruitTask.cpp
> +                rc.avg_level /= double(rc.opers.size());
使用staticcast

2022-07-25 16:49 UTC, lhhxxxxx commented on src/MeoAssistant/AutoRecruitTask.cpp
> +        out_selected = int(final_combination.tags.size());
使用staticcast

2022-07-25 16:49 UTC, lhhxxxxx commented on src/MeoAssistant/AutoRecruitTask.cpp
> +            results_json["robot"] = m_skip_robot && has_robot_tag;
这个robot控制小车提示以及提示性文本在没有选中跳过小车时不显示
这个不显示应当是基于任务开始的状态而非GUI保存的状态，这里加上这个参数是为了方便GUI的处理，尤其是可以中途修改配置的支持多任务的GUI

2022-07-25 16:50 UTC, lhhxxxxx commented on src/MeoAssistant/AutoRecruitTask.cpp
> +            results_json["robot"] = m_skip_robot && has_robot_tag;
所以新ui什么时候出

2022-07-25 16:50 UTC, MistEO commented on src/MeoAssistant/AutoRecruitTask.cpp
> +            results_json["robot"] = m_skip_robot && has_robot_tag;
中途修改配置就更应该按 UI 最新配置来了_(:з」∠)_

2022-07-25 16:52 UTC, lhhxxxxx commented on src/MeoAssistant/AutoRecruitTask.cpp
> +            results_json["robot"] = m_skip_robot && has_robot_tag;
并不吧，如果你运行时按不跳过来，中途选了跳过，这时候回传一个提示是让你高血压吗（）

2022-07-25 16:53 UTC, lhhxxxxx commented on src/MeoAssistant/AutoRecruitTask.cpp
> +            results_json["robot"] = m_skip_robot && has_robot_tag;
毕竟已经刷掉/用掉了

2022-07-25 17:10 UTC, horror-proton commented on src/MeoAssistant/RecruitConfiger.h
> +                min_level = (std::min)(min_level, op.level);
这其实是 MSVC 的毛病

2022-07-25 20:32 UTC, lhhxxxxx commented on src/MeoAssistant/RecruitConfiger.h
> +                min_level = (std::min)(min_level, op.level);
还真是，但单独拿出来却可以过编译，我不理解

2022-07-25 20:37 UTC, lhhxxxxx commented on src/MeoAssistant/RecruitConfiger.h
> +                min_level = (std::min)(min_level, op.level);
懂了，msvc有全局宏maxmin，但它为什么不大写？？？

2022-07-25 20:41 UTC, lhhxxxxx commented on src/MeoAssistant/RecruitConfiger.h
> +                min_level = (std::min)(min_level, op.level);
这也太逆天了（）

2022-07-26 05:52 UTC, horror-proton commented on src/MeoAssistant/RecruitTask.cpp
>      bool skip_robot = params.get("skip_robot", true);
现在是否要自动确认招募是由 `confirm` 和 `skip_robot` 确定的, 但就算这样硬加了个小车好像也不能完全描述清楚, 比如有些人只想关注 *生存* tag, 有些人只想关注**不可寻访的五星干员** (*因陀罗*, *火神*),  有些人只想关注**不可寻访的四星和五星干员** (*因陀罗*, *火神*, *艾丝黛尔*, *清流*). 
而且就算解释清楚了, 什么情况应该让用户手动来搞, 是只有遇到**存在只可能出现用户关注的干员的 tag 组合**才跳过吗...

也许应该直接放弃选定干员, 改成选定 tags, 就是让用户指定一些 tag 集合, 当前槽位如果包含任意一个集合中的所有 tag, 就跳过让用户手动来搞. 那这样 `confirm` 是不是也应该去掉, 改成 tag 集合的预设 (思考

但是这样应该传入什么? 传入 tag 文本肯定不大合适, gamedata 里有 tag id 或者顺序吗, 而且我也不知道怎么写 GUI...

2022-07-26 05:53 UTC, horror-proton commented on src/MeoAssistant/RecruitTask.cpp
>      bool skip_robot = params.get("skip_robot", true);
而且这个 pr 只是把先把两个任务合并成一个, 并且希望别出什么把人家高资干员刷掉或者用完加急许可之类的 bug, 改接口可能应该在之后另外开一个 branch 比较合适? 不然可能会有混乱 (

2022-07-26 13:32 UTC, MistEO commented on src/MeoAssistant/RecruitTask.cpp
>      bool skip_robot = params.get("skip_robot", true);
确实，下次单独整一个_(:з」∠)_

2022-07-26 13:32 UTC, MistEO commented on src/MeoAssistant/AutoRecruitTask.cpp
> +            results_json["robot"] = m_skip_robot && has_robot_tag;
下次单独整一个（

2022-07-26 14:44 UTC, MistEO commented
当 `招聘许可` 数量不足时，没有出现招募失败报错，并且死循环（任务不会结束）

![image](https://user-images.githubusercontent.com/18511905/181036708-ee06db43-57de-4360-8da3-69a8884e81fb.png)

![image](https://user-images.githubusercontent.com/18511905/181036825-427e5a54-fe98-468d-b848-c500e32c0125.png)

![image](https://user-images.githubusercontent.com/18511905/181036960-adceb0ef-d9a7-4455-ba9a-62f78958e0b4.png)


最后的是我手动结束的

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9190762/asst.log)

2022-07-26 15:19 UTC, horror-proton commented
> 当 `招聘许可` 数量不足时，没有出现招募失败报错，并且死循环（任务不会结束）

其实并没有死循环, 只是重试次数太多了, 这里会尝试 $4 \times 3=12$ 次, 因为作为 `AbstractTask` 重试时 `slot_fail` 计数器会被重置, 感觉这样不对, 还有我可能把作为 `AbstractTask` 的重试次数设定得太高了

2022-07-26 15:20 UTC, MistEO commented
> > 当 `招聘许可` 数量不足时，没有出现招募失败报错，并且死循环（任务不会结束）
> 
> 其实并没有死循环, 只是重试次数太多了, 这里会尝试 4×3=12 次, 因为作为 `AbstractTask` 重试时 `slot_fail` 计数器会被重置, 感觉这样不对, 还有我可能把作为 `AbstractTask` 的重试次数设定得太高了

现在的版本失败一次应该就会直接结束整个公招任务，感觉这样保险一点

2022-07-26 15:57 UTC, horror-proton commented on src/MeoAssistant/AutoRecruitTask.h
> +        bool recruit_calc_task(bool&, int&);
这个地方比较头疼, 因为这个函数为了处理仅计算不确认的任务抽出来的, 只负责槽位内部的事情, 打开/确认/关闭槽位以及验证是否调整正确都由外面的函数完成, 所以要传出的东西比较多, 不知道有没有更好的设计方法 🤔 
我先试试看用 `tuple` 吧

2022-07-26 15:58 UTC, MistEO commented on src/MeoAssistant/AutoRecruitTask.h
> +        bool recruit_calc_task(bool&, int&);
tuple 也难看，搞个类内的 private struct 怎么样

2022-07-26 16:30 UTC, horror-proton commented
> 现在的版本失败一次应该就会直接结束整个公招任务，感觉这样保险一点

草, 现在的版本直接结束任务居然是通过直接不回公招页面让 `check_recruit_home_page` 失败来达到的 🤯

2022-07-26 16:53 UTC, horror-proton commented on src/MeoAssistant/AutoRecruitTask.h
> +        bool recruit_calc_task(bool&, int&);
是返回一个 struct 吗

2022-07-27 01:36 UTC, MistEO commented
> > 现在的版本失败一次应该就会直接结束整个公招任务，感觉这样保险一点
> 
> 草, 现在的版本直接结束任务居然是通过直接不回公招主页面让 `check_recruit_home_page` 失败来达到的 🤯

点了确认理应在主页了，没回主页说明哪里出错了，我觉得合理（确信

2022-07-27 02:43 UTC, horror-proton commented
还有就是上面提到的 `RecruitImageAnalyzer::confirm_analyze()` 的识别结果是完全浪费了的 (现在的版本也是), 应该把它利用起来, 还是直接删掉

2022-07-27 03:32 UTC, MistEO commented
我感觉可以删，这个多截图一次没啥必要

2022-07-27 09:13 UTC, MistEO commented
link to https://github.com/MaaAssistantArknights/MaaAssistantArknights/projects/1#card-83722187

2022-07-27 16:43 UTC, MistEO approved these changes

2022-07-28 11:03 UTC, merged