Code Tidy
MaaAssistantArknights/MaaAssistantArknights pull request #1374
Opened 2022-07-29 19:30 UTC by lhhxxxxx

2022-07-29 20:12 UTC, MistEO commented
我认为代码清理是为了可读性服务的，而不是为了清理而清理。C++ 部分只有虚析构函数增加 `override` 关键词可被接受。其他的不接受合并。

C# 我不懂，等大佬们看看

2022-07-29 20:13 UTC, MistEO requested changes
如上。

2022-07-29 20:18 UTC, lhhxxxxx commented
[[nodiscard]]呢

2022-07-29 20:18 UTC, lhhxxxxx commented
以及头文件的清理

2022-07-29 20:18 UTC, lhhxxxxx commented
可读性应该只和冗余命名空间相关

2022-07-29 20:20 UTC, lhhxxxxx commented
以及，std等命名空间前为何要加::取全局空间运算符？

2022-07-29 22:14 UTC, MistEO commented on src/MeoAssistant/AsstInfrastDef.h
> +            skills = move(skill_vec);
std 没了（

2022-07-29 22:17 UTC, lhhxxxxx commented on src/MeoAssistant/AsstInfrastDef.h
> +            skills = move(skill_vec);
```suggestion
            skills = std::move(skill_vec);
```

2022-07-29 22:17 UTC, lhhxxxxx commented on src/MeoAssistant/OcrPack.cpp
> +std::vector<asst::TextRect> asst::OcrPack::recognize(const cv::Mat& image, const Rect& roi, const TextRectProc& pred, bool without_det)
```suggestion
std::vector<asst::TextRect> asst::OcrPack::recognize(const cv::Mat& image, const Rect& roi, const asst::TextRectProc& pred, bool without_det)
```

2022-07-29 22:17 UTC, lhhxxxxx commented on src/MeoAssistant/OcrPack.cpp
> +std::vector<asst::TextRect> asst::OcrPack::recognize(const cv::Mat& image, const TextRectProc& pred, bool without_det)
```suggestion
std::vector<asst::TextRect> asst::OcrPack::recognize(const cv::Mat& image, const asst::TextRectProc& pred, bool without_det)
```

2022-07-30 03:25 UTC, horror-proton reviewed
C++ 的名称查找是个很大的坑, 我也说不出到底怎么写更好, 有些稍微解释一下
- 全局命名空间之前加 `::` 好像是微软的风格, 有些 Windows API 可以加一下就当是入乡随俗, 其他地方应该确实没必要
- 那个 `move` 不加 `std::` 是可以的, 能让 ADL 自动找到 `std::move`, 如果是在写什么大的模板库甚至最好不加. 但这里还是用 `std::move` 的好, 毕竟这里参数是固定的, 用 `std::move` 不会出错
- 参数里面的 `asst::` 加也行不加也行, `namespace` 外面的声明和在里面的一样, 会优先找到 `asst::` 里的名字, 不过应该注意 `cv::` 里面也有 `Point` 和 `Rect`
- `cv::imwrite` 这种还是写全比较好, 第一个参数是 `std::string`, 这一般人第一眼也看不出这里可以 ADL 啊
- 另外我感觉 `AbstractTask.cpp` 开头的 `using namespace asst;` 看上去不是很安全

2022-07-30 06:19 UTC, MistEO approved these changes

2022-07-30 07:59 UTC, MistEO commented
C# 大佬捏，救一救啊（

2022-07-30 08:19 UTC, LiamSho commented
C# 这边也就那样啊（

也就是我用Rider打开之后一堆下划线。。。

包括但不限于：

- 多余的 else
- 使用 var 代替类型
- Possiable NullReferenceException
- Possiable InvalidCastException
- Inconsistent Naming
- Assigned but never used

等 300+黄色下划线（

2022-07-30 08:20 UTC, zzyyyl commented
C# 那边 XAML 的绿色下划线有没有可能解决啊（？

2022-07-30 08:22 UTC, LiamSho commented on src/MeoAsstGui/Helper/AutoScroll.cs
> +                _autoScroll = Math.Abs(scroll.VerticalOffset - scroll.ScrollableHeight) < 1e-6;
或许可以拆到一个Extension Method去

``` csharp
public static bool EqualTo(this float x, float y) => Math.Abs(x - y) < 1e-6;
```

2022-07-30 08:28 UTC, LiamSho commented
> C# 那边 XAML 的绿色下划线有没有可能解决啊（？

语言文件一堆 Inconstant Naming，建议直接忽略（

Rider 是里面一堆黄色下划线的Warning（和VS好像不一样？），Rider 里面关掉就是加个注释

``` xml
<!-- ReSharper disable InconsistentNaming -->
```

2022-07-30 09:16 UTC, lhhxxxxx commented
> C# 这边也就那样啊（
> 
> 也就是我用Rider打开之后一堆下划线。。。
> 
> 包括但不限于：
> 
> * 多余的 else
> * 使用 var 代替类型
> * Possiable NullReferenceException
> * Possiable InvalidCastException
> * Inconsistent Naming
> * Assigned but never used
> 
> 等 300+黄色下划线（

Possiable NullReferenceException这个本来想修的，但有些地方实在太复杂了，我选择放弃

2022-07-30 09:21 UTC, lhhxxxxx commented
rider其实还有一种绿色点状下划线（不是波浪线），对应的是可优化的代码，这个反而比较有用，但好像不会在warning列表里显示

2022-07-30 10:28 UTC, lhhxxxxx commented on src/MeoAsstGui/Helper/AutoScroll.cs
> +                _autoScroll = Math.Abs(scroll.VerticalOffset - scroll.ScrollableHeight) < 1e-6;
问题是放哪（）
C#似乎没有合适的Utils文件？

2022-07-30 10:30 UTC, LiamSho commented
扩展方法一般放Common/Extensions/xxxExtension.cs 或者单纯的 Extensions/xxxExtension.cs

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: lhhxxxxx ***@***.***>
Sent: Saturday, July 30, 2022 6:28:32 PM
To: MaaAssistantArknights/MaaAssistantArknights ***@***.***>
Cc: Alisa ***@***.***>; Review requested ***@***.***>
Subject: Re: [MaaAssistantArknights/MaaAssistantArknights] Code Tidy (PR #1374)


@lhhxxxxx commented on this pull request.

________________________________

In src/MeoAsstGui/Helper/AutoScroll.cs<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMaaAssistantArknights%2FMaaAssistantArknights%2Fpull%2F1374%23discussion_r933784524&data=05%7C01%7C%7C8a581d6083ce4e13787508da721640a8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637947737163833213%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=rzfQCpS4LpUuUtCSoc81KZ2WyOXGmzHXtreBoQQinwU%3D&reserved=0>:

> @@ -67,7 +67,7 @@ private static void ScrollChanged(object sender, ScrollChangedEventArgs e)



             if (e.ExtentHeightChange == 0)

             {

-                _autoScroll = scroll.VerticalOffset == scroll.ScrollableHeight;

+                _autoScroll = Math.Abs(scroll.VerticalOffset - scroll.ScrollableHeight) < 1e-6;



问题是放哪（）
C#似乎没有合适的Utils文件？

―
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMaaAssistantArknights%2FMaaAssistantArknights%2Fpull%2F1374%23discussion_r933784524&data=05%7C01%7C%7C8a581d6083ce4e13787508da721640a8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637947737163833213%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=rzfQCpS4LpUuUtCSoc81KZ2WyOXGmzHXtreBoQQinwU%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG37FDUPD3LT3XGDH7KB5S3VWT7VBANCNFSM55BXNGXA&data=05%7C01%7C%7C8a581d6083ce4e13787508da721640a8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637947737163833213%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=iQoAbFYughbmhajb%2Fo3k6Z7tG2JIWI3Q16dn%2FA7c%2Fhc%3D&reserved=0>.
You are receiving this because your review was requested.Message ID: ***@***.***>

2022-07-30 11:41 UTC, lhhxxxxx commented on src/MeoAsstGui/Helper/AutoScroll.cs
> +                _autoScroll = Math.Abs(scroll.VerticalOffset - scroll.ScrollableHeight) < 1e-6;
感觉这个已经超出code tidy的范畴了，等需要refactor的时候再弄吧

2022-07-30 19:12 UTC, MistEO commented
还改么，我合了啊？

2022-07-30 19:12 UTC, MistEO commented
算了弄好你自己合）

2022-07-30 19:20 UTC, lhhxxxxx commented
再不合我怕conflict了

2022-07-30 19:20 UTC, merged