chore: 使用 concept 优化代码
MaaAssistantArknights/MaaAssistantArknights pull request #1402
Opened 2022-08-01 15:18 UTC by zzyyyl

等 [c++20 那个 pr](https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/1391) 合了再来看看这个，我已经等不及了（

2022-08-01 16:40 UTC, MistEO requested changes

2022-08-01 16:40 UTC, MistEO commented on src/MeoAssistant/Assistant.cpp
> +            const auto& [id, task_ptr] = m_tasks_list.front();
你仔细想想这里能不能引用。。

2022-08-01 16:40 UTC, zzyyyl commented on src/MeoAssistant/Assistant.cpp
> +            const auto& [id, task_ptr] = m_tasks_list.front();
欸（？

2022-08-02 02:08 UTC, MistEO commented on src/MeoAssistant/TaskData.h
> -                return it->second;
之前这里少转一次啊， `std::dynamic_pointer_cast` 是运行期，多多少少有性能消耗（确信

2022-08-02 02:09 UTC, zzyyyl commented on src/MeoAssistant/TaskData.h
> -                return it->second;
草，那我给你再加一个

2022-08-02 11:59 UTC, merged