feat:dorm
MaaAssistantArknights/MaaAssistantArknights pull request #1475
Opened 2022-08-06 15:39 UTC by Hydrogina

增加宿舍蹭信赖功能。现在如果所有心情未满的干员已进入宿舍，会将信赖未满的干员加入宿舍的空位中。

2022-08-06 16:44 UTC, horror-proton reviewed
看上去是不错的想法

2022-08-06 16:44 UTC, horror-proton commented on src/MeoAssistant/MeoAssistant.vcxproj
> +    <PlatformToolset>v143</PlatformToolset>
因为某种原因 MAA 使用的 `v142` (我也不知道为什么). 
我也是自己编译的时候用的也是 `v143`, 但是不应该把对这两个文件的修改 commit 进来.
你可以趁现在没人 amend 一下, 然后 force push, 如果你不熟悉 git 操作的话, 在后面加一个 commit 改回 `v142` 可能也行?

2022-08-06 16:52 UTC, MistEO requested changes
感谢提交，粗略扫了一眼，等有空我再细看一下_(:з」∠)_

2022-08-06 16:52 UTC, MistEO commented on src/MeoAssistant/InfrastAbstractTask.h
> +        virtual bool click_SortByTrustButton();// 点击干员选择页面的“按信赖值排序”按钮
这个命名有点奇怪，尽量用下划线保持一致_(:з」∠)_

2022-08-06 16:52 UTC, MistEO commented on resource/tasks.json
> +        "specificRect": [
`specificRect` 是一种比较偷懒的做法，如果按钮比较好识别的话尽量还是用模板匹配

2022-08-08 12:36 UTC, MistEO requested changes

2022-08-08 12:36 UTC, MistEO commented on src/MeoAssistant/InfrastDormTask.cpp
>          if (m_all_finished) {
既然不要 break 了就可以把这个判断去掉_(:з」∠)_

2022-08-08 12:39 UTC, MistEO commented
一个比较棘手的问题是：按上面举例子的情况，第三个宿舍会把第一个宿舍进驻的信赖未满的人，再次放到第三个宿舍中。即第一个宿舍中还是没有信赖未满的人

另一个问题是：`彩虹小队+阿米娅` 这种心情永远是满的组合，按这套逻辑，如果 `彩虹小队` / `阿米娅` 信赖没有满，是会把他们从控制中枢下下来放到宿舍里去的，那样的话控制中枢就空出来了

2022-08-08 23:26 UTC, lhhxxxxx commented
肥鸭信赖没满的话用了是不是不太好

2022-08-10 15:18 UTC, MistEO commented on src/MeoAssistant/InfrastDormTask.cpp
> +                    opername = std::regex_replace(opername, rule, "");
这是在干啥，没太看明白

W, 这种的咋整（

2022-08-10 15:18 UTC, MistEO commented on src/MeoAssistant/InfrastDormTask.cpp
> +                    opername = std::regex_replace(opername, rule, "");
这里应该对比下 face_hash 就好了

2022-08-10 15:21 UTC, horror-proton commented on src/MeoAssistant/InfrastDormTask.cpp
> +                    opername = std::regex_replace(opername, rule, "");
说起来 MAA 里的 face_hash 用的到底是什么算法

2022-08-10 15:21 UTC, MistEO commented on src/MeoAssistant/InfrastDormTask.cpp
> +                    opername = std::regex_replace(opername, rule, "");
从企鹅物流那边嫖来的

2022-08-10 15:50 UTC, Hydrogina commented on src/MeoAssistant/InfrastDormTask.cpp
> +                    opername = std::regex_replace(opername, rule, "");
我试过face_hash，但是不是很准，拖动干员列表之后，同一个干员的face_hash会不一样。
按照信赖值排序后，信赖值会把干员名字盖住，这里只能识别到信赖值，例如"M 194%"。我还在想办法识别干员名字

2022-08-10 16:14 UTC, MistEO commented on src/MeoAssistant/InfrastDormTask.cpp
> +                    opername = std::regex_replace(opername, rule, "");
> 我试过face_hash，但是不是很准，拖动干员列表之后，同一个干员的face_hash会不一样。 按照信赖值排序后，信赖值会把干员名字盖住，这里只能识别到信赖值，例如"M 194%"。我还在想办法识别干员名字

不是直接比较 face_hash 的值是否相同，而是计算两者的 hamming 差值是否小于阈值，可以参考选人那边的逻辑

2022-08-12 11:36 UTC, MistEO commented
所以点下 `未进驻` 不好么_(:з」∠)_

2022-08-12 12:49 UTC, Hydrogina commented
> 所以点下 `未进驻` 不好么_(:з」∠)_

我火星了orz 我刚刚才发现游戏里还有这个功能

2022-08-12 14:59 UTC, MistEO commented on src/MeoAssistant/InfrastAbstractTask.cpp
> +}
利用 tasks.json 里的 next 字段，一次 ProcessTask run 就可以了，不用封三个函数出来。

2022-08-12 15:02 UTC, MistEO commented on resource/tasks.json
> +        "specificRect": [
还是和上面说的一样，尽量用识别，不要直接点，直接点这种做法非常不鲁棒（

2022-08-12 15:02 UTC, MistEO commented on src/MeoAssistant/InfrastDormTask.cpp
> +                    if (!trust_analyzer.analyze()) {
话说信赖值是不是没必要识别，按顺序直接无脑放人怎么样？

2022-08-12 15:02 UTC, MistEO commented on src/MeoAssistant/InfrastDormTask.cpp
> +            }
这是啥，没看明白_(:з」∠)_

2022-08-13 00:16 UTC, Hydrogina commented on src/MeoAssistant/InfrastDormTask.cpp
> +                    if (!trust_analyzer.analyze()) {
如果宿舍里原本有满信赖的人，不识别信赖值就没法把他换下来
也可以每进一个宿舍清空后再点两下按信赖排序，但这样操作就多了，我觉得鲁棒性比较低

2022-08-13 00:20 UTC, Hydrogina commented on src/MeoAssistant/InfrastDormTask.cpp
> +            }
这个主要是为了在放完所有未满心情的人后如果当前宿舍没满需要按信赖值重新识别图像后，跳过一次后面的拖动干员列表

2022-08-13 14:54 UTC, MistEO commented on src/MeoAssistant/InfrastDormTask.cpp
> +                    if (!trust_analyzer.analyze()) {
满信赖且满心情的吗，那他放宿舍里有啥用呀_(:з」∠)_

2022-08-13 15:53 UTC, MistEO requested changes

2022-08-13 15:53 UTC, MistEO commented on resource/tasks.json
> +        ],
这里最好还是图片模板匹配，因为点了一次 `未进驻` 之后，如果我没退出宿舍，并再次执行换班任务，OCR 就会再去点一次 `未进驻` orz

2022-08-13 15:54 UTC, MistEO commented on src/MeoAssistant/InfrastDormTask.cpp
> +            }
加一点点注释吧~ 几个可能的值分别代表什么，不然看的有点懵_(:з」∠)_

2022-08-13 15:55 UTC, MistEO commented
测了几次总体没什么大问题了，再次感谢 ✿✿ヽ(°▽°)ノ✿

2022-08-13 15:57 UTC, MistEO commented on resource/tasks.json
> +        ],
我又去试了一下，似乎只有在仅勾选 `宿舍` 的时候才会有这种问题，只要进一下随便其他房间，再进宿舍，这个 `未进驻` 就被自动取消掉了。。那这个倒也无伤大雅（

2022-08-13 15:59 UTC, ABA2396 commented
加工站的人完成加工后还是在工作的状态，点击未进驻不会筛选出加工站的状态，不过感觉这个问题和训练室差不多了。

2022-08-13 16:00 UTC, MistEO commented
> 加工站的人完成加工后还是在工作的状态，点击未进驻不会筛选出加工站的状态，不过感觉这个问题和训练室差不多了。

不会，现在他的逻辑是先正常换班，人全满了之后再去按 `未进驻` 放入需要加信赖的人，不影响原有逻辑

2022-08-13 16:02 UTC, ABA2396 commented
> > 加工站的人完成加工后还是在工作的状态，点击未进驻不会筛选出加工站的状态，不过感觉这个问题和训练室差不多了。
> 
> 不会，现在他的逻辑是先正常换班，人全满了之后再去按 `未进驻` 放入需要加信赖的人，不影响原有逻辑

原来的换班也不会换加工站的人，但照理来说有些换班应该可以通过总览来实现

2022-08-13 16:03 UTC, MistEO commented
> > > 加工站的人完成加工后还是在工作的状态，点击未进驻不会筛选出加工站的状态，不过感觉这个问题和训练室差不多了。
> > 
> > 
> > 不会，现在他的逻辑是先正常换班，人全满了之后再去按 `未进驻` 放入需要加信赖的人，不影响原有逻辑
> 
> 原来的换班也不会换加工站的人，但照理来说有些换班应该可以通过总览来实现

那就不是这个 pr 的修改范围了

2022-08-13 16:04 UTC, ABA2396 commented
说个其他的问题，见行者的基建技能是 `进驻会客室时，线索搜集速度提升35%，心情每小时消耗+2` 换班时间如果隔得稍微长点就会注意力涣散）

2022-08-13 16:29 UTC, MistEO approved these changes

2022-08-13 16:33 UTC, lhhxxxxx commented
所以不考虑肥鸭的情况了吗

2022-08-13 16:34 UTC, ABA2396 commented
> 所以不考虑肥鸭的情况了吗

等肥鸭信赖满了就没这问题了）

2022-08-13 17:47 UTC, merged