docs: 更新公招数据自动上传的文档
MaaAssistantArknights/MaaAssistantArknights pull request #1608
Opened 2022-08-19 16:25 UTC by zzyyyl

还有一些杂七杂八的文档格式优化

其中 https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/6f1221b8e78283dffc56c1c331de6945fcc7319e 我删掉的应该不是什么日语字符吧 @Tastror

2022-08-19 18:43 UTC, MistEO commented
草，你怎么改个文档都能水 6 个 commit

2022-08-19 18:45 UTC, MistEO requested changes

2022-08-19 18:45 UTC, MistEO commented on README.md
> +- 公招数据上传 [企鹅物流](https://penguin-stats.cn/)，[一图流](https://yituliu.site/maarecruitdata)
这个和上面的是同一行吧，都是公招的

2022-08-19 18:45 UTC, MistEO commented on README.md
> +- 作业分享站 <https://www.prts.plus>：[前端](https://github.com/MaaAssistantArknights/maa-copilot-frontend)，[后端](https://github.com/MaaAssistantArknights/MaaCopilotServer)
所以到底全角半角，你和 @Tastror 先打一架（

2022-08-19 18:46 UTC, lhhxxxxx commented
用typora编辑时使用tab会产生不可见空格字符，也就是这里的0x200b

直接删掉就行

2022-08-20 01:50 UTC, Tastror commented on README.md
> +- 作业分享站 <https://www.prts.plus>：[前端](https://github.com/MaaAssistantArknights/maa-copilot-frontend)，[后端](https://github.com/MaaAssistantArknights/MaaCopilotServer)
中日全角，英文半角
没啥问题，我之前也没改这一部分，只改了我遇到的文档（

2022-08-20 01:57 UTC, Tastror commented
嗯呢 没问题

2022-08-20 03:32 UTC, zzyyyl commented on README.md
> +- 公招数据上传 [企鹅物流](https://penguin-stats.cn/)，[一图流](https://yituliu.site/maarecruitdata)
草，意思是两行合并？

2022-08-20 03:33 UTC, zzyyyl commented
> 草，你怎么改个文档都能水 6 个 commit

那我 squash 几个 commit（？

2022-08-20 03:33 UTC, MistEO commented on README.md
> +- 公招数据上传 [企鹅物流](https://penguin-stats.cn/)，[一图流](https://yituliu.site/maarecruitdata)
是啊，每行一个功能点，公招上传不也是公招的一部分么（

- - 自动公招，可选使用加急许可，一次全部刷完。并自动上传至 [企鹅物流](https://penguin-stats.cn/)，[一图流](https://yituliu.site/maarecruitdata)

2022-08-20 03:58 UTC, zzyyyl commented
7 个 commit 变 5 个！

2022-08-20 05:56 UTC, merged