chore: win32 improvements
MaaAssistantArknights/MaaAssistantArknights pull request #1765
Opened 2022-09-04 17:26 UTC by dantmnf

* 修复一个可能导致 GUI 向 core 传参失败的问题
* 将 OpenCV imread/imwrite 改为 fstream + imencode/imdecode 以支持 Unicode 路径
* 在路径中包含不可转换到 ANSI 代码页的字符时，尝试使用 DOS 8.3 短文件名加载 PaddleOCR
  * 如果当前资源目录没有生成短路径，则尝试在临时文件夹中创建 NTFS 目录链接
* socket 传输使用 OS 选择的空闲端口

2022-09-04 17:36 UTC, MistEO requested changes

2022-09-04 17:36 UTC, MistEO commented on src/MeoAssistant/Controller.cpp
> +    HANDLE pipe_parent_read, pipe_child_write;
要初始化一下

2022-09-04 17:36 UTC, MistEO commented on src/MeoAssistant/OcrPack.cpp
> +    bool use_temp_dir;
初始化_(:з」∠)_

2022-09-04 17:36 UTC, MistEO commented on src/MeoAssistant/OcrPack.cpp
> +    bool use_temp_dir;
不知道还有没有别的

2022-09-04 17:36 UTC, MistEO commented on src/MeoAssistant/OcrPack.cpp
> +{
这个是干嘛的，包括后面删除的逻辑，没看懂（

2022-09-04 17:38 UTC, MistEO commented
完了，dant 写的代码我一大半都看不懂，只能鸡蛋里挑点骨头了（

2022-09-04 17:58 UTC, dantmnf commented on src/MeoAssistant/OcrPack.cpp
> +{
当前路径救不了的话，就跑去 temp 创建个类似软链接的东西，然后 paddle 加载完之后就不会再读了，尽早删掉避免在 temp 里留一大堆让用户以为我们在倒垃圾（

2022-09-05 10:13 UTC, LiamSho commented
> 完了，dant 写的代码我一大半都看不懂，只能鸡蛋里挑点骨头了（

这都是 CPP 你给我 review 我也看不懂啊（

2022-09-05 11:36 UTC, MistEO commented
> > 完了，dant 写的代码我一大半都看不懂，只能鸡蛋里挑点骨头了（
> 
> 这都是 CPP 你给我 review 我也看不懂啊（

最下面有 c# 啊

2022-09-05 13:05 UTC, MistEO commented on src/MeoAssistant/OcrPack.cpp
> +{
什么情况会救不了啊_(:з」∠)_

只有飞桨？为啥其他资源不要

2022-09-05 13:20 UTC, dantmnf commented on src/MeoAssistant/OcrPack.cpp
> +{
因为飞浆要传 ANSI 路径进去初始化（

具体逻辑在主楼第三点

2022-09-05 13:25 UTC, MistEO commented on src/MeoAssistant/AsstPlatformWin32.cpp
> +        wchar_t short_path[MAX_PATH];
这个也要初始化下

2022-09-05 13:25 UTC, MistEO commented on src/MeoAssistant/AsstPlatformWin32.cpp
> +        wchar_t short_path[MAX_PATH];
这个也要初始化下

2022-09-05 13:25 UTC, MistEO commented on src/MeoAssistant/AsstCaller.cpp
>      return handle->connect(adb_path, address, config ? config : std::string());
adb 路径不用转码了么？

2022-09-05 13:25 UTC, MistEO commented on src/MeoAssistant/AsstPlatformPosix.h
> +#endif
这个头文件是空的？

2022-09-05 13:31 UTC, dantmnf commented on src/MeoAssistant/AsstCaller.cpp
>      return handle->connect(adb_path, address, config ? config : std::string());
MAA 内部所有 string 都认为是 UTF-8，调用系统 API 或者第三方库之前再转换

2022-09-05 13:53 UTC, MistEO commented on src/MeoAssistant/AsstPlatformPosix.h
> +#endif
~~那怎么 cpp 里写了那么多~~

2022-09-05 14:19 UTC, MistEO approved these changes

2022-09-05 15:18 UTC, merged