feat: 在信用值溢出时无视黑名单进行购物
MaaAssistantArknights/MaaAssistantArknights pull request #1927
Opened 2022-09-24 14:28 UTC by Hydrogina

在信用交易所正常购物结束后，对信用值进行一次ocr，若信用大于300则无视黑名单进行购物，直到信用值不再溢出

2022-09-24 14:57 UTC, MistEO commented on src/MeoAssistant/CreditShoppingTask.cpp
> +    std::regex rule("[^0-9]"); // 只保留数字
我感觉这种方式不是特别好，建议用 `OcrWithFlagTemplImageAnalyzer` 出来的直接就是完成的数字结果，而且消耗更小。最后也只要 all_of isdigit 检查一下就好了

2022-09-24 14:57 UTC, MistEO commented on src/MeoAssistant/CreditShoppingTask.cpp
> +    std::regex rule("[^0-9]"); // 只保留数字
可以参考 `bool asst::BattleImageAnalyzer::kills_analyze()`, 不过这个考虑的情况比较多最终处理逻辑有点复杂，信用商店最大值固定是 300，可以不用算 `/` 后面的内容，直接把 roi 拉到 `/` 之前就好

2022-09-24 14:57 UTC, MistEO commented on src/MeoAssistant/CreditShoppingTask.cpp
> +std::string asst::CreditShoppingTask::creditOcr()
命名尽量用下划线保持一致吧~

2022-09-24 14:57 UTC, MistEO commented on src/MeoAssistant/CreditShoppingTask.cpp
> +        std::string credit = creditOcr();
后面这一大段没法复用之前的逻辑么（抽象个函数出来之类的），重写一遍有点冗余

2022-09-24 14:58 UTC, MistEO commented
@zzyyyl 这个 issue checker 咋挂了

2022-09-25 06:59 UTC, zzyyyl commented
这玩意有开自选项么？有的人可能会觉得买黑名单的还不如溢出一点点等第二天
特别是如果买了没打折的黑名单商品，那不是血亏（x

2022-09-25 17:00 UTC, MistEO commented on src/MeoAssistant/CreditShoppingTask.cpp
> +std::string asst::CreditShoppingTask::credit_ocr()
不如直接返回个 int？如果识别错了返回个 -1 之类的

2022-09-25 17:07 UTC, MistEO commented on src/MeoAssistant/MallTask.cpp
> +    bool save_credit_enabled = params.get("save_credit_enabled", true);
这个参数感觉不容易理解，要考虑其他的集成者（现在的 maa core 已经不光是我们的 wpf 在用了），或许可以叫 force_shopping_if_credit_full 之类的，也可以想想有没有啥更好的名字

另外 `docs/3.1-集成文档.md` 和 `docs/en-us/3.1-INTEGRATION.md` 也补充下吧~

2022-09-26 06:35 UTC, zzyyyl commented on docs/3.1-集成文档.md
> +   "force_shopping_if_credit_full" // 是否在信用溢出时无视黑名单，默认为 true
```suggestion
   "force_shopping_if_credit_full": bool // 是否在信用溢出时无视黑名单，默认为 true
```
英文文档里还有个

2022-09-26 06:35 UTC, zzyyyl commented on src/MeoAssistant/CreditShoppingTask.cpp
> +            if (credit <0 || credit <= m_max_credit) {//信用值不再溢出，停止购物
```suggestion
            if (credit <= m_max_credit) {//信用值不再溢出，停止购物
```

下面的 `credit > 0 && ...` 也可以改

2022-09-27 08:58 UTC, MistEO requested changes

2022-09-27 08:58 UTC, MistEO commented on src/MeoAssistant/CreditShoppingTask.h
> +        int m_max_credit = 300;
最好放在 public 改成 `static constexpr MaxCredit = 300;`

2022-09-27 08:58 UTC, MistEO commented on src/MeoAssistant/MallTask.cpp
> +    m_shopping_task_ptr->set_force_shopping_if_credit_full(force_shopping_if_credit_full);
这几行应该放到下面的 if (shopping) 里面

2022-09-27 08:58 UTC, MistEO commented on src/MeoAssistant/CreditShoppingTask.h
> +        bool m_force_shopping_if_credit_full = true;         // 设置是否防止信用值溢出
感觉默认值应该用 false

2022-09-27 08:58 UTC, MistEO commented on src/MeoAssistant/CreditShoppingTask.cpp
> +    std::string credit = credit_analyzer.get_result().front().text;
const std::string& credit = xxx

2022-09-27 08:58 UTC, MistEO commented on src/MeoAssistant/CreditShoppingTask.cpp
> +            if (!credit_shopping(false, true)) {
另外我觉得一个 run 里面买两次（调用两次 credit_shopping）有点乱，可以直接在 MallTask 里面多增加一个 m_shopping_force_task_ptr，如果 params 是 false 可以直接把这个 task_ptr->set_enable(false);

CreditShoppingTask::_run() 仅通过 m_xxxx 各种参数来判断要走哪个逻辑

2022-09-27 16:04 UTC, merged

2022-09-27 16:05 UTC, MistEO commented
Thanks for your contributions!