feat: 添加借助战作战赚信用功能
MaaAssistantArknights/MaaAssistantArknights pull request #2849
Opened 2022-11-22 10:28 UTC by Hydrogina

添加借助战作战赚信用功能，借随机助战打一次OF-1，赚30信用。
OF-1是别传火蓝之心第一关火蓝之心，不消耗理智，且几乎任何近战位干员都能单守。

2022-11-22 12:59 UTC, MistEO commented
这真的有必要吗（

2022-11-23 03:53 UTC, Hydrogina commented
![屏幕截图 2022-11-23 114219](https://user-images.githubusercontent.com/46482682/203465266-2244bba0-0bc7-4742-8aaf-f84882dca4b4.png)
  在任务列表中加入了“借助战作战”的选项，可以排序和开关。不需要这个功能的用户可以将其关闭，不会影响到原有的任务流程。

  借助战作战的流程大致如下：
1.和FightTask一样导航到OF-1
2.调用CopilotTask进行自动编队，这里我写了一份OF-1作业，包含几个近战干员的干员组，最低配置是芬。
3.借一个随机的助战先锋。借先锋是因为先锋在助战页面的第一页。
4.CopilotTask进行自动战斗，只用部署一个近战位干员。
5.助战结束，回到关卡界面。

2022-11-23 07:25 UTC, MistEO commented
我觉得这个收益太少了，主界面增加一个选项没有必要。而且这样写不太优雅，冗余代码很多，像 吃源石、吃理智药，这些参数这个任务都用不上，却还是照着复制过来了。

或许可以考虑放在 “访问好友” 或者哪里，作为一个设置中的开关项来开启（勾选了的话，访问完好友就顺便去打一局）。然后把访问好友改叫 “获取信用” 之类的（？）

不过我还是倾向于直接不做这个（

2022-11-23 07:26 UTC, MistEO commented
Copilot 任务里增加的助战功能也不太有封装性，感觉就是专门为了这个任务增加的。以后 Copilot 如果要做支持助战功能，这块也会产生兼容性问题

2022-11-23 13:24 UTC, ABA2396 commented on resource/tasks.json
> +    "StageOF": {
之前是写过OF章节导航的，OF-F3的导航在1065行左右

2022-11-23 13:51 UTC, MistEO requested changes

2022-11-23 13:51 UTC, MistEO commented on src/MeoAssistant/Task/CreditFightTask.cpp
> +    copilotparams["filename"] = "resource/credit_fight_copilot.json";
这个路径不对，仅在 win wpf 上这样写能生效，别的平台和接口都跑不起来。得想办法把 resource_dir 传进来

2022-11-23 13:51 UTC, MistEO commented on src/MeoAssistant/Task/CreditFightTask.cpp
> +    copilotparams["stage_name"] = "activities/act3d0/level_act3d0_01";// OF-1
关卡名建议从下面这个 json 里读，json 里直接写 OF-1 就行了

2022-11-23 13:51 UTC, MistEO commented on src/MeoAssistant/Task/CreditFightTask.cpp
> +    const std::string stage = "OF-1";
这个最好也从 json 里读

2022-11-23 13:51 UTC, MistEO commented on src/MeoAssistant/Task/CreditFightTask.h
> +    class CreditFightTask final : public PackageTask
不对外提供接口的任务不要从 PackageTask 继承，可以从 AbstractTask

2022-11-23 13:51 UTC, MistEO commented on src/MeoAssistant/Resource/CopilotConfiger.cpp
> +    battle_actions.support_unit_name = json.get("support_unit", "name", std::string());
Copilot 以后肯定要支持助战的，但是助战从 json 读是不合理的。一般情况下是使用别人发过来的作业，他也不知道我要啥助战。所以应该是 CopilotTask 那边提供一个 set 接口。在 MallTask 里调用就好了

2022-11-23 13:51 UTC, MistEO commented on src/MeoAssistant/Task/CreditFightTask.cpp
> +        .set_times_limit("EndOfAction", 0)
这些真的需要吗。。这和刷理智不是同样的情况啊

2022-11-23 13:51 UTC, MistEO commented on src/MeoAssistant/Task/CreditFightTask.cpp
> +        m_start_up_task_ptr->set_tasks({ "StageBegin" }).set_times_limit("GoLastBattle", 0);
这里不需要和上面的 set 等一大堆区分开来，因为没有运行时设置的 case

2022-11-23 13:51 UTC, MistEO commented on src/MeoAssistant/Task/CreditFightTask.h
> +        static constexpr const char* TaskType = "CreditFight";
如果不从 PackageTask 继承的话这个可以去掉

2022-11-23 13:51 UTC, MistEO commented on src/MeoAssistant/Task/VisitTask.cpp
> +    bool credit_fight_task_enabled = params.get("credit_fight_task_enabled", false);
这个是纯 MAA 内部的接口，不需要拿 json 转一道，该传什么参数传什么

2022-11-23 13:51 UTC, MistEO commented on src/MeoAsstGui/Resources/Localizations/zh-cn.xaml
> +    <system:String x:Key="CreditFight">访问好友后借助战作战</system:String>
借助战作战，有点不明所以，不知道是要干啥。加个 Tips ？

2022-11-23 13:51 UTC, MistEO commented on src/MeoAssistant/Assistant.cpp
> +        ASST_ASSISTANT_APPEND_TASK_FROM_STRING_IF_BRANCH(StartUpTask)
你的 clang-format 的版本有点老，这里对齐错了，最好把文件还原下

2022-11-23 13:51 UTC, MistEO commented on src/MeoAssistant/Task/CreditFightTask.cpp
> +      m_fight_task_ptr(std::make_shared<ProcessTask>(m_callback, m_callback_arg, TaskType)),
这些不涉及运行期 set 的参数，不需要搞个成员变量

2022-11-23 13:51 UTC, MistEO commented on src/MeoAssistant/Task/Sub/BattleFormationTask.cpp
> +        if (!select_random_support_unit()) {
如上面说的，可以改成 set 到某个成员变量之后读，而不是从 json 读

2022-11-23 13:52 UTC, MistEO commented on src/MeoAssistant/Task/CreditFightTask.cpp
> +    copilotparams["filename"] = "resource/credit_fight_copilot.json";
可以像 UserDir 一样在 utils 里面放个单例

2022-11-24 03:07 UTC, MistEO commented on src/MeoAssistant/Task/CreditFightTask.cpp
> +    copilotparams["filename"] = "resource/credit_fight_copilot.json";
dev 上新改了一下，直接 `ResDir.get()` 即可

2022-11-24 06:55 UTC, Hydrogina commented on src/MeoAssistant/Task/CreditFightTask.h
> +    class CreditFightTask final : public PackageTask
我有一个问题
在继承PackageTask 时运行子任务是这么写的
 m_subtasks.emplace_back(m_start_up_task_ptr);
    m_subtasks.emplace_back(m_stage_navigation_task_ptr);
    m_subtasks.emplace_back(m_copilot_task_ptr);
    m_subtasks.emplace_back(m_fight_task_ptr);
但是从 AbstractTask继承后就用不了m_subtasks了，运行子任务该怎么写？

2022-11-24 09:32 UTC, MistEO commented on src/MeoAssistant/Task/CreditFightTask.h
> +    class CreditFightTask final : public PackageTask
封装几个函数挨个调下。PackageTask 里面其实也就是轮流调

2022-11-24 09:38 UTC, MistEO commented on src/MeoAssistant/Task/CreditFightTask.cpp
> +    const std::string stage = "OF-1";
导航关卡名也从 json 里读吧，直接拿 stage_name 就好了，就写 "OF-1"，下面的 copilot params 是支持的，没必要一定是 levelID

2022-11-24 09:38 UTC, MistEO commented on src/MeoAssistant/Task/CreditFightTask.cpp
> +    copilotparams["stage_name"] = "activities/act3d0/level_act3d0_01"; // OF-1
这个也是

2022-11-24 09:39 UTC, MistEO commented on src/MeoAssistant/Task/CreditFightTask.cpp
> +    std::string copilot_path = utils::path_to_utf8_string(ResDir.get()) + "\\resource\\credit_fight_copilot.json";
```suggestion
    std::string copilot_path = utils::path_to_utf8_string(ResDir.get() / "resource" / "credit_fight_copilot.json");
```

2022-11-24 09:40 UTC, MistEO commented on src/MeoAsstGui/Helper/StageManager.cs
> +                { "OF-1", new StageInfo { Display = "OF-1", Value = "OF-1" } },
这个好像用不上？

2022-11-25 03:43 UTC, Hydrogina commented on src/MeoAssistant/Task/CreditFightTask.cpp
> +      m_fight_task_ptr(std::make_shared<ProcessTask>(m_callback, m_callback_arg, TaskType)),
加了个set_subtasks_enable()来控制开关，还是继续用成员变量了

2022-11-25 13:09 UTC, MistEO approved these changes
其他的感觉 ok 了，还有点是 MAA 本来的架构问题，先合了再说.jpg

感谢你的提交！

2022-11-25 13:09 UTC, MistEO commented on src/MeoAssistant/Task/CopilotTask.cpp
> +    if (!Copilot.load(utils::path(filename))) {
这块的逻辑非常不好，不过本来这里就是这样写的，目前的架构确实也没有太好的解决方案，先就这样吧等我有空重构一下

2022-11-25 13:09 UTC, MistEO commented on src/MeoAssistant/Task/CreditFightTask.cpp
> +    visit_subtasks.emplace_back(m_start_up_task_ptr);
为啥一定要 subtask push 呢。。

2022-11-25 13:10 UTC, merged

2022-11-25 13:30 UTC, Hydrogina commented on src/MeoAssistant/Task/CreditFightTask.cpp
> +    visit_subtasks.emplace_back(m_start_up_task_ptr);
子任务直接run()总在报一些非法访问的错，我还没搞明白是怎么回事