feat.新增对新关卡`1-7`的支持
MaaAssistantArknights/MaaAssistantArknights pull request #407
Opened 2022-05-02 10:03 UTC by zzyyyl

ohhhhhhh~ ~~爷青结~~
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/389
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/265
1-7关卡识别是用OCR实现的，不知道会不会出事，反正我`1080x720`的`score`都是0.95以上
整体的导航暂时都只在`1080x720`测试了，等会儿我试试其他分辨率
~~自己动手丰衣足食~~

2022-05-02 10:14 UTC, zzyyyl commented
很好，`1600x900`的分辨率也能跑，大概没问题了

2022-05-02 12:46 UTC, MistEO commented
好耶，~~终于长出来了~~

2022-05-03 14:18 UTC, MistEO requested changes

2022-05-03 14:18 UTC, MistEO commented on resource/tasks.json
> +            "SwipeLeftToStage1-7"
这里是不是写错了，好像是 `SwipeRightToStage1-7` ？

2022-05-03 14:18 UTC, MistEO commented on resource/tasks.json
> +        "algorithm": "OcrDetect",
这 ocr 太慢了，一屏幕关卡名，或许截个图用模板匹配好点_(:з」∠)_

2022-05-03 14:18 UTC, MistEO commented on resource/tasks.json
> +            "SwipeLeftToStage1-7"
另外这个滑动非常快，我不知道会不会滑飞出去，_(:з」∠)_可能得单独加个 SwipeSlowy 之类的 action

2022-05-03 14:19 UTC, MistEO commented on resource/tasks.json
> +            "1-8",
我超，好暴力（

2022-05-03 14:22 UTC, zzyyyl commented on resource/tasks.json
> +            "SwipeLeftToStage1-7"
> 这里是不是写错了，好像是 `SwipeRightToStage1-7` ？

我想的是不会滑动超过一个屏幕，这样左滑之后应该不需要再右滑（
我实际测试的时候滑动也确实没超过一个屏幕，或许可以加一个右滑？~~（但是我怕会死循环）~~

2022-05-03 14:24 UTC, MistEO commented on resource/tasks.json
> +            "SwipeLeftToStage1-7"
我刚试了一下，就滑了一次直接从 `1-12` 飞到了 `1-1` orz

2022-05-03 14:24 UTC, zzyyyl commented on resource/tasks.json
> +        "algorithm": "OcrDetect",
真的吗，我OCR挺快的啊，插着电也就300ms左右（我模拟器截个图都要500ms）

2022-05-03 14:25 UTC, MistEO commented on resource/tasks.json
> +        "algorithm": "OcrDetect",
> 真的吗，我OCR挺快的啊，插着电也就300ms左右（我模拟器截个图都要500ms）

彳亍，那这个摆了

2022-05-03 14:26 UTC, zzyyyl commented on resource/tasks.json
> +        "algorithm": "OcrDetect",
还没试过的话可以用这个[临时版本](https://github.com/zzyyyl/MaaAssistantArknights/actions/runs/2258000973)试试（？

2022-05-03 14:27 UTC, MistEO commented on resource/tasks.json
> +        "algorithm": "OcrDetect",
> 还没试过的话可以用这个[临时版本](https://github.com/zzyyyl/MaaAssistantArknights/actions/runs/2258000973)试试（？

我跑了，感觉在这卡的有点久，不过我没看日志（

2022-05-03 14:27 UTC, MistEO commented on resource/tasks.json
> +            "SwipeLeftToStage1-7"
adb swipe 似乎是应该是电脑越卡反而滑动的越慢_(:з」∠)_原因没搞懂

2022-05-03 14:29 UTC, MistEO commented on resource/tasks.json
> +            "SwipeLeftToStage1-7"
> 另外这个滑动非常快，我不知道会不会滑飞出去，_(:з」∠)_可能得单独加个 SwipeSlowy 之类的 action

或许可以复用基建选人的时候慢慢滑动的那套逻辑，我来搞吧=。=

2022-05-03 14:31 UTC, zzyyyl commented on resource/tasks.json
> +            "SwipeLeftToStage1-7"
adb swipe 可以加个滑动时间的

2022-05-03 14:39 UTC, zzyyyl commented on resource/tasks.json
> +            "SwipeLeftToStage1-7"
> > 另外这个滑动非常快，我不知道会不会滑飞出去，_(:з」∠)_可能得单独加个 SwipeSlowy 之类的 action
> 
> 或许可以复用基建选人的时候慢慢滑动的那套逻辑，我来搞吧=。=

能不能把`ProcessTask::exec_swipe_task`里的`swipe()`加一个`duration`参数？

2022-05-03 14:41 UTC, MistEO commented on resource/tasks.json
> +            "SwipeLeftToStage1-7"
> > > 另外这个滑动非常快，我不知道会不会滑飞出去，_(:з」∠)_可能得单独加个 SwipeSlowy 之类的 action
> > 
> > 
> > 或许可以复用基建选人的时候慢慢滑动的那套逻辑，我来搞吧=。=
> 
> 能不能把`ProcessTask::exec_swipe_task`里的`swipe()`加一个`duration`参数？

差不多是这个意思，头疼的是 adb swipe 还有个 [bug](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/resource/config.json#L16), 想慢慢滑就得把这套逻辑再翻出来 orz

2022-05-03 14:47 UTC, MistEO commented on resource/tasks.json
> +            "SwipeLeftToStage1-7"
> * 可以加，逻辑上没问题，但是相当于所有 TaskInfo 都要多一个 swipe_duration 字段，感觉没必要（一共也没几个 swipe 的任务）

> 可以加，逻辑上没问题，但是相当于所有 TaskInfo 都要多一个 swipe_duration 字段，感觉没必要（一共也没几个 swipe 的任务）

就是这个意思，有点浪费内存（虽然似乎也浪费不了多少？

2022-05-03 14:48 UTC, MistEO commented on resource/tasks.json
> +            "SwipeLeftToStage1-7"
> 

或许可以把 std::variant 用起来，~~等到 5.0 一定改~~

2022-05-03 14:49 UTC, zzyyyl commented on resource/tasks.json
> +            "SwipeLeftToStage1-7"
> > * 可以加，逻辑上没问题，但是相当于所有 TaskInfo 都要多一个 swipe_duration 字段，感觉没必要（一共也没几个 swipe 的任务）
> 
> > 可以加，逻辑上没问题，但是相当于所有 TaskInfo 都要多一个 swipe_duration 字段，感觉没必要（一共也没几个 swipe 的任务）
> 
> 就是这个意思，有点浪费内存（虽然似乎也浪费不了多少？

不如沿用之前的操作，把`pre_delay`当作滑动时间，`rear_delay`当作额外延时（

2022-05-03 14:50 UTC, MistEO commented on resource/tasks.json
> +            "SwipeLeftToStage1-7"
> > > * 可以加，逻辑上没问题，但是相当于所有 TaskInfo 都要多一个 swipe_duration 字段，感觉没必要（一共也没几个 swipe 的任务）
> > 
> > 
> > > 可以加，逻辑上没问题，但是相当于所有 TaskInfo 都要多一个 swipe_duration 字段，感觉没必要（一共也没几个 swipe 的任务）
> > 
> > 
> > 就是这个意思，有点浪费内存（虽然似乎也浪费不了多少？
> 
> 不如沿用之前的操作，把`pre_delay`当作滑动时间，`rear_delay`当作额外延时（

那假如这个 swipe 的任务就是需要 `pre_delay` 的。。

2022-05-03 15:08 UTC, merged