优化肉鸽招募逻辑
MaaAssistantArknights/MaaAssistantArknights pull request #5621
Opened 2023-07-24 03:38 UTC by SherkeyXD

+ 不知道为什么波登可被标记为关键干员，导致出现 #5379 #4675 提到的问题
+ MAA 现在还不会用罗比菈塔的召唤物，于是先 ban 了
+ 根据 #5607 的建议，焰苇打法优先抓泡普卡

2023-07-25 11:47 UTC, lhhxxxxx requested changes

2023-07-25 11:47 UTC, lhhxxxxx commented on resource/roguelike/recruitment.json
> -                    "is_key": true,
罗比菈塔可以直接不选，这个也是小刻肉鸽理解的遗留物，当时初始券是随机的，因此没有地面位时会在辅助券里抓罗比菈塔

2023-07-25 11:52 UTC, lhhxxxxx commented
在github留档一下问题原因的分析。

经过讨论和回忆，波登可等有医疗功能的辅助被设置is_key=true的原因是当年小刻肉鸽初始券是随机的，因此前期没有医疗容易寄，因此会在辅助券中抓取波登可等干员提高通关率，在我们编写傀影肉鸽优先级文件时沿用了这一点。

以后有类似问题可引用此条评论。

2023-07-25 17:44 UTC, SherkeyXD commented
应该可了
合的时候记得squash ~~我懒得本地rebase了（不是~~

2023-07-25 17:56 UTC, lhhxxxxx approved these changes

2023-07-25 17:58 UTC, merged

2023-08-18 13:33 UTC, Clazex commented
#5143 也可以 close 掉了