docs: 繁中文件大更新
MaaAssistantArknights/MaaAssistantArknights pull request #6226
Opened 2023-09-05 05:54 UTC by momomochi987

因為不知道繁中文件到底缺少了哪些內容，我就~~直接簡單粗暴的~~把目前簡中的內容轉成繁體，再一個一個微調。

所以目前簡中有的內容，繁中也有了 ｡:.ﾟヽ(*´∀`)ﾉﾟ.:｡

除了文件內容以外，也一起修改了 .vuepress 裡的 search.ts, sidebar 跟 navbar 的繁中內容。

再麻煩各位大佬看看有沒有地方還需要調整了 🙏🙏🙏

2023-09-05 08:37 UTC, ABA2396 approved these changes
内容应该没啥问题。

文件名现在可以直接改吗？我不确定现在是怎么个同步情况了，来个人瞅瞅）

2023-09-05 08:37 UTC, ABA2396 commented on docs/zh-tw/3.1-集成文件.md
> +另支援少部分資源關卡名請參考[集成範例](..\tools\AutoLocalization\example\zh-cn.xaml#L260)
这个链接位置对吗？前面的..\应该不能删吧，试试看能不能跑

2023-09-05 08:55 UTC, momomochi987 commented on docs/zh-tw/3.1-集成文件.md
> +另支援少部分資源關卡名請參考[集成範例](..\tools\AutoLocalization\example\zh-cn.xaml#L260)
> 这个链接位置对吗？前面的..\应该不能删吧，试试看能不能跑

對欸 漏掉了 QQ
謝佬提醒

但我去看現行簡中的[這個部分](https://maa.plus/docs/3.1-%E9%9B%86%E6%88%90%E6%96%87%E6%A1%A3.html) 
會出現這個
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/45387477/f190a530-7035-4455-871d-667a427038ee)

2023-09-05 09:23 UTC, SherkeyXD commented
> 文件名现在可以直接改吗？我不确定现在是怎么个同步情况了，来个人瞅瞅）

改文件名的话需要更改侧边栏对应的配置，我这几天看看写个文档指引一下吧

2023-09-06 02:00 UTC, ABA2396 commented on docs/zh-tw/3.1-集成文件.md
> +另支援少部分資源關卡名請參考[集成範例](..\tools\AutoLocalization\example\zh-cn.xaml#L260)
之前不是直接写死的仓库链接吗）

2023-09-06 03:33 UTC, momomochi987 commented
啊啊，想到有兩個跟這個 PR 相關問題想問，再麻煩大佬們解惑 ~

1. 我想把 `resource/global/txwy/readme.md` 刪了，看起來是之前功能還沒齊全時的說明。
現在功能比較齊全 (?) 了，感覺就沒有存在的必要了?
@MistEO 佬覺得如何? 因為看紀錄是您新增的，想說先問一下 🙈

2. `docs/maa_tasks_schema.json` 
這個我看除了簡中的之外，還有一個英文版的。
有需要也補一個繁中的嗎 🤔

2023-09-06 15:58 UTC, SherkeyXD commented
> 2. 我不知道这个是干嘛的（

2 那个是 json schema（见[3.4-任务流程协议.md](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/be83faf31ee9230020220d585a653b25aee65a1b/docs/3.4-任务流程协议.md?plain=1#L251C2-L251C2)）可以用于vscode的补全提示什么的
不过这东西为什么要放在文档里啊（

2023-09-06 16:11 UTC, momomochi987 commented on docs/zh-tw/3.1-集成文件.md
> +另支援少部分資源關卡名請參考[集成範例](..\tools\AutoLocalization\example\zh-cn.xaml#L260)
總之我先把繁中的這個連結改成 Github 上 MAA 主倉庫的連結了

放的是這個連結 ↓
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/be83faf31ee9230020220d585a653b25aee65a1b/tools/AutoLocalization/example/zh-cn.xaml#L260

2023-09-06 16:14 UTC, momomochi987 commented
> 提交冲突了，改一下我们可以先把这个 PR 合进去

衝突應該解決了 (?
還有問題的下次再說~  o(〃'▽'〃)o

~~先把這個 PR 合起來，不然感覺好卡~~

2023-09-06 16:22 UTC, momomochi987 commented
~~雖然但是~~
看了一下其他 PR 發現好像我會卡到別人的 PR 
也是可以先合其他的 PR 
然後我再慢慢解衝突 (?)

看大佬們覺得哪種比較方便
我都可以 🙈🙈🙈

2023-09-06 17:10 UTC, SherkeyXD requested changes

2023-09-06 17:10 UTC, SherkeyXD commented on docs/zh-tw/3.1-集成文件.md
> +另支援少部分資源關卡名請參考[集成範例](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/be83faf31ee9230020220d585a653b25aee65a1b/tools/AutoLocalization/example/zh-cn.xaml#L260)
这边不要把当前的 commit hash 写死

2023-09-07 01:09 UTC, momomochi987 commented on docs/zh-tw/3.1-集成文件.md
> +另支援少部分資源關卡名請參考[集成範例](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/be83faf31ee9230020220d585a653b25aee65a1b/tools/AutoLocalization/example/zh-cn.xaml#L260)
> 这边不要把当前的 commit hash 写死

那我把連結結尾的 `#L260` 拿掉?
只留下 `https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/be83faf31ee9230020220d585a653b25aee65a1b/tools/AutoLocalization/example/zh-cn.xaml` ?

還是有其他更好的解法 (´;ω;`)?

2023-09-07 01:15 UTC, momomochi987 commented on docs/zh-tw/3.1-集成文件.md
> +另支援少部分資源關卡名請參考[集成範例](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/be83faf31ee9230020220d585a653b25aee65a1b/tools/AutoLocalization/example/zh-cn.xaml#L260)
啊啊 沒事
早上醒來腦子還沒醒

想到可以改成這個 `https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/tools/AutoLocalization/example/zh-cn.xaml#L260`

改成這個應該就可以了 (?

2023-09-07 02:05 UTC, MistEO approved these changes

2023-09-07 02:05 UTC, momomochi987 commented on docs/zh-tw/3.1-集成文件.md
> +另支援少部分資源關卡名請參考[集成範例](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/be83faf31ee9230020220d585a653b25aee65a1b/tools/AutoLocalization/example/zh-cn.xaml#L260)
我有先把
`https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/be83faf31ee9230020220d585a653b25aee65a1b/tools/AutoLocalization/example/zh-cn.xaml#L260`
改成了
`https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/dev/tools/AutoLocalization/example/zh-cn.xaml#L260`

這樣應該就不會有 commit hash 的問題 (?

如果還有需要再調整的，再麻煩大佬們了 (´;ω;`)

2023-09-07 02:36 UTC, SherkeyXD approved these changes

2023-09-07 09:14 UTC, merged

2023-09-07 09:42 UTC, SherkeyXD commented
![Thx-ld](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/18511905/68092871-ea78-4f59-b329-eccc1c33e860)