水月肉鸽：增加支援道具，新干员分组，优化大君遗脉策略
MaaAssistantArknights/MaaAssistantArknights pull request #6372
Opened 2023-09-15 05:50 UTC by Yumi0606

支援道具还添加到了萨米的文件里

2023-09-15 05:51 UTC, Yumi0606 commented
修复 #6128

2023-09-15 09:53 UTC, Lancarus commented on resource/roguelike/Sami/recruitment.json
冲突了

2023-09-15 09:55 UTC, Lancarus commented on resource/roguelike/Mizuki/autopilot/大君遗脉.json
额，用原来的formatter格式化一下？

2023-09-15 09:58 UTC, Lancarus commented on resource/roguelike/Mizuki/recruitment.json
> +            "doc": "部署位地面,无朝向的召唤物",
地雷和夹子之类的建议不要写，让他默认在其他地面里面最后自动部署

2023-09-15 11:26 UTC, MistEO reviewed
请用 4 缩进格式化一下

2023-09-15 18:25 UTC, Lancarus approved these changes

2023-09-16 04:12 UTC, Yumi0606 commented
不明白smoke test为什么不能过啊,不该啊

2023-09-16 04:52 UTC, Yumi0606 commented
> 不明白smoke test为什么不能过啊,不该啊

主要自己的仓库里测试都能过

2023-09-16 04:53 UTC, Lancarus commented
> > 不明白smoke test为什么不能过啊,不该啊
> 
> 主要自己的仓库里测试都能过

等修复

2023-09-16 18:14 UTC, MistEO requested changes
你的提交有问题，把老的代码还原回去了。

点 Files changed 可以看到你改了哪些内容，有些应该不是你想改的（

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/18511905/a28cd8e4-41b6-461d-a7d5-bf70148278cf)

2023-09-16 18:45 UTC, MistEO commented
如果你对 github 不熟悉，我建议直接重新开一个分支，把要修改的重新提交一下

2023-09-16 23:13 UTC, Yumi0606 commented
已经reset了,现在只改3个文件

2023-09-17 04:06 UTC, MistEO approved these changes
@Lancarus e佬再来瞅瞅_(:з」∠)_

2023-09-17 06:59 UTC, Lancarus approved these changes

2023-09-17 07:38 UTC, merged