chore: 在Python脚本中添加活动关导航下载与加载的示例 (#3916)
MaaAssistantArknights/MaaAssistantArknights pull request #6451
Opened 2023-09-20 03:46 UTC by ZhaoZuohong

使用 Python 的标准库 `urllib`

2023-09-20 04:33 UTC, MistEO commented on src/Python/sample.py
>      # incremental_path=path / 'resource' / 'global' / 'YoStarEN'
上面这行被隔开了，有点割裂，不知道这个  incremental 是干嘛的了

2023-09-21 23:27 UTC, SherkeyXD approved these changes

2023-09-22 08:30 UTC, MistEO requested changes
请处理一下上面 incremental_path 的问题

2023-09-22 12:50 UTC, merged

2023-09-22 12:50 UTC, MistEO commented
![Thx-ld](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/18511905/4c8ec91a-1280-403e-8cb5-6a580146b795)