feat: 自动使用助战
MaaAssistantArknights/MaaAssistantArknights pull request #6458
Opened 2023-09-20 12:18 UTC by Gliese129

修改后如果两轮内没有识别到某干员，则自动判定该干员不在box内

2023-09-20 17:49 UTC, Lancarus commented
参考一下 RoguelikeRecruitTaskPlugin::recruit_support_char？

2023-09-20 18:05 UTC, Constrat commented on resource/template/BattleSupportFormationOCR.png
I'm having a hard time understanding what's this supposed to do.
If it's OcrDetect why is there an image uploaded? For context?

2023-09-20 18:16 UTC, Lancarus commented on resource/template/BattleSupportFormationOCR.png
don't worry about that, he should upload a wrong picture. give he time to fix it.

2023-09-20 18:17 UTC, Lancarus commented on resource/template/BattleSupportFormationOCR.png
don't worry about that, he should upload a wrong picture. give he time to fix it.

2023-09-20 18:18 UTC, Constrat commented on resource/template/BattleSupportFormationOCR.png
I was already panicking for the adaptation 😅

2023-09-20 23:59 UTC, Gliese129 commented on resource/template/BattleSupportFormationOCR.png
> I'm having a hard time understanding what's this supposed to do.
> 
> If it's OcrDetect why is there an image uploaded? For context?

I forgot to delete it... sorry for the confusion😂

2023-09-26 01:26 UTC, Gliese129 commented
> recruit_support_char

没找到能复用的资源，不过有些可以用ocr替换
然后就是rougelike里面指定了max refresh time，这个需要加在自动助战里面吗，比如刷新10次就告诉用户没刷到对应的助战（

2023-09-28 02:17 UTC, status102 commented
不能判断技能的话，选完助战是直接停止让玩家检查还是？

2023-10-01 02:40 UTC, Gliese129 commented
> 不能判断技能的话，选完助战是直接停止让玩家检查还是？

目前是直接进入战斗，之后可能会考虑把自动编队单独分出来，而不是绑定在自动战斗里面

2023-10-01 02:41 UTC, Gliese129 commented
> 不能判断技能的话，选完助战是直接停止让玩家检查还是？

判断技能的话有些吃力不讨好，战斗助战的技能同质化严重，基本就决战技挂机技能

2023-10-01 02:44 UTC, status102 commented
> 判断技能的话有些吃力不讨好，战斗助战的技能同质化严重，基本就决战技挂机技能

如果不能判断技能以及对应的技能等级，希望能在显著位置进行表明。
例：
提丰23？
苇草23？
号角123？
如果我需要塞雷娅1？

2023-10-01 02:45 UTC, status102 commented
如果不能判断，给自动编队加一个选不到干员就中止，然后弹一个Toast让用户手动处理可能更好

2023-10-03 15:09 UTC, status102 commented on src/MaaCore/Task/Miscellaneous/BattleFormationTask.cpp
> +    if (cnt + !m_use_support > 1) {
ul + bool？

2023-10-05 03:32 UTC, Gliese129 commented
> 如果不能判断技能及技能等级，给自动编队加一个选不到干员就中止，然后弹一个Toast让用户手动处理会不会更好

ul+bool主要是方便，bool不就是0和1吗（），这样use support是false的时候相当于多了一名助战，这样直接判断助战数量就行了）

2023-10-05 03:38 UTC, status102 commented on src/MaaCore/Task/Miscellaneous/BattleFormationTask.cpp
> +    if (cnt + !m_use_support > 1) {
> ul+bool主要是方便，bool不就是0和1吗（），这样use support是false的时候相当于多了一名助战，这样直接判断助战数量就行了）

看别人了，我觉得不好。

2023-10-05 09:32 UTC, zzyyyl commented on src/MaaCore/Task/Miscellaneous/BattleFormationTask.cpp
> +    if (cnt + !m_use_support > 1) {
`? 0u : 1u`

2023-11-26 03:38 UTC, status102 commented
- link to #6023

2023-12-19 02:45 UTC, CGYR commented
请问这个feat还上吗？自动战斗能借助战会方便很多，尤其是活动关卡借好友角色抄作业刷材料

2023-12-19 05:00 UTC, Gliese129 commented
> 请问这个feat还上吗？自动战斗能借助战会方便很多，尤其是活动关卡借好友角色抄作业刷材料

有个大问题是技能匹配，maa的OCR识别率不是100%导致技能自动判断有些困难

2023-12-19 05:04 UTC, Gliese129 commented
> 请问这个feat还上吗？自动战斗能借助战会方便很多，尤其是活动关卡借好友角色抄作业刷材料

@status102 目前打算是求技能名和OCR结果的最长公共子序列长度，如果大于原字符串长度的一半就判定一致，这样误判率应该会低一些？

2023-12-19 11:11 UTC, status102 commented
> @status102 目前打算是求技能名和OCR结果的最长公共子序列长度，如果大于原字符串长度的一半就判定一致，这样误判率应该会低一些？

不知道OCR的话外服适配起来会有多大的问题，我倾向于用fw的特征匹配

2023-12-19 14:37 UTC, status102 requested changes
有些文件似乎不应该出现在这里，比如危机合约地图

2023-12-24 08:00 UTC, Gliese129 commented
> 有些文件和改动似乎不应该出现在这里，比如危机合约地图、stages.json等等，代码部分还没怎么看

这个应该是git pull和merge的时候发生的变动？我倒是没修改过里面的内容

2024-02-05 03:10 UTC, wxhwen commented
> > > 请问这个feat还上吗？自动战斗能借助战会方便很多，尤其是活动关卡借好友角色抄作业刷材料
> > 
> > 
> > @status102 目前打算是求技能名和OCR结果的最长公共子序列长度，如果大于原字符串长度的一半就判定一致，这样误判率应该会低一些？
> 
> 我不太懂，想提点建议顺便问问，技能识别容易出问题的话，多加点识别项会不会更好，就是技能图标、技能名、回复方式、触发方式、技能描述这些，全都识别一遍，然后看匹配程度
> 
> 我给新号开荒找到这里来了，得借个干员刷1-7，但是自动战斗好像目前借不了

我也想找能够自动借助干员的操作，目前还没有找到。小号需要借助干员刷活动的时候，这个功能最能释放双手。

2024-02-07 15:24 UTC, Gliese129 commented
> > > 请问这个feat还上吗？自动战斗能借助战会方便很多，尤其是活动关卡借好友角色抄作业刷材料
> > 
> > 
> > @status102 目前打算是求技能名和OCR结果的最长公共子序列长度，如果大于原字符串长度的一半就判定一致，这样误判率应该会低一些？
> 
> 我不太懂，想提点建议顺便问问，技能识别容易出问题的话，多加点识别项会不会更好，就是技能图标、技能名、回复方式、触发方式、技能描述这些，全都识别一遍，然后看匹配程度
> 
> 我给新号开荒找到这里来了，得借个干员刷1-7，但是自动战斗好像目前借不了

好问题，不过maa里面的resource里面没有这些。考完试后看看能不能加个图片匹配啥的

2024-05-25 02:50 UTC, closed without merging