重构 changelog_generator.py 部分内容
MaaAssistantArknights/MaaAssistantArknights pull request #6957
Opened 2023-10-16 11:05 UTC by quyansiyuanwang

重构了一些重复性内容

2023-10-16 12:29 UTC, wangl-cc requested changes

2023-10-16 12:29 UTC, wangl-cc commented on tools/ChangelogGenerator/changelog_generator.py
> +            def updateMessages(return_message):
应该在循环外面更新message。

2023-10-16 12:29 UTC, wangl-cc commented on tools/ChangelogGenerator/changelog_generator.py
> +                for keys, trans in CNtoEN_Factory.items():
按照 `CNtoEN_Factory.items()` 来循环，最后生成的 changlog 顺序是不对的。

2023-10-16 12:44 UTC, ABA2396 reviewed
不太清楚python的函数定义是怎么样的，但是我感觉就算嵌套函数的话也是放在for外面比较好，要么就干脆直接放在print_commits的外面

2023-10-16 12:44 UTC, ABA2396 commented on tools/ChangelogGenerator/changelog_generator.py
> +            }
```suggestion
            translation_map = {
                '修复': 'fix',
                '新增': 'feat',
                '改进': 'perf',
                '更新': 'perf',
                '优化': 'perf',
                '重构': 'perf',
                '其他': 'other'
            }
```
直接这样？简单映射就没必要用元组了吧，不过也无所谓，就是这样写的话下面能方便点

2023-10-16 12:44 UTC, ABA2396 commented on tools/ChangelogGenerator/changelog_generator.py
> +                oper = push[0] if push else 'other'
这些可以和上面的一起抽出来，比如来个 translate_operation 函数啥的，返回替换后的标签，如果上面改成简单的映射的话就只需要
```
for keys, trans in translation_map.items():
    if any(key in commit_message for key in keys):
        return trans
return 'other'
```
看的应该会更加简单点

2023-10-16 12:44 UTC, ABA2396 commented on tools/ChangelogGenerator/changelog_generator.py
> +                oper = push[0] if push else 'other'
既然要重构的话可以更彻底点，比如
```
for commit_hash, commit_info in commits.items():
    commit_message = extract_commit_message(commit_info, with_commitizen)
    oper = translate_operation(commit_message)
    sorted_commits[oper].update({commit_hash: commit_info})
```
然后再整个 `extract_commit_message` 把下面的 `if not with_commitizen:` 一并处理了
比如
```
def extract_commit_message(commit_info, with_commitizen):
    commit_message = commit_info["message"]
    if not with_commitizen:
        commitizens = r"(?:build|chore|ci|docs?|feat|fix|perf|refactor|rft|style|test)"
        commit_message = re.sub(rf"^(?:{commitizens}, *)*{commitizens} *(?:\([^\)]*\))*: *", "", commit_message)
    return commit_message
```
后面就只需要
```
    for oper, commit_data in sorted_commits.items():
        if commit_data:
            ret_message += f"\n### {oper}\n\n"
            for commit_hash, commit_info in commit_data.items():
                ret_message += indent + "- " + extract_commit_message(commit_info, with_commitizen)
```
就可以整个函数统一了

2023-10-16 16:45 UTC, quyansiyuanwang commented on tools/ChangelogGenerator/changelog_generator.py
> +            CNtoEN_Factory = {
已覆写

2023-10-16 16:45 UTC, quyansiyuanwang commented on tools/ChangelogGenerator/changelog_generator.py
> +                ('改进', '更新', '优化', '重构'): 'perf',
已覆写

2023-10-16 16:46 UTC, quyansiyuanwang commented on tools/ChangelogGenerator/changelog_generator.py
> +                push = [trans for keys, trans in CNtoEN_Factory.items() if any(key in commit_message for key in keys)]
已覆写

2023-10-16 16:47 UTC, quyansiyuanwang commented on tools/ChangelogGenerator/changelog_generator.py
> +            def updateMessages(return_message):
已重构

2023-10-16 16:47 UTC, quyansiyuanwang commented on tools/ChangelogGenerator/changelog_generator.py
> +                for keys, trans in CNtoEN_Factory.items():
已修复

2023-10-16 16:47 UTC, quyansiyuanwang commented on tools/ChangelogGenerator/changelog_generator.py
> +            }
已应用

2023-10-16 21:19 UTC, wangl-cc reviewed
其他没有什么大问题，主要是变量命名方面有点问题。函数应该snake_case而不是camelCase。另外我觉得`updateCommits`可以叫`classify_commit`或者`sort_commit`。`updateMessage`可以叫`gen_changelog`之类的，那个`individual_commits`名字也类似。

2023-10-16 21:19 UTC, wangl-cc commented on tools/ChangelogGenerator/changelog_generator.py
> +    sorted_commits[oper].update(update_dict)
这里没啥大问题，但是和原来的不完全等价，因为原来是先匹配一遍关键词，再匹配一遍英文的开头。对于`feat: 更新`这样的 commit，原来会分类成`pref`而这里会分类成`feat`，我不知道那个比较好。但是我觉得两个不要混在一起匹配比较好，这样改优先级也比较方便。

```suggestion
KEYWORD_TO_COMMIT_TYPE = {
    '修复': 'fix',
    '新增': 'feat',
    '改进': 'perf',
    '更新': 'perf',
    '优化': 'perf',
    '重构': 'perf',
    '其他': 'other'
}

COMMIT_TYPES = ['fix', 'feat', 'perf']

def updateCommits(commit_message, sorted_commits, update_dict):
    commit_type = 'other'
    for keyword, type_ in KEYWORD_TO_COMMIT_TYPE.items():
        if keyword in commit_message:
            commit_type = type_
            return
    for type_ in COMMIT_TYPES:
        if commit_message.startswith(type_):
            commit_type = type_
            return
    sorted_commits[commit_type].update(update_dict)
```

2023-10-16 23:45 UTC, quyansiyuanwang commented on tools/ChangelogGenerator/changelog_generator.py
> +    sorted_commits[oper].update(update_dict)
已修正

2023-10-16 23:45 UTC, quyansiyuanwang commented on tools/ChangelogGenerator/changelog_generator.py
> +def individual_commits(commits: dict):
已修改

2023-10-17 03:37 UTC, wangl-cc commented on tools/ChangelogGenerator/changelog_generator.py
> +    sorted_commits[oper].update(update_dict)
这里并不是开头优先，这里先匹配 key，再匹配 value。所以现在的匹配优先级是匹配`修复`关键词或者`fix`开头，再然后匹配`新增`关键词和开头，...。这样`feat: 修复`或者`pref: 新增`之类的(尽管我觉得大概不会出现这样的commit）会被分类为`fix`和`feat`。如果真的要开头优先，应该先匹配一遍开头，再匹配一遍关键词。不过现在这也能行，区别不会太大。

2023-10-17 04:16 UTC, quyansiyuanwang commented on tools/ChangelogGenerator/changelog_generator.py
> +    sorted_commits[oper].update(update_dict)
描述有问题是我的问题（
其实这样就能跑了，我觉得没啥问题，所以问题不大（

2023-10-17 07:03 UTC, wangl-cc approved these changes
功能上没啥问题了，就是我不确定格式和命名需不需要改改。

2023-10-17 11:45 UTC, zzyyyl commented on tools/ChangelogGenerator/changelog_generator.py
> +    }
这两个缩进是不是往前移点（

2023-10-17 11:49 UTC, quyansiyuanwang commented on tools/ChangelogGenerator/changelog_generator.py
> +    }
差不多，不用改
所以，改！

2023-10-17 13:43 UTC, merged