Dev-可选择使用系统通知推送MAA通知
MaaAssistantArknights/MaaAssistantArknights pull request #713
Opened 2022-06-03 03:56 UTC by cglcv

受#697中的讨论启发，尝试搓了个推送到系统通知的方案，由于提到win7不兼容的问题做了个复选框
![image](https://user-images.githubusercontent.com/35825310/171782563-07b91729-5ae4-4f5b-8af1-2951e95cdc8a.png)

![image](https://user-images.githubusercontent.com/35825310/171782837-d03c5933-0d90-406d-9f04-922da6a3c006.png)

第一次做这种代码，如有问题还请指正
参考微软文档：https://docs.microsoft.com/zh-cn/windows/apps/design/shell/tiles-and-notifications/send-local-toast?tabs=desktop
~话说aria2支持输出进度吗，要是支持的话也许可以来一个toast进度条？~

2022-06-03 04:04 UTC, zhongfly commented
可以增加一个判断吧？如果是win10以下的系统，这个选项变成不可用

2022-06-03 04:18 UTC, cglcv commented
> 可以增加一个判断吧？如果是win10以下的系统，这个选项变成不可用

我觉得可以有
~但我不会写orz~

2022-06-03 04:33 UTC, MistEO commented
@usaginya 大佬康康（

2022-06-03 04:34 UTC, MistEO commented
另外系统通知就只能右下角了吧，或许可以勾选之后就把上下左右那些 checkbox disable 掉？

2022-06-03 04:45 UTC, LengmoAngel commented
> > 可以增加一个判断吧？如果是win10以下的系统，这个选项变成不可用
> 
> 我觉得可以有 ~但我不会写orz~

判断下NT内核版本 你可以参考https://docs.microsoft.com/zh-cn/windows/win32/api/winnt/ns-winnt-osversioninfoa?redirectedfrom=MSDN这个来写

2022-06-03 04:47 UTC, MistEO commented
> 话说aria2支持输出进度吗，要是支持的话也许可以来一个toast进度条？

aria2 可以重定向然后解析下字符串，这部分应该不是特别麻烦，~~但是 UI 我不会写~~

2022-06-03 05:02 UTC, MistEO commented
link to https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/117 https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/122 https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/356

2022-06-03 05:41 UTC, usaginya commented
> @usaginya @LiamSho 大佬们康康（

> > 可以增加一个判断吧？如果是win10以下的系统，这个选项变成不可用
> 
> 我觉得可以有 ~但我不会写orz~

看起来也可以啦、虽然还能再优化下格式、用系统通知的时候就把位置设置禁用就行了
不过这是用之前的 UWP系统通知、在老系统也用不了、所以最好再加个对不支持的系统的判断、把选项禁用更好
这边刚换 win10 不久 vs 还没装上你们可以先改改 \_(:3 」∠)\_

2022-06-03 05:44 UTC, usaginya commented
> > 话说aria2支持输出进度吗，要是支持的话也许可以来一个toast进度条？
> 
> aria2 可以重定向然后解析下字符串，这部分应该不是特别麻烦，~但是 UI 我不会写~

如果可以提供个 aira2 下载信息进度的接口给 UI 用、再说明下接口用法、剩下的交给会写 UI 的我们就好啦 \_(:3 」∠)\_

2022-06-03 06:12 UTC, MistEO requested changes

2022-06-03 06:12 UTC, MistEO commented on src/MeoAssistant/MeoAssistant.vcxproj
> +    <PlatformToolset>v143</PlatformToolset>
怎么顺道把 MSVC 升级了 orz
VS 2022 在 debug opencv  `cv::Mat` 的时候有很大概率崩溃，微软也一直没修。所以不能升_(:з」∠)_

2022-06-03 06:12 UTC, MistEO commented on src/MeoAsstGui/Helper/AsstProxy.cs
> +                    if (CheckToastSystem()) new ToastContentBuilder().AddText("任务已全部完成！").Show();
话说这里每个地方都 check 一下，直接写在封装里会不会好一点

2022-06-03 06:15 UTC, cglcv commented on src/MeoAsstGui/Helper/AsstProxy.cs
> +                    if (CheckToastSystem()) new ToastContentBuilder().AddText("任务已全部完成！").Show();
> 话说这里每个地方都 check 一下，直接写在封装里会不会好一点

确实……我再想想这块怎么搞……代码还没完全熟悉

2022-06-03 06:16 UTC, usaginya commented on src/MeoAsstGui/Helper/AsstProxy.cs
> +                    if (CheckToastSystem()) new ToastContentBuilder().AddText("任务已全部完成！").Show();
刚刚也再想把通知封装起来 (草

2022-06-03 06:16 UTC, cglcv commented on src/MeoAssistant/MeoAssistant.vcxproj
> +    <PlatformToolset>v143</PlatformToolset>
因为没装2019的vc++所以顺手就升级了……我改一下

2022-06-03 06:17 UTC, LiamSho requested changes

2022-06-03 06:17 UTC, LiamSho commented on src/MeoAsstGui/Helper/AsstProxy.cs
> +        }
这个文件是 MaaCore 的 Native API，通知相关的代码不应该粘在这里，应该全部塞进 `ToastNotification`，要改也应该是去改 `ToastNotification` 的实现，而且也是可以做到不更改发送通知的 API 的

2022-06-03 06:57 UTC, LiamSho commented
> 

都用 C# 了哪有那么麻烦（

获取系统版本

``` csharp
var sys = RuntimeInformation.OSDescription; // 得到的是字符串，例如：Microsoft Windows 10.0.22000
```

获取 NT 内核版本

``` csharp
var os = Environment.OSVersion.Version; // 得到的是 Version 对象，例如：6.2.9200.0
```

2022-06-03 11:24 UTC, LiamSho requested changes

2022-06-03 11:24 UTC, LiamSho commented on tools/ItemMappingCvt/ItemMappingCvt.vcxproj
> +    <PlatformToolset>v143</PlatformToolset>
怎么又变成 143 了？？？

2022-06-03 11:24 UTC, LiamSho commented on src/MeoAsstGui/ViewModels/VersionUpdateViewModel.cs
> +                        .ShowUpdateVersion();
这个格式是为什么？

2022-06-03 11:24 UTC, LiamSho commented on src/MeoAsstGui/ViewModels/VersionUpdateViewModel.cs
> +            //开发版不检查更新
还有这个格式变更？

2022-06-03 11:30 UTC, cglcv commented on src/MeoAsstGui/ViewModels/VersionUpdateViewModel.cs
> +            //开发版不检查更新
可能是测更新弹窗时反复注释不检查更新代码时导致的

2022-06-03 11:48 UTC, cglcv commented on tools/ItemMappingCvt/ItemMappingCvt.vcxproj
> +    <PlatformToolset>v143</PlatformToolset>
已处理，稍后推上来

2022-06-03 11:48 UTC, cglcv commented on src/MeoAsstGui/Helper/AsstProxy.cs
> +        //}
已处理，稍后推上来

2022-06-03 11:49 UTC, cglcv commented on src/MeoAsstGui/ViewModels/VersionUpdateViewModel.cs
> +                        .ShowUpdateVersion();
误处理，恢复了，稍后推

2022-06-03 21:18 UTC, LiamSho requested changes
review request 前麻烦自己先检查一下（

2022-06-03 21:18 UTC, LiamSho commented on src/MeoAssistant/MeoAssistant.vcxproj
> +    <PlatformToolset>v143</PlatformToolset>
？

2022-06-03 21:18 UTC, LiamSho commented on tools/TestCaller/TestCaller.vcxproj
> +    <PlatformToolset>v143</PlatformToolset>
？

2022-06-03 21:18 UTC, LiamSho commented on src/MeoAsstGui/ViewModels/SettingsViewModel.cs
> +            if (os.ToString().CompareTo("10.0.0.10240") > 0)
你有试过 `Environment.OSVersion.Version` 会返回什么吗（

https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/713#issuecomment-1145649757

2022-06-03 21:35 UTC, LiamSho requested changes

2022-06-03 21:35 UTC, LiamSho commented on src/MeoAsstGui/ViewModels/SettingsViewModel.cs
> +            if (os.ToString().CompareTo("10.0.0.10240") > 0)
使用这种方式获取系统版本信息在 .NET Framework 中是[存在问题](https://docs.microsoft.com/en-us/dotnet/api/system.environment.osversion?view=net-6.0#remarks)的（.NET 5 以上不存在）

可以改为 `RuntimeInformation.OSDescription.ToString()`

获取到的值为 `Microsoft Windows 10.0.22000`

2022-06-03 23:17 UTC, cglcv commented on src/MeoAssistant/MeoAssistant.vcxproj
> +    <PlatformToolset>v143</PlatformToolset>
我在VS里面降级过了
![image](https://user-images.githubusercontent.com/35825310/171965692-8bff65f0-29ed-4e24-bfd0-2b5ce7020d53.png)
没提交上去？
~那为什么升级更改会提交……~

这东西可以在网页端直接改数字吗？或者管理员有可能单独处理这一个文件吗，十分抱歉

2022-06-04 00:42 UTC, cglcv commented on src/MeoAssistant/MeoAssistant.vcxproj
> +    <PlatformToolset>v143</PlatformToolset>
草，版本太多光处理release x64的了，已处理

2022-06-04 00:55 UTC, cglcv commented
可能有一个bug：
系统推送通知的对勾点选上的情况下启动maa第一次去掉对勾时下面的通知位置不会恢复可用，再勾上再去掉即可恢复
反过来没有问题

目前不知道怎么解决orz

如图：
![image](https://user-images.githubusercontent.com/35825310/171970225-c765048d-317b-4ab8-ba1a-8e482d056dec.png)
再勾选一次再去掉的正常情况：
![image](https://user-images.githubusercontent.com/35825310/171970259-1f72f4c3-a714-48fe-990d-66158beb469b.png)

2022-06-04 04:45 UTC, MistEO commented on README.md
> +Visual Studio 2022请务必安装VS2019的VC++生成工具，VS 2022 在 debug opencv cv::Mat 的时候有很大概率崩溃，微软也一直没修。所以暂时无法使用
这个其实不用加的，vs 22 用是正常能用的，只是调试图像算法的时候会出问题，不影响 release 包。

即不是生成工具的问题，而是 debugger 的问题。

而且这项目的 pr 好像从来没人改过图像相关算法 ~~果然太小众领域了么~~，所以自己不推上来的话，22 也没什么事

2022-06-04 04:45 UTC, MistEO commented on src/MeoAsstGui/ViewModels/VersionUpdateViewModel.cs
> +        private string _updateUrl = ViewStatusStorage.Get("VersionUpdate.url", string.Empty);
这个是干啥的（

2022-06-04 04:52 UTC, cglcv commented on src/MeoAsstGui/ViewModels/VersionUpdateViewModel.cs
> +        private string _updateUrl = ViewStatusStorage.Get("VersionUpdate.url", string.Empty);
存URI，用于推送通知时的按钮支持

2022-06-04 05:21 UTC, MistEO commented on src/MeoAsstGui/ViewModels/VersionUpdateViewModel.cs
> +        private string _updateUrl = ViewStatusStorage.Get("VersionUpdate.url", string.Empty);
没看别的地方用啊（~~我是不是星际了~~

2022-06-04 05:38 UTC, cglcv commented on src/MeoAsstGui/ViewModels/VersionUpdateViewModel.cs
> +        private string _updateUrl = ViewStatusStorage.Get("VersionUpdate.url", string.Empty);
> 没看别的地方用啊（~我是不是星际了~

改了下下面的UpdateUrl类，发现删了好像也可以?

2022-06-04 05:47 UTC, cglcv commented on src/MeoAsstGui/ViewModels/VersionUpdateViewModel.cs
> +        private string _updateUrl = ViewStatusStorage.Get("VersionUpdate.url", string.Empty);
删了，在传了（

2022-06-04 05:48 UTC, MistEO commented on src/MeoAsstGui/ViewModels/VersionUpdateViewModel.cs
> +        private string _updateUrl = ViewStatusStorage.Get("VersionUpdate.url", string.Empty);
不，我的意思是整个 `UpdateUrl` 似乎都没用上_(:з」∠)_

2022-06-04 06:04 UTC, cglcv commented on src/MeoAsstGui/ViewModels/VersionUpdateViewModel.cs
> +        private string _updateUrl = ViewStatusStorage.Get("VersionUpdate.url", string.Empty);
> 不，我的意思是整个 `UpdateUrl` 似乎都没用上_(:з」∠)_
> 
> getter / setter 给变量封装一层的方式是没问题的

246行`UpdateUrl = _lastestJson["html_url"].ToString();`
运用该类把url写到gui.json中，然后由按钮初始化的时候的读取gui,json
`protected string _buttonSystemUrl = ViewStatusStorage.Get("VersionUpdate.url", string.Empty);`

2022-06-04 06:07 UTC, MistEO commented on src/MeoAsstGui/ViewModels/VersionUpdateViewModel.cs
> +        private string _updateUrl = ViewStatusStorage.Get("VersionUpdate.url", string.Empty);
> > 不，我的意思是整个 `UpdateUrl` 似乎都没用上_(:з」∠)_
> > getter / setter 给变量封装一层的方式是没问题的
> 
> 246行`UpdateUrl = _lastestJson["html_url"].ToString();` 运用该类把url写到gui.json中，然后由按钮初始化的时候的读取gui,json `protected string _buttonSystemUrl = ViewStatusStorage.Get("VersionUpdate.url", string.Empty);`

那按钮直接使用 `UpdateUrl` 就好了呀，或者直接把这个 json 字段存到 `_buttonSystemUrl`。现在这样有点摸不着头脑，容易让人觉得这个 `UpdateUrl` 没有任何地方引用

2022-06-04 07:58 UTC, cglcv commented on src/MeoAsstGui/ViewModels/VersionUpdateViewModel.cs
> +        private string _updateUrl = ViewStatusStorage.Get("VersionUpdate.url", string.Empty);
> > > 不，我的意思是整个 `UpdateUrl` 似乎都没用上_(:з」∠)_
> > > getter / setter 给变量封装一层的方式是没问题的
> > 
> > 
> > 246行`UpdateUrl = _lastestJson["html_url"].ToString();` 运用该类把url写到gui.json中，然后由按钮初始化的时候的读取gui,json `protected string _buttonSystemUrl = ViewStatusStorage.Get("VersionUpdate.url", string.Empty);`
> 
> 那按钮直接使用 `UpdateUrl` 就好了呀，或者直接把这个 json 字段存到 `_buttonSystemUrl`。现在这样有点摸不着头脑，容易让人觉得这个 `UpdateUrl` 没有任何地方引用

确实，好久没写都忘了类怎么用了……
已处理

2022-06-04 13:51 UTC, LiamSho approved these changes

2022-06-04 13:52 UTC, MistEO commented
Thanks for your contribution!

2022-06-04 13:52 UTC, merged

2022-06-04 19:11 UTC, sakuraxp commented
> > 可以增加一个判断吧？如果是win10以下的系统，这个选项变成不可用
> 
> 我觉得可以有 ~但我不会写orz~

我改了一版，当操作系统不支持时，隐藏相应的选项，代码有简化，前面说得可能有点选的bug好像消失了。
![image](https://user-images.githubusercontent.com/39004442/172022197-3918d39d-6c14-4841-82f0-5676a192f0b2.png)
![image](https://user-images.githubusercontent.com/39004442/172022209-2cf54cdd-a1e9-47ee-a248-23c48c61fcf8.png)