更新 Readme.md 加入fastgit镜像渠道
MaaAssistantArknights/MaaAssistantArknights pull request #729
Opened 2022-06-03 19:16 UTC by LengmoAngel

更新 Readme.md 加入fastgit镜像渠道

2022-06-03 19:49 UTC, MistEO requested changes

2022-06-03 19:49 UTC, MistEO commented on README.md
> +- 本软件不对fastgit镜像分发渠道可用性做出保障。
我感觉这个没必要加（？）

2022-06-03 19:49 UTC, MistEO commented on README.md
> +[fastgit镜像稳定版](https://hub.fastgit.xyz/MaaAssistantArknights/MaaAssistantArknights/releases/latest)
README 规范，字母和汉字之间要有空格

2022-06-05 07:23 UTC, qianxu2001 commented
建议叫正式版，因为正式版可以不稳定（，像微软一直都没叫稳定版，小米前段时间也改成正式版了

2022-06-05 07:49 UTC, LengmoAngel commented
> 建议叫正式版，因为正式版可以不稳定（，像微软一直都没叫稳定版，小米前段时间也改成正式版了

雷军！金凡！  
其实稳定版只是相对测试版乃至nightly版本来说的，举个其他例子，比如kernel核心的开发主线是mainline，而稳定版是stable，但稳定版不是最稳定的，真正最稳定版是Longterm(LTS) Ref:https://kernel.org/
其实只要让客户知道如果第一次使用优先下哪个就行，希望尝试新功能用哪个就行。因为舟一直在更新，肯定MAA也是随着滚动更新的。

2022-06-05 10:58 UTC, MistEO approved these changes

2022-06-05 11:00 UTC, merged