ci: 对pr的commits进行检查，禁止Merge xxx的commit合并
MaaAssistantArknights/MaaAssistantArknights pull request #7414
Opened 2023-11-27 12:41 UTC by status102

帮帮看看
报warning不会修
(node:1751) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

2023-11-29 09:18 UTC, SherkeyXD commented
<img width="414" alt="4963d8740f4529ebb4c0feb9d65a43fe" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/57581480/abf415a7-e412-436b-a035-48bb28f3dfc2">
不是我们的锅.jpg

2023-11-29 09:21 UTC, SherkeyXD requested changes

2023-11-29 09:21 UTC, SherkeyXD commented on .github/workflows/pr-checker.yml
> +        uses: actions/github-script@v4
```diff
-uses: actions/github-script@v4
+uses: actions/github-script@v4
```

2023-11-29 09:25 UTC, SherkeyXD requested changes

2023-11-29 09:25 UTC, SherkeyXD commented on .github/workflows/pr-checker.yml
> +        uses: actions/github-script@v4
```suggestion
        uses: actions/github-script@v7
```
```diff
-uses: actions/github-script@v4
+uses: actions/github-script@v7
```
<img width="414" alt="4963d8740f4529ebb4c0feb9d65a43fe" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/57581480/abf415a7-e412-436b-a035-48bb28f3dfc2">

[github-script](https://github.com/actions/github-script) 最新版本是 v7，可能是 v4 的代码用到了 `Buffer()` 函数，更新下试试

2023-11-29 11:35 UTC, SherkeyXD approved these changes

2023-11-29 12:11 UTC, AnnAngela approved these changes
LGTM

2023-11-29 12:13 UTC, zzyyyl commented
要不把 commitizen 也加上）

2023-11-30 01:41 UTC, AnnAngela reviewed
康康

2023-11-30 01:41 UTC, AnnAngela commented on .github/workflows/pr-checker.yml
> +            const regex = /^(build|chore|ci|docs?|feat|fix|perf|refactor|rft|style|test)[\:\.\(\,]|[Rr]evert|[Rr]elease/;
`|[Rr]evert|[Rr]elease`

这一段没有被括号包裹，可能导致开头的`^`覆盖不到这两段导致这两段实际上可以在任何位置出现，对吧？

2023-11-30 01:47 UTC, status102 commented on .github/workflows/pr-checker.yml
> +            const regex = /^(build|chore|ci|docs?|feat|fix|perf|refactor|rft|style|test)[\:\.\(\,]|[Rr]evert|[Rr]elease/;
确实会漏

2023-11-30 01:53 UTC, AnnAngela approved these changes

2023-11-30 09:14 UTC, status102 commented on .github/workflows/pr-checker.yml
> +    types: [opened, synchronize]
```suggestion
    types: [opened, ready_for_review, reopened, synchronize]
```
增加reopen和ready for review触发以处理较早的pr

2023-11-30 09:51 UTC, merged