[WIP] [New Feature] 自动启动方舟
MaaAssistantArknights/MaaAssistantArknights pull request #743
Opened 2022-06-04 14:11 UTC by lhhxxxxx

2022-06-04 17:36 UTC, MistEO requested changes

2022-06-04 17:36 UTC, MistEO commented on src/MeoAssistant/StartGameTask.h
> +        ServerType m_server_type = ServerType::Official;
考虑默认参数做成不自动启动，或通过外部 disable 该任务。接口默认参数同理，WPF 界面也可以增加一项不自动启动

2022-06-04 17:36 UTC, MistEO commented on src/MeoAssistant/GeneralConfiger.cpp
> +        m_intent_name[asst::ServerType::Official] = intent_json.at("Official").as_string();
直接遍历 `intent` 下的所有项，map key 用 string 好点，方便高级用户自己 diy

2022-06-04 17:36 UTC, MistEO commented on src/MeoAssistant/StartUpTask.cpp
> +    if (params.contains("server_type"))
这个 if 是多余的，json::value::get 就是 if not contains return default value

2022-06-04 17:36 UTC, MistEO commented on src/MeoAssistant/StartUpTask.cpp
> +        m_start_game_task_ptr->set_param(static_cast<ServerType>(params.get("server_type", 0)));
这里需要改成默认参数是不启动，接口需要向下兼容。

考虑使用 B 服 ~~或其他国际服~~ 且使用 python 接口的用户，升级 core 之后自动启动官服是有问题的

2022-06-04 17:36 UTC, MistEO commented on src/MeoAsstGui/ViewModels/SettingsViewModel.cs
> +                new CombData { Display = "官服", Value = "0" },
加个不自动启动作为默认项

2022-06-04 17:41 UTC, MistEO commented on src/MeoAsstGui/ViewModels/SettingsViewModel.cs
> +            _listTitle.Add("唤醒设置");
这个可以往下放放，一般人设过一次就不会改（？），其他常用的放上面。

2022-06-04 17:58 UTC, lhhxxxxx commented on src/MeoAssistant/GeneralConfiger.cpp
> +        m_intent_name[asst::ServerType::Official] = intent_json.at("Official").as_string();
mapkey用string也就意味着整体的协议要从enum/int重构为与config一致的string，这样会要求gui与config一致而非core与config一致，这样真的好吗？

2022-06-04 18:01 UTC, MistEO commented on src/MeoAssistant/GeneralConfiger.cpp
> +        m_intent_name[asst::ServerType::Official] = intent_json.at("Official").as_string();
现在好多都是，core 就当个甩手掌柜，都是集成方自己与 config 一致（

其实你转念想想，load resouce 都是集成方送进来的，集成方自己管理 config 也没毛病

2022-06-04 18:21 UTC, lhhxxxxx commented on src/MeoAsstGui/ViewModels/SettingsViewModel.cs
> +            _listTitle.Add("唤醒设置");
其他的好像也不会经常改吧（）

往下放的话放到哪呢？

2022-06-04 18:22 UTC, MistEO commented on src/MeoAsstGui/ViewModels/SettingsViewModel.cs
> +            _listTitle.Add("唤醒设置");
放到企鹅前面？

2022-06-04 18:31 UTC, lhhxxxxx commented on src/MeoAsstGui/ViewModels/SettingsViewModel.cs
> +            _listTitle.Add("唤醒设置");
如果有人是两个服来回切的呢（）

2022-06-04 18:32 UTC, lhhxxxxx commented on src/MeoAsstGui/ViewModels/SettingsViewModel.cs
> +            _listTitle.Add("唤醒设置");
其实现在的startup接口支持一个服做完任务后切另一个服继续做，不过gui不支持（）

2022-06-04 18:33 UTC, MistEO commented on src/MeoAsstGui/ViewModels/SettingsViewModel.cs
> +            _listTitle.Add("唤醒设置");
相对来说应该少吧，我感觉选基建无人机、改信用商店买什么啥的用的可能挺多

2022-06-05 08:40 UTC, MistEO commented on src/MeoAsstGui/Helper/AsstProxy.cs
> +            task_params["enable"] = enable;
改个名字？作为 startup 的接口参数来看， `enable` 有点意义不明，或许叫 `enable_startgame` 或者啥的。server_type 也是

2022-06-05 09:19 UTC, lhhxxxxx commented on src/MeoAssistant/GeneralConfiger.cpp
> +        m_intent_name[asst::ServerType::Official] = intent_json.at("Official").as_string();
servertype的默认直接设成"Official"，还是把官服复制一遍作为"Default"

2022-06-05 10:38 UTC, MistEO approved these changes

2022-06-05 10:56 UTC, merged

2022-06-05 11:01 UTC, lhhxxxxx commented
links to #651 #596 #60