Auto recruit
MaaAssistantArknights/MaaAssistantArknights pull request #7463
Opened 2023-12-02 15:22 UTC by lpowo

* fix #7452   

按照 #7452 的想法，在 #6900  的基础上增加了只选尽可能多选且只选高星tag的功能选项，并将选项策略合并
默认策略：只选一个高星tag组合
#6900 策略：选满三个tag为止
新增策略：尽可能多选高星tag，且额外的tag组合要么完整选入，要么舍弃；且若当前出现更高星tag组合，则不会考虑较低星，只会尽可能选高星tag组合（例如出现五星tag时，将尽力多选五星tag，不会考虑四星tag）

在GUI中增加了选择公招策略的功能，如图：
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/113409320/4b0d4f7d-5156-4144-b411-b96b604e49c7)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/113409320/18167d72-741a-4bcd-95c8-6f916dec008d)
最后用模拟器在自己账号上进行了一些自动公招测试。

2023-12-02 15:29 UTC, zzyyyl commented
`尽可能多选高星 tag` 挺符合我的需求，感觉也符合 @horror-proton 的描述：）

btw, commit message 写的乱可以 force push 修改，否则合并时会 squash

2023-12-02 15:40 UTC, lpowo commented
> 代码实现没细看，只看你的功能描述我觉得可以。`尽可能多选高星 tag` 挺符合我的需求，感觉也符合 @horror-proton 的描述：）
> 
> btw, commit message 写的乱可以 force push 修改，否则合并时会 squash

没问题，commit message已更改

2023-12-02 16:05 UTC, horror-proton commented on src/MaaCore/Task/Miscellaneous/AutoRecruitTask.cpp
> +        if (min_level == 3) return select;
这时候 `select` 是空的? 好像不大对, 是应该设成 `conbinations.front()` 吗
(是谁之前把 combinations 拼错了

2023-12-02 16:17 UTC, lpowo commented on src/MaaCore/Task/Miscellaneous/AutoRecruitTask.cpp
> +        if (min_level == 3) return select;
conbination传入的就是result_vec。按照排序规则，如果有高星tag，conbination.front()肯定是高星，会被加入selelct的。如果conbination的第一个就是三星，那代表这次只有三星tag能选了，按照之前的想法，是不会考虑三星的，所以select会是空的。
(combination拼错了。

2023-12-02 16:36 UTC, lpowo commented
将commit合并了一下

2023-12-02 17:47 UTC, lpowo commented on src/MaaCore/Task/Miscellaneous/AutoRecruitTask.cpp
>          }
打断点发现这一段代码在只有三星tag时就return了，后续的策略都不会用上

2023-12-02 17:52 UTC, Constrat commented
This should be a bit better.

2023-12-03 01:48 UTC, broken-paint commented on src/MaaCore/Task/Miscellaneous/AutoRecruitTask.cpp
> +        if (min_level == 3) return select;
我的锅我的锅，现在改了吧orz

2023-12-03 03:14 UTC, lpowo commented
> This should be a bit better.

Thanks! I used chat-gpt to translate zh-cn into en-us, ja-jp and ko-kr. Maybe ja-jp and ko-kr translations also need correction.

2023-12-03 04:35 UTC, horror-proton approved these changes
应该没什么问题, GUI 我不知道了

2023-12-03 08:43 UTC, status102 commented on src/MaaCore/Task/Miscellaneous/AutoRecruitTask.cpp
> +    m_select_extra_onlyrare_tags = (select_extra_tags_mode == 2);
这里如果存一个enum，然后后面直接判断enum会不会好一点

2023-12-03 12:24 UTC, status102 requested changes
应该对commits变基，而不是单纯改个名字来应对检查

2023-12-03 12:27 UTC, Constrat commented
This is what I was worried about

2023-12-03 13:33 UTC, horror-proton commented
> 非常对不起各位，由于我的一些错误操作导致了commit丢失，我会重新写好再发起pr的。 真的非常对不起！请给我一点时间！

不用重新写吧, 我这里有的, 你也可以直接 fetch github 上的 https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/b5bc8d3a58379477b3ed200f0578c05f19fb6056

2023-12-03 14:02 UTC, lpowo commented
> > 非常对不起各位，由于我的一些错误操作导致了commit丢失，我会重新写好再发起pr的。 真的非常对不起！请给我一点时间！
> 
> 不用重新写吧, 我这里有的, 你也可以直接 fetch github 上的 [b5bc8d3](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/b5bc8d3a58379477b3ed200f0578c05f19fb6056) 或者 [b57d0de](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/b57d0deeaa5f5a68b4e3726d81fa888a95c87579)
> 
> ```shell
> git fetch https://github.com/MaaAssistantArknights/MaaAssistantArknights.git b57d0deeaa5f5a68b4e3726d81fa888a95c87579
> ```
> 
> 现在已经恢复了 @lpowo

太感谢了QVQ！

2023-12-06 07:59 UTC, lpowo commented
求助，这样的conflict要怎么处理，[`c6ff421`](https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/7463/commits/c6ff4214f99b1fba68afa84e6df1c9d46caf563c) 的commit后还是存在conflict

2023-12-06 09:07 UTC, ABA2396 commented on src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs
> +                ConfigurationHelper.SetValue(ConfigurationKeys.SelectExtraTags, value);
这一步会不会有问题？原来存着的是"True""False"这样的字符串，是不是可以在get里做一下处理并且兼容一下旧配置

2023-12-06 09:20 UTC, ABA2396 commented on src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs
> +                ConfigurationHelper.SetValue(ConfigurationKeys.SelectExtraTags, value);
```
get
{
    if (bool.TryParse(_selectExtraTags, out bool boolValue))
    {
        // 兼容原来的布尔类型格式
        return boolValue ? "1" : "0";
    }
    else
    {
        // 尝试将字符串解析为整数
        if (int.TryParse(_selectExtraTags, out int intValue))
        {
            // 返回整数类型的字符串
            return intValue.ToString();
        }
        else
        {
            // 处理无法解析为整数的情况，默认为 "0"
            return "0";
        }
    }
}
```
类似这样，但core里面有过处理，int.TryParse或许可以省略？

2023-12-06 12:36 UTC, ABA2396 commented on src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs
> +                ConfigurationHelper.SetValue(ConfigurationKeys.SelectExtraTags, value);
getvalue点进去就有，会存默认值。可以在解析到true和false的时候也setvalue一下

2023-12-06 13:05 UTC, lpowo commented on src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs
> +                ConfigurationHelper.SetValue(ConfigurationKeys.SelectExtraTags, value);
明白了！

2023-12-06 13:27 UTC, ABA2396 commented on src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs
> +
``` c#
get
{
    if (int.TryParse(_selectExtraTags, out int intValue))
    {
        return intValue.ToString();
    }

    var value = "0";
    if (bool.TryParse(_selectExtraTags, out bool boolValue))
    {
        value = boolValue ? "1" : "0";
    }

    SetAndNotify(ref _selectExtraTags, value);
    ConfigurationHelper.SetValue(ConfigurationKeys.SelectExtraTags, value);
    return value;
}
```
想了下是不是这样比较好

2023-12-08 08:54 UTC, lpowo commented
> 草，好像刚刚的提交影响到这个pr了）

学新代码格式中x

2023-12-09 06:22 UTC, ABA2396 approved these changes

2023-12-09 06:34 UTC, lpowo commented
最近的两个commit message 出问题了，该怎么解决（
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/113409320/8d31b321-69ef-4e62-a129-22d79775f384)

2023-12-09 06:35 UTC, horror-proton commented
@zzyyyl 啊现在这个应该怎么合并, rebase 吗, 还有为啥 commit message 检查没过

2023-12-09 06:39 UTC, status102 commented
> @zzyyyl 啊现在这个应该怎么合并, rebase 吗, 还有为啥 commit message 检查没过

因为那两个commit是Merge commit（虽然改了名字
rebase or squash

2023-12-09 06:46 UTC, horror-proton commented
> 因为那两个commit是Merge commit（虽然改了名字 rebase or squash

草, 这下麻烦了 (

2023-12-09 06:51 UTC, lpowo commented
能回滚到[09be0d8](https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/7463/commits/09be0d8151521e539037cca62a5133adc6f388e6)，然后我再把出问题的两个commit重新做一遍吗，

2023-12-09 07:05 UTC, status102 commented
> 能回滚到[09be0d8](https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/7463/commits/09be0d8151521e539037cca62a5133adc6f388e6)，然后我再把出问题的两个commit重新做一遍吗，

给你rebase了一下，是直接推这个分支还是推别个分支（没权限

2023-12-09 07:08 UTC, lpowo commented
> 给你rebase了一下，是直接推这个分支还是推别个分支（没权限

直接推这个分支吧

2023-12-09 07:14 UTC, horror-proton commented
InitAutoRecruit 被搞没了 ( https://github.com/MaaAssistantArknights/MaaAssistantArknights/compare/27568709ebf58322a5e021cc83d88356136732fe..9ba69e9c79a3ecbce43a8487384cea7f932785d0

2023-12-09 07:26 UTC, lpowo commented
> InitAutoRecruit 被搞没了, 这是正常的吗, rebase 的时候是不是冲突解决错了 ( https://github.com/MaaAssistantArknights/MaaAssistantArknights/compare/27568709ebf58322a5e021cc83d88356136732fe..9ba69e9c79a3ecbce43a8487384cea7f932785d0

重新加进去了！

2023-12-09 07:31 UTC, status102 commented
>Merge commit是需要squash进已经有的commit里面吗，我是不是得弄一个没内容的commit来容纳这些Merge commit

直接对你的commits进行一个rebase然后force push就行

2023-12-13 03:17 UTC, ABA2396 commented
是不是可以合了

2023-12-13 07:37 UTC, horror-proton commented
> 是不是可以合了

应该早就可以合并了.
好像改得挺多的, 要不 rebase and merge?

2023-12-13 07:48 UTC, status102 commented
> 应该早就可以合并了.
> 好像改得挺多的, 要不 rebase 合并?

应该是squash合并吧

2023-12-13 07:59 UTC, lpowo commented
> > 应该早就可以合并了.
> > 好像改得挺多的, 要不 rebase 合并?
> 
> 应该是squash合并吧

全部squash进一个commit里面吗

2023-12-13 08:12 UTC, status102 commented
> > > 应该早就可以合并了.
> > > 好像改得挺多的, 要不 rebase 合并?
> > 
> > 应该是squash合并吧
> 
> 全部squash进一个commit里面吗
> 
> 

GitHub合并的时候能自动squash，所以不用手动改

2023-12-13 08:23 UTC, merged

2023-12-13 08:32 UTC, lpowo commented
太好了！谢谢各位的指导和帮助！