fix. 修复复刻活动stageId识别错误
MaaAssistantArknights/MaaAssistantArknights pull request #747
Opened 2022-06-04 23:44 UTC by aa889788

复刻活动必定晚于插曲，因此在 stage.json 中必定位于下方，而复刻关闭
后 drops 为空，会被直接忽略，只需让晚出现的 stageId 覆盖早出现的即
可返回正确的 stageId。
而为了能够正确识别不同服务器活动开启时间不同的情况，在 StageInfo
中加入了 openTime 和 closeTime 来进行判断，同时在 stageCode 后加
入 "_server" 来进行区别。

2022-06-05 07:46 UTC, MistEO commented
`stage_code` 是会用来取图像识别结果的，因此不能修改该字段_(:з」∠)_

除非给图像识别的结果也加上 `_server`, 但是总体这样我觉得不够合理。每个字段应该保证其独立性，或许可以单独写个 server 的逻辑来整

~~但我觉得没必要，只把 `emplace` 改成 overwrite 的就好了~~

2022-06-05 07:50 UTC, MistEO requested changes

2022-06-05 07:50 UTC, MistEO commented on src/MeoAssistant/StageDropsConfiger.cpp
> +				m_stage_info.erase(server_key);
这里直接

```c++
m_stage_info.insert_or_assign(key, info);
```

就可以了，不需要先删除再插入

另外建议与项目风格保持一致

```c++
m_stage_info.insert_or_assign(std::move(key), std::move(info));
```

2022-06-05 07:51 UTC, MistEO commented
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/629

2022-06-05 13:01 UTC, aa889788 commented on src/MeoAssistant/StageDropsConfiger.cpp
> +				m_stage_info.erase(server_key);
又改了一下，下划线也不用加了，反正`m_stage_info`是给程序看的，不用考虑可读性。考虑到图像识别的问题，给`StageDropsImageAnalyzer`也加了个`m_server`属性，会用到`m_stage_info`的应该也就这两个地方了。
还有一个问题就是，`FightTask`获取到`server`后似乎并没有调用`m_stage_drops_plugin_ptr->set_server(std::move(server));`，是故意删了还是忘了？

2022-06-05 13:02 UTC, aa889788 commented on src/MeoAssistant/StageDropsConfiger.cpp
> +				m_stage_info.erase(server_key);
`StageInfo`不能 move ，因为在接下来的循环里还要复用，`StageKey`改成 move 了

2022-06-05 16:04 UTC, MistEO commented
![image](https://user-images.githubusercontent.com/18511905/172059490-d0cec5ea-fe90-4b1d-9f62-1ac7bbf7935e.png)


这里的逻辑还是有问题的，这就是我上面说的图像识别到的还是不带 server 的，对于图像这边来说是未知关卡，会把全部材料跑一遍

~~所以说不要加 server 了~~

2022-06-05 16:07 UTC, MistEO commented
另外这个问题，即使修改了，如果用户不及时更新客户端（stages.json 没更新），也并没有什么用。
从我们这边的数据来看大部分用户客户端更新的很慢，且企鹅那边已经通过根据上传时间自行调整相关数据了。

所以我觉得这个 PR 的意义不是特别大

2022-06-05 19:11 UTC, MistEO commented
讨论了下，这个 PR 不是很合理，现在的 server 判断其实也都没做，都是 CN. 所以暂时不会合并，后面做完 server 及外服相关适配之后可能考虑 reopen

还是感谢你的提交 ✿✿ヽ(°▽°)ノ✿

2022-06-05 19:11 UTC, closed without merging

2022-06-06 00:07 UTC, aa889788 commented
> 讨论了下，这个 PR 不是很合理，现在的 server 判断其实也都没做，都是 CN. 所以暂时不会合并，后面做完 server 及外服相关适配之后可能考虑 reopen
> 
> 还是感谢你的提交 ✿✿ヽ(°▽°)ノ✿

那要不我先把`get_stage_info`改一下，改成这样？
```C
const auto& get_stage_info(const std::string& code, StageDifficulty difficulty, const std::string& server = "CN") const
{
    unsigned long current = (unsigned long)time(0)*1000;
    StageKey key{ code, difficulty, server };
    if (auto find_iter = m_stage_info.find(key);
        find_iter != m_stage_info.end() &&
        current >= find_iter->second.openTime &&
        current < find_iter->second.closeTime) {
        return find_iter->second;
    }
    else {
        static StageInfo empty_info;
        return empty_info;
    }
}
```
这样先留好接口，以后适配也方便