ci: 修复smoke-testing重复加载外服和国服资源导致潜在的非预期TaskData字段问题
MaaAssistantArknights/MaaAssistantArknights pull request #7511
Opened 2023-12-08 14:01 UTC by status102

修复类似 [0291163](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/02911638ce49730d3745fd910c250bc31a9cd44c) 的问题

（本地DEBUG就先扔着了

2023-12-09 09:37 UTC, Constrat commented
@status102 Is it normal that Sample.exe in Release is 212KB while in Debug it's 72KB?
Also, the release one shows all the outputs correctly (as expected). The debug only opens a terminal and then closes quickly.

2023-12-09 09:50 UTC, Constrat approved these changes
`DEBUG`:
- [x] YostarEN 
- [x] YostarJP
- [x] YostarKR 
- [x] txwy 
I'm guessing there is "Official"

2023-12-09 10:35 UTC, Constrat requested changes
I want to try and make some changes.
Wait before merge :)

2023-12-09 10:40 UTC, status102 commented
wow, but it will look like `Sample.exe` (with no param)

2023-12-09 10:41 UTC, Constrat commented
> wow, but it will look like `Sample.exe` (with no param)

Yeah just need to add a check: if there is a param, don't run the official loader

2023-12-09 10:46 UTC, status102 commented
> Yeah just need to add a check: if there is a param, don't run the official loader

no, it is no sense. You need to load official resource FIRST. Overseas resource is incomplete.

2023-12-09 10:47 UTC, Constrat commented
> > Yeah just need to add a check: if there is a param, don't run the official loader
> 
> no, it is no sense. You need to load official resource FIRST. Overseas resource is incomplete.

So 4 official needs to be loaded 4 times? For every smoketest?

2023-12-09 10:52 UTC, status102 commented
> So `official` needs to be loaded 4 times? For every smoketest?

yes

2023-12-09 10:56 UTC, Constrat approved these changes

2023-12-09 11:02 UTC, status102 commented
> So `official` needs to be loaded 4 times? For every smoketest?

Overseas resource files show resource differences between official and overseas. So we have to loaded more than once.

2023-12-09 12:51 UTC, zzyyyl commented on src/Cpp/main.cpp
> +#ifdef SMOKE_TESTING
这玩意在哪定义了吗

2023-12-09 12:56 UTC, status102 commented on src/Cpp/main.cpp
> +#ifdef SMOKE_TESTING
没找到（不知道是怎么算的，但是能跑，很怪

2023-12-09 16:05 UTC, status102 commented on src/Cpp/main.cpp
> +#ifdef SMOKE_TESTING
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/dev/src%2FCpp%2FMaaSample.vcxproj#L208-L220

2023-12-11 03:37 UTC, status102 commented
没问题就合了 @zzyyyl

2023-12-12 04:25 UTC, merged