Refector: config
MaaAssistantArknights/MaaAssistantArknights pull request #7683
Opened 2023-12-18 03:48 UTC by Cryolitia

2023-12-18 03:50 UTC, Cryolitia commented
> ## ⚠️ Found 5 invalid commit(s):
> * refctor: config/GUI [`b8c2bb2`](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/b8c2bb2382e57d96defadb3dbca200ed8e325f0d)
> * Merge remote-tracking branch 'upstream/dev' into config [`2573c20`](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/2573c20bd025a8975935c380e17cb96a0d5a0947)
> * Reduce warning [`1cca359`](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/1cca3590d8902619c396c293017d00e92b8136be)
> * Merge remote-tracking branch 'upstream/rft/dotnet8' into config [`86bab45`](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/86bab45bcd2298408a21ef87d638410226b2007c)
> * 谁把我fody删了 [`2e9e601`](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/2e9e601cb9781c8f1b3f1ef97c3ca4226898a565)
> 
> Please follow the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) format.

哎呀，无所谓的啦，我们只要squash merge就好了嘛

2023-12-18 16:05 UTC, ABA2396 commented
#6918 这玩意也直接塞到全局里去吧

2023-12-29 10:48 UTC, Cryolitia commented
先合进去测试稳定性吧，要不然隔三差五冲突

2023-12-29 11:28 UTC, MistEO requested changes
在没有自动数据迁移功能之前，我反对本条 PR。

2023-12-29 11:29 UTC, Cryolitia commented
> 在没有自动数据迁移功能之前，我反对本条 PR。

进dotnet8又不是进dev，那么紧张干什么

2023-12-29 12:34 UTC, MistEO commented
哪个分支也不行，这不是把 regression 带入别的 feature 了吗？

2024-01-01 10:35 UTC, status102 commented
问问TaskQueueOrder方便从<string, int>改成类似于[{type},{type}]的格式么？

2024-01-05 03:25 UTC, ABA2396 commented
现在准备咋整啊）

2024-01-05 05:53 UTC, Cryolitia commented
累了，有时间再说吧

2024-01-11 09:29 UTC, Cryolitia commented
先把框架推上去，谁有时间慢慢迁移吧，没时间就不迁移了

2024-01-11 09:31 UTC, Cryolitia commented
> 问问TaskQueueOrder方便从<string, int>改成类似于[{type},{type}]的格式么？

你如果能写旧配置到新配置的迁移就很方便

2024-01-11 09:32 UTC, ABA2396 commented
要不先重新基于dev拉个分支然后squash到那个新分支去

2024-01-11 09:39 UTC, Cryolitia commented
> 要不先重新基于dev拉个分支然后squash到那个新分支去

merge的时候squash merge就行吧

2024-01-11 09:46 UTC, ABA2396 commented
哦看了下好像只是加上了选项但还没把设置换到新的，那应该没什么问题

2024-01-11 10:08 UTC, status102 commented
> > 问问TaskQueueOrder方便从<string, int>改成类似于[{type},{type}]的格式么？
> 
> 你如果能写旧配置到新配置的迁移就很方便

其他设置项有迁移了是么，等有空看看，最近忙的要死也是

2024-01-11 10:10 UTC, ABA2396 commented
> > > 问问TaskQueueOrder方便从<string, int>改成类似于[{type},{type}]的格式么？
> > 
> > 
> > 你如果能写旧配置到新配置的迁移就很方便
> 
> 其他设置项有迁移了是么，等有空看看，最近忙的要死也是

没迁移，也还没用上，先搭了个框架

2024-01-11 10:24 UTC, Cryolitia commented
> > > 问问TaskQueueOrder方便从<string, int>改成类似于[{type},{type}]的格式么？
> > 
> > 
> > 你如果能写旧配置到新配置的迁移就很方便
> 
> 其他设置项有迁移了是么，等有空看看，最近忙的要死也是

只迁移了 DarkMode 作为使用示例

2024-01-28 01:43 UTC, status102 commented
> 只迁移了 DarkMode 作为使用示例

DarkMode只有作为新配置的使用示例，而没有从旧配置进行数据迁移的是么

2024-01-28 01:55 UTC, Cryolitia commented
> DarkMode只有作为新配置的使用示例，而没有从旧配置进行数据迁移的是么

是，DarkMode在去年九月就实验性的挪过去了。

2024-02-02 10:17 UTC, status102 commented on src/MaaWpfGui/Configuration/ConfigFactory.cs
> +            }
这里会导致死锁么

2024-02-04 05:35 UTC, Cryolitia commented on src/MaaWpfGui/Configuration/ConfigFactory.cs
> +            }
我没测试过，你试试

2024-02-04 06:24 UTC, status102 commented on src/MaaWpfGui/Configuration/ConfigFactory.cs
> +            }
试了下会卡在Line.221这里

2024-02-04 06:51 UTC, Cryolitia commented on src/MaaWpfGui/Configuration/ConfigFactory.cs
> +            }
> 试了下会卡在Line.221这里

那辛苦你看着改下吧

2024-05-24 01:36 UTC, Cryolitia commented
先合了吧，反正不影响现有代码，我很久不用Windows了也没时间改WPF了

2024-05-24 01:36 UTC, merged