feat: 远控支持localhost上的连接
MaaAssistantArknights/MaaAssistantArknights pull request #8061
Opened 2024-01-22 05:23 UTC by SherkeyXD

fix #8053

2024-01-22 21:00 UTC, KevinT3Hu requested changes
判断逻辑好像错了xd，localhost地址会在https那里就error掉（

2024-01-22 21:03 UTC, KevinT3Hu commented
而且用contains判断的话是不是会有办法绕开（
比如

`http://xxx.xxx/localhost`

这样

2024-01-23 01:42 UTC, Cryolitia requested changes

2024-01-23 01:42 UTC, Cryolitia commented on src/MaaWpfGui/Services/RemoteControl/RemoteControlService.cs
> +            else if (endpoint.ToLower().Contains("127.0.0.1") || endpoint.ToLower().Contains("localhost"))
整个127.0.0.0/8都是回环地址，see https://datatracker.ietf.org/doc/html/rfc5735#section-3

2024-01-23 01:44 UTC, Cryolitia commented
此外，应该允许用户在充分理解使用HTTP的危险性的前提下继续使用HTTP。对于运行在不可信平台上的开源软件，设置这种障碍毫无意义。

2024-01-23 03:53 UTC, SherkeyXD commented
那干脆把https的检测删了（

设置的时候提示下用户不安全就行了（？

2024-01-23 05:03 UTC, Cryolitia requested changes

2024-01-23 05:03 UTC, Cryolitia commented on src/MaaWpfGui/Services/RemoteControl/RemoteControlService.cs
> +                return false;
```suggestion
                return true;
```

2024-02-06 12:57 UTC, Cryolitia commented
不要拦着用户，警告差不多得了

2024-02-06 13:00 UTC, SherkeyXD commented
> 不要拦着用户，警告差不多得了

empty 的情况总得拦着吧）

2024-02-06 13:02 UTC, Cryolitia commented
> empty 的情况总得拦着吧）

这怎么看也不是只拦empry啊

2024-02-06 13:39 UTC, Cryolitia approved these changes

2024-02-07 02:16 UTC, merged