更新了README里面的license badge
MaaAssistantArknights/MaaAssistantArknights pull request #8909
Opened 2024-04-26 14:22 UTC by KPCOFGS

点击license badge的时候可以直接传用户到license网页

2024-04-29 01:21 UTC, AnnAngela requested changes

2024-04-29 01:21 UTC, AnnAngela commented on README.md
> +    <a href="https://spdx.org/licenses/AGPL-3.0-only.html"><img alt="license" src="https://img.shields.io/github/license/MaaAssistantArknights/MaaAssistantArknights"></a>
建议还是用markdown格式写链接好一些

2024-04-29 01:40 UTC, ABA2396 commented
这为啥不本地改完了再一起推上来

2024-04-29 01:42 UTC, KPCOFGS commented
一开始以为很快就搞完了=。= 一直在弄那个间隔距离

2024-04-29 01:51 UTC, AnnAngela requested changes
不需要链接的按钮可以改回原来的`<img>`格式，避免出现预期外的链接

2024-04-29 01:51 UTC, ABA2396 commented on README.md
> +[![LICENSE](https://img.shields.io/github/license/MaaAssistantArknights/MaaAssistantArknights)](https://spdx.org/licenses/AGPL-3.0-only.html)
这儿多了个 [

2024-04-29 01:59 UTC, KPCOFGS commented
好了

2024-05-03 13:54 UTC, closed without merging

2024-05-05 01:11 UTC, AnnAngela commented
> 好了，但是貌似还是有点间隔问题 为啥不用`<a></a>`

md 最好还是用 markdown

2024-05-05 01:12 UTC, AnnAngela commented
前几天旅游去了没时间看