fix. 修改公招流程
MaaAssistantArknights/MaaAssistantArknights pull request #951
Opened 2022-06-21 05:37 UTC by zzyyyl

fix #945

具体更改：

1. 检查时间是否调整过改为用 `09` 而不是 `01`
2. 获取调整时间的按钮时不再使用检测到 01 后 rectMove 的操作，而是检测到 01 后再匹配按钮（更改前后都是只截一次图）
3. 稍微调整了以上几点涉及到的模板图片的名字

我这边除了刷新操作没测，用 3、4 星的 Tag 测起来没问题，也不会重复识别

2022-06-21 06:10 UTC, zzyyyl commented
#935 那边对公招部分的改动测试：

1. 刷新操作没测
2. 用 3 星的 Tag 测起来没问题，但稳定重复识别，不过没有出现时间被调成 8 小时的情况，都是 9 小时。（这应该是老问题）
3. 用 4 星的 Tag 测起来没问题，也不会重复识别。

2022-06-21 06:11 UTC, zzyyyl commented
我觉得公招这部分问题跟网络和电脑性能关系很大，我这测了等于没测（

2022-06-21 06:16 UTC, zzyyyl commented
我这边和 #935 的 conflict 应该是这个更改
```diff
-if (check_time_unreduced()) {
+if (!check_time_reduced()) {
```
等那边合了我直接改就完事了

2022-06-21 09:26 UTC, horror-proton commented
理论上我的 https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/935 修改之后行为应该与之前基本一致, 只是打出来的日志有点不同 (不然就不叫 code tidy 了). 
不过 3 星 Tag 下的重复识别具体指的是什么情况? 🤔

2022-06-21 13:44 UTC, MistEO commented
#935 merged, 有冲突了

2022-06-21 13:44 UTC, zzyyyl commented
https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/935#discussion_r902637167

2022-06-21 14:03 UTC, zzyyyl commented
> [#935 (comment)](https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/935#discussion_r902637167)

在整了，测试完就 push 上来给玛丽看看

2022-06-21 14:37 UTC, MistEO requested changes

2022-06-21 14:37 UTC, MistEO commented on src/MeoAssistant/AutoRecruitTask.cpp
> +                Log.trace("recruit tags refreshed for the " + std::to_string(++refresh_count) + "-th time, rerunning recruit task");
`++refresh_count` 不建议放在日志里，最好单独一行。

日志所在行不应该影响功能（防止这种情况：某天我嫌日志碍事，没细看就随手把这行删了。~~我就删了一行日志怎么出bug了~~）

2022-06-21 14:37 UTC, MistEO commented on src/MeoAssistant/AutoRecruitTask.cpp
> +    for (int refresh_count = 0; refresh_count <= 3; ) {
是不是不用等于？

2022-06-21 14:53 UTC, zzyyyl commented on src/MeoAssistant/AutoRecruitTask.cpp
> +    for (int refresh_count = 0; refresh_count <= 3; ) {
不等于的话相当于刷新第三次之后没确认就退出了（其实这个应该放在 refresh 那块，~但是放在那了我还写 for 干啥~

2022-06-21 15:03 UTC, MistEO commented on src/MeoAssistant/AutoRecruitTask.cpp
> +    for (int refresh_count = 0; ; ) {
这写法好怪啊（

2022-06-21 15:03 UTC, zzyyyl commented on src/MeoAssistant/AutoRecruitTask.cpp
> +    for (int refresh_count = 0; ; ) {
确实啊（要不还是用 while 吧

2022-06-21 15:05 UTC, horror-proton commented on src/MeoAssistant/AutoRecruitTask.cpp
> +    for (int refresh_count = 0; ; ) {
我也经常这么写 (x

2022-06-21 15:21 UTC, horror-proton commented
我魔改了一下图片让它 09 总是识别失败而 01 识别成功, 它应该不停切换数字试图找到 09, 但是当界面上不是 01 而它 09 识别失败进入下一个循环之后又因为 01 识别也失败而没有去切换数字, 就不停点 Tag, 这应该不对头吧

2022-06-21 15:49 UTC, horror-proton commented
> 

https://github.com/zzyyyl/MaaAssistantArknights/blob/4383d6218c1a79a4127398b1b3e284d3c5c8d5fe/src/MeoAssistant/RecruitCalcTask.cpp#L22

https://github.com/zzyyyl/MaaAssistantArknights/blob/4383d6218c1a79a4127398b1b3e284d3c5c8d5fe/src/MeoAssistant/RecruitImageAnalyzer.cpp#L12

我猜问题出在这里

2022-06-22 04:25 UTC, zzyyyl commented
之前和现在 `RecruitImageAnalyzer` 的逻辑都是是检测到 `01` 才进行调整，没改
https://github.com/zzyyyl/MaaAssistantArknights/blob/4383d6218c1a79a4127398b1b3e284d3c5c8d5fe/src/MeoAssistant/RecruitImageAnalyzer.cpp#L56

2022-06-22 04:41 UTC, zzyyyl commented
你的意思是把 `RecruitImageAnalyzer` 的时间检测也改成检测 `09` ？
我觉得直接忽略检测结果不好，可能会有其他问题

还有，我觉得可能要给 [while 那段](https://github.com/zzyyyl/MaaAssistantArknights/blob/4383d6218c1a79a4127398b1b3e284d3c5c8d5fe/src/MeoAssistant/AutoRecruitTask.cpp#L129)加个循环次数上限，不然按照上面所说可能会一直检测卡着。也许可以直接把 m_cur_times 拿来用？（类似 [`asst::AutoRecruitTask::_run`](https://github.com/zzyyyl/MaaAssistantArknights/blob/4383d6218c1a79a4127398b1b3e284d3c5c8d5fe/src/MeoAssistant/AutoRecruitTask.cpp#L55) 里的循环） @MistEO 

今天下午有门考试，回复可能不及时，要改什么的话我晚上再看看

2022-06-22 04:50 UTC, horror-proton commented
我这里忽略检测只是为了排查问题, 确实是应该也改成检测 09.

~卡着就卡着吧, 反正也没啥坏处, 或者~ 限制重试次数的话可以把重试次数设定得高一点, 比如 18 或者 27 之类, 万一调过头了还能绕回来

2022-06-22 10:30 UTC, zzyyyl commented
单槽位招募：
![image](https://user-images.githubusercontent.com/74587068/175007425-6e6003bd-c53d-493a-a439-d2a66fe7dc53.png)
多槽位招募：
![image](https://user-images.githubusercontent.com/74587068/175007867-d735696e-3775-4f16-9f58-ea289f1f1469.png)
日志：
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8956765/asst.log)

2022-06-22 10:42 UTC, zzyyyl commented
https://user-images.githubusercontent.com/74587068/175009928-1287a476-83f2-4f59-8fdf-d0583cb0d819.mp4

测试效果很好（
用的OBS，画面下半部分是显示器采集，为了体现消息弹窗

2022-06-23 14:52 UTC, zzyyyl commented
好像没过编译，我整整（

2022-06-23 15:54 UTC, MistEO approved these changes

2022-06-24 00:44 UTC, merged