fix: 修复坍缩范式插件导致的Gui和傀影/水月肉鸽初始化Bug
MaaAssistantArknights/MaaAssistantArknights pull request #9573
Opened 2024-07-08 16:06 UTC by Alan-Charred

…se plugins

2024-07-08 16:20 UTC, Constrat commented
Merge?
Don't worry about it. This is why we have nightly releases.

2024-07-08 16:27 UTC, Rbqwow commented
> Merge? Don't worry about it. This is why we have nightly releases.

we forgot to release a nightly build to test 😶

#9570

2024-07-08 16:29 UTC, Constrat commented
I should have released a nightly before the merge. And another after the merge. To differentiate.

2024-07-08 23:50 UTC, status102 commented
TL;DR
希望不同功能的提交可以拆分pr

2024-07-09 04:30 UTC, status102 requested changes
好像还有其他测试代码没有移除

2024-07-09 04:30 UTC, status102 commented on src/MaaCore/Config/Roguelike/RoguelikeCollapsalParadigmConfig.h
> +            return m_rare_clp_pds.at(theme);
直接用上面find的结果吧

2024-07-09 06:35 UTC, Alan-Charred commented on src/MaaCore/Config/Roguelike/RoguelikeCollapsalParadigmConfig.h
> +            return m_rare_clp_pds.at(theme);
这里不是测试代码，是兜底，如果没有就返回一个空的set，有就返回本来应该有的值。
如果返回值类型稍微改一下，是可以直接写成m_rare_clp_pds[theme]的，利用unordered_map没有就会自行创建默认元素的特性。

之前无法进入其他主题肉鸽的bug是因为set_params期间触发了这个函数，.at()找不到对应的东西报错了。
现在做了两层变化:
1. 对于与特定主题绑定的肉鸽任务参数，只在特定主题的时候读取；
2. 就算瞎读，如果读不到也就返回一个空集合，不影响之后的流程。

2024-07-09 06:36 UTC, Alan-Charred commented on src/MaaCore/Config/Roguelike/RoguelikeCollapsalParadigmConfig.h
> +            return m_rare_clp_pds.at(theme);
哦我明白您意思了，稍等。

2024-07-09 06:37 UTC, zzyyyl commented on src/MaaCore/Task/Roguelike/RoguelikeCollapsalParadigmTaskPlugin.cpp
> +            if ((*result_it1).text == "坍缩范式加深") {
我测是石！快跑！

这个地方硬编码不好吧

2024-07-09 06:44 UTC, Alan-Charred commented on src/MaaCore/Task/Roguelike/RoguelikeCollapsalParadigmTaskPlugin.cpp
> +            if ((*result_it1).text == "坍缩范式加深") {
我之前的方案是从tasks.json里读这个字符串，这样更符合规范吗？
或者写在某个文件里，为了这个字符串专门读取一下？

2024-07-09 06:48 UTC, Alan-Charred commented on src/MaaCore/Config/Roguelike/RoguelikeCollapsalParadigmConfig.h
> +            return m_rare_clp_pds.at(theme);
@status102 改好了，您看看？我没有找到其他的测试用代码了。

2024-07-09 06:50 UTC, Alan-Charred commented on src/MaaCore/Task/Roguelike/RoguelikeCollapsalParadigmTaskPlugin.cpp
> +            if ((*result_it1).text == "坍缩范式加深") {
```C++
std::string_view deepen_text = (Task.get<OcrTaskInfo>(theme + "@Roguelike@CheckCollapsalParadigms_banner")->text)[0]; // "坍缩范式加深"
```
@zzyyyl 这是之前的写法，如果这种更规范的话，我就改回去。

2024-07-09 06:54 UTC, Alan-Charred commented on src/MaaCore/Task/Roguelike/RoguelikeCollapsalParadigmTaskPlugin.cpp
> +            if ((*result_it1).text == "坍缩范式加深") {
> 我测是石！快跑！
> 
> 这个把加深和消退分别写两个ocrtask会好一点吧
分成两个OcrTask...那我岂不是要再加一个指针？代码可读性越来越💩了（

注意右上角是有可能出现复数个Banner的，所以我需要排序后遍历。

2024-07-09 07:05 UTC, zzyyyl commented on src/MaaCore/Task/Roguelike/RoguelikeCollapsalParadigmTaskPlugin.cpp
> +            if ((*result_it1).text == "坍缩范式加深") {
> ```c++
> std::string_view deepen_text = (Task.get<OcrTaskInfo>(theme + "@Roguelike@CheckCollapsalParadigms_banner")->text)[0]; // "坍缩范式加深"
> ```
> 
> @zzyyyl 这是之前的写法，如果这种更规范的话，我就改回去。

这样大概确实规范一些，按照玛丽标准

2024-07-09 10:46 UTC, status102 submitted a review, later dismissed

2024-07-09 10:46 UTC, status102 commented on src/MaaCore/Task/Roguelike/RoguelikeCollapsalParadigmTaskPlugin.cpp
> +    if (DEBUG) { analyzer1.save_img(utils::path("debug") / utils::path("collapsalParadigms")); }
DEBUG已使用，参照其他模块

2024-07-09 10:52 UTC, status102 commented
还有些问题像是ocrReplace格式，参照其他修改

使用->而不是(*).

2024-07-10 13:07 UTC, horror-proton commented on src/MaaCore/Task/Roguelike/RoguelikeFoldartalUseTaskPlugin.cpp
> +                    if (m_config->get_theme() == RoguelikeTheme::Sami && m_config->get_check_clp_pds()) {
这种地方是不是直接 `if (m_clp_pd_plugin)` 就行了, 不然万一之后 `RoguelikeStageEncounterTaskPlugin` 改了条件然后其他地方忘记改了就不好了

2024-07-10 14:46 UTC, status102 commented on src/MaaCore/Task/Roguelike/RoguelikeCollapsalParadigmTaskPlugin.cpp
> +#undef ASST_DEBUG
为啥不直接使用ASST_DEBUG，还要重新转换

2024-07-10 14:48 UTC, status102 commented on src/MaaCore/Task/Roguelike/RoguelikeConfig.h
> +        bool m_need_check_panel = false;
加点注释？

2024-07-10 17:20 UTC, Alan-Charred commented
> 日版翻译更正 現在の崩壊値 パラダイムロスト進行 パラダイムロスト減退
> 
> 原图

Thanks a lot!

2024-07-10 17:23 UTC, Alan-Charred commented on src/MaaCore/Task/Roguelike/RoguelikeCollapsalParadigmTaskPlugin.cpp
> +#undef ASST_DEBUG
事情是这样的，我研究出来一个只对单个文件开ASST_DEBUG的方法，但是如果我不undef，通过function call这个ASST_DEBUG defined就会被传播到别的文件去，然后弄一连串连锁反应。简单来说这样的话，就可以很简单的在编译过程中加一行参数来单独开启我插件的debug模式。（顺带一说，连锁反应主要影响的是Log.info。（其实我很想推广这个

2024-07-10 17:29 UTC, Alan-Charred commented on src/MaaCore/Task/Roguelike/RoguelikeConfig.h
> +        bool m_need_check_panel = false;
好！

2024-07-10 17:44 UTC, Alan-Charred commented on src/MaaCore/Task/Roguelike/RoguelikeFoldartalUseTaskPlugin.cpp
> +                    if (m_config->get_theme() == RoguelikeTheme::Sami && m_config->get_check_clp_pds()) {
您说的好，我突然有了一个更有趣的想法。这个条件应该封装在我的插件里，而不是写在.h文件里。

2024-07-10 17:56 UTC, Alan-Charred commented on src/MaaCore/Task/Roguelike/RoguelikeFoldartalUseTaskPlugin.cpp
> +                    if (m_config->get_theme() == RoguelikeTheme::Sami && m_config->get_check_clp_pds()) {
最新的版本应该舒服多了。其实我本来想在每个肉鸽插件下加个属性，显示他们适用于的主题，这样插件加载部分的代码也会更好看一些。但是C++里我似乎没办法搞一个class的set，如果创建一堆shared_ptr，最后再释放不需要的，似乎又不太好看。Orz

2024-07-11 02:10 UTC, status102 commented on src/MaaCore/Task/Roguelike/RoguelikeCollapsalParadigmTaskPlugin.cpp
> +#undef ASST_DEBUG
单插件ASST_DEBUG感觉没有什么使用需求，感觉留在自己的分支里更好，而不是进主分支

2024-07-11 03:15 UTC, Alan-Charred commented on src/MaaCore/Task/Roguelike/RoguelikeCollapsalParadigmTaskPlugin.cpp
> +#undef ASST_DEBUG
已修改，感谢建议。

2024-07-11 06:27 UTC, SherkeyXD approved these changes

2024-07-11 17:12 UTC, merged