feat: RoguelikeMode::FastPass
MaaAssistantArknights/MaaAssistantArknights pull request #9812
Opened 2024-07-21 05:18 UTC by Alan-Charred

2024-07-21 06:04 UTC, zzyyyl commented on resource/tasks.json
> +        "specialParams": [321, 138, 47, 450, 32, 15, 10]
这是什么邪道用法（

2024-07-21 06:04 UTC, Lancarus commented
真厉害
如果模版匹配的精度够的话，建议用这个来识别每个点的类型？
![image](https://github.com/user-attachments/assets/1e71625b-aa21-484e-88df-973cf49461ee)
这样可以在第一面的时候确定三列的点，而不需要滑动

2024-07-21 06:04 UTC, Lancarus commented on resource/tasks.json
> +        "specialParams": [321, 138, 47, 450, 32, 15, 10]
挺好的啊，总有国服ocr，外服用不了的时候

2024-07-21 06:06 UTC, status102 commented on src/MaaCore/Vision/MultiTemplMatcher.h
这个单拆一个pr吧

2024-07-21 06:15 UTC, status102 commented on resource/tasks.json
> +            ["Sarkaz@Roguelike@MapNode_RogueTrader_grey.png", "8"]
这个直接写到cpp吧，这个放这也还是要去读cpp才能懂

2024-07-21 07:04 UTC, status102 requested changes

2024-07-21 07:15 UTC, status102 requested changes

2024-07-21 07:15 UTC, status102 commented on src/MaaCore/Task/Roguelike/Map/RoguelikeRoutingTaskPlugin.cpp
> +    cv::Mat grayImage;
直接写一个analyzer吧

2024-07-21 08:05 UTC, status102 commented on src/MaaCore/Task/Roguelike/Map/RoguelikeRoutingTaskPlugin.h
> +            };
是否在找：sort_by_horizontal_

2024-07-21 13:48 UTC, Alan-Charred commented on resource/tasks.json
> +        "specialParams": [321, 138, 47, 450, 32, 15, 10]
这个实际上是用于程序内部把templ_name转换成节点类型RoguelikeNodeType的。（瞎写的，等以后可以改，都可以改

2024-07-21 13:50 UTC, Alan-Charred commented on resource/tasks.json
> +            ["Sarkaz@Roguelike@MapNode_RogueTrader_grey.png", "8"]
暂时debug方便一些，以后等节点类型转换我补齐了，就放cpp或者单独来个config文件。这个map和routing我的本意是要做到适应每一个主题的。

2024-07-21 15:36 UTC, SherkeyXD commented on resource/tasks.json
> +        "specialParams": [321, 138, 47, 450, 32, 15, 10]
草 这太魔术了

2024-07-22 09:09 UTC, Alan-Charred commented
> 真厉害 如果模版匹配的精度够的话，建议用这个来识别每个点的类型？ ![image](https://private-user-images.githubusercontent.com/34369130/350740440-1e71625b-aa21-484e-88df-973cf49461ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2Mzk2MTMsIm5iZiI6MTcyMTYzOTMxMywicGF0aCI6Ii8zNDM2OTEzMC8zNTA3NDA0NDAtMWU3MTYyNWItYWEyMS00ODRlLTg4ZGYtOTczY2Y0OTQ2MWVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDA5MDgzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzNzIyZDRhNDhkNDg5NjI1NjdkY2Y0Nzk5MzY1NzEwYjRiMDJkMzljOWE3ZDU4NjgzMDY1ZDFhMmM1MWU1ZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EJm5VCQ3KleKdvhrtWd5mApr-SeyyiZp1k7a8Wu0ljc) 这样可以在第一面的时候确定三列的点，而不需要滑动

好主意，我在来想想能不能为第一层优化一下。我现在这么做是希望能通用于所有肉鸽所有地图。

2024-07-24 15:54 UTC, Alan-Charred commented on src/MaaCore/Task/Roguelike/Map/RoguelikeRoutingTaskPlugin.h
> +            };
如果 sort_by_vertical_ 可以把那个 threshold 5 换成参数让我自己代，我就用它（

2024-07-24 20:32 UTC, Alan-Charred commented
> 真厉害 如果模版匹配的精度够的话，建议用这个来识别每个点的类型？ ![image](https://private-user-images.githubusercontent.com/34369130/350740440-1e71625b-aa21-484e-88df-973cf49461ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4NTMyODYsIm5iZiI6MTcyMTg1Mjk4NiwicGF0aCI6Ii8zNDM2OTEzMC8zNTA3NDA0NDAtMWU3MTYyNWItYWEyMS00ODRlLTg4ZGYtOTczY2Y0OTQ2MWVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDIwMjk0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwYTY1ZGE2YjE4OTY5OWI4NTUxZjgzNDM4NDQ4NGZjZDE0MGIyNzA2MGFiOGJmY2NlZjBlNGRiZjk3Y2JhNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9pbpYK16AuVHe3vAv3R1IrH72rZxfiCwej2lvR2v-Ko) 这样可以在第一面的时候确定三列的点，而不需要滑动

啊，我想的是，做一个通用的插件，每一层都可以用，那么就得加上滑动，直到确定最右侧没有节点。
现在重新reformat了一下应该能用了，确定基本功能无误后我会按照您这个思路优化一下，毕竟现在最直接的用途的确是仅跳过第一层。

2024-07-24 20:38 UTC, Constrat commented
@Alan-Charred 
```py
D:\a\MaaAssistantArknights\MaaAssistantArknights\MaaDeps\vcpkg\installed\maa-x64-windows\include\opencv2\core\mat.inl.hpp(103,57): error C2220: the following warning is treated as an error [D:\a\MaaAssistantArknights\MaaAssistantArknights\src\MaaCore\MaaCore.vcxproj]
         D:\a\MaaAssistantArknights\MaaAssistantArknights\src\MaaCore\Task\Roguelike\Map\RoguelikeRoutingTaskPlugin.cpp(192,18): error C2039: 'accumulate': is not a member of 'std' [D:\a\MaaAssistantArknights\MaaAssistantArknights\src\MaaCore\MaaCore.vcxproj]
         D:\a\MaaAssistantArknights\MaaAssistantArknights\src\MaaCore\Task\Roguelike\Map\RoguelikeRoutingTaskPlugin.cpp(192,18): error C3861: 'accumulate': identifier not found [D:\a\MaaAssistantArknights\MaaAssistantArknights\src\MaaCore\MaaCore.vcxproj]
         D:\a\MaaAssistantArknights\MaaAssistantArknights\src\MaaCore\Task\Roguelike\Map\RoguelikeRoutingTaskPlugin.cpp(191,19): error C2737: 'leftmost_y': const object must be initialized [D:\a\MaaAssistantArknights\MaaAssistantArknights\src\MaaCore\MaaCore.vcxproj]
         D:\a\MaaAssistantArknights\MaaAssistantArknights\src\MaaCore\Task\Roguelike\Map\RoguelikeRoutingTaskPlugin.cpp(195,18): error C2039: 'accumulate': is not a member of 'std' [D:\a\MaaAssistantArknights\MaaAssistantArknights\src\MaaCore\MaaCore.vcxproj]
         D:\a\MaaAssistantArknights\MaaAssistantArknights\src\MaaCore\Task\Roguelike\Map\RoguelikeRoutingTaskPlugin.cpp(195,18): error C3861: 'accumulate': identifier not found [D:\a\MaaAssistantArknights\MaaAssistantArknights\src\MaaCore\MaaCore.vcxproj]
         D:\a\MaaAssistantArknights\MaaAssistantArknights\src\MaaCore\Task\Roguelike\Map\RoguelikeRoutingTaskPlugin.cpp(194,19): error C2737: 'rightmost_y': const object must be initialized [D:\a\MaaAssistantArknights\MaaAssistantArknights\src\MaaCore\MaaCore.vcxproj]
         D:\a\MaaAssistantArknights\MaaAssistantArknights\MaaDeps\vcpkg\installed\maa-x64-windows\include\opencv2\videoio.hpp(315,80): error C2220: the following warning is treated as an error [D:\a\MaaAssistantArknights\MaaAssistantArknights\src\MaaCore\MaaCore.vcxproj]
```

2024-07-24 20:59 UTC, Alan-Charred commented on src/MaaCore/Task/Roguelike/Map/RoguelikeRoutingTaskPlugin.cpp
> +    cv::Mat grayImage;
我这个功能太少了，而且没有任何重复利用价值，要不就先不分了？

2024-07-25 00:04 UTC, status102 requested changes

2024-07-25 00:04 UTC, status102 commented on src/MaaCore/Task/Roguelike/Map/RoguelikeRoutingTaskPlugin.cpp
> +        auto right_end = std::ranges::end(rightmostBrightPoints);
no std::ranges

2024-07-25 04:22 UTC, Alan-Charred commented on src/MaaCore/Task/Roguelike/Map/RoguelikeRoutingTaskPlugin.cpp
> +        auto right_end = std::ranges::end(rightmostBrightPoints);
改好了改好了～

2024-07-25 16:02 UTC, zzyyyl commented on src/MaaCore/Task/Roguelike/Map/RoguelikeRoutingTaskPlugin.cpp
> +            brightPoints | ranges::views::filter([&](const cv::Point& p) { return p.x == rightmost_x; });
`ranges::views::` -> `views::`

2024-07-25 16:06 UTC, zzyyyl commented on src/MaaCore/Task/Roguelike/Map/RoguelikeRoutingTaskPlugin.cpp
> +            static_cast<int>(std::distance(right_start, right_end));
整那么复杂，不如 minmax / 2

2024-07-25 16:09 UTC, Alan-Charred commented on src/MaaCore/Task/Roguelike/Map/RoguelikeRoutingTaskPlugin.cpp
> +            static_cast<int>(std::distance(right_start, right_end));
在图中只有目标线条的假设下，是的

2024-07-25 16:32 UTC, zzyyyl commented on resource/tasks.json
> +        "algorithm": "JustReturn"
神金！你为什么不直接用 Stop

2024-07-26 00:35 UTC, status102 requested changes

2024-07-26 00:35 UTC, status102 commented on src/MaaCore/Task/Roguelike/Map/RoguelikeMap.cpp
> +        Log.error("RoguelikeMap | node does not exist");
使用_FUNCTION_代替手动标注

2024-07-26 00:35 UTC, status102 commented on src/MaaCore/Task/Roguelike/Map/RoguelikeRoutingTaskPlugin.cpp
> +    cv::Mat grayImage;
这玩意是admin提的（摊手

2024-07-26 07:08 UTC, zzyyyl commented on src/MaaCore/Vision/Miscellaneous/BrightPointAnalyzer.cpp
> +using namespace asst;
别

2024-07-26 07:11 UTC, Alan-Charred commented on src/MaaCore/Vision/Miscellaneous/BrightPointAnalyzer.cpp
> +using namespace asst;
这怎么了？

2024-07-26 07:17 UTC, zzyyyl commented on src/MaaCore/Vision/Miscellaneous/BrightPointAnalyzer.cpp
> +BrightPointAnalyzer::ResultsVecOpt asst::BrightPointAnalyzer::analyze()
那把这个 asst:: 删了（

2024-07-26 07:19 UTC, Alan-Charred commented on src/MaaCore/Vision/Miscellaneous/BrightPointAnalyzer.cpp
> +BrightPointAnalyzer::ResultsVecOpt asst::BrightPointAnalyzer::analyze()
matcher，multimatcher，ocrer，PipelineAnalyzer里都是这么写的，我这个有什么特殊的吗？

2024-07-26 07:22 UTC, zzyyyl commented on src/MaaCore/Vision/Miscellaneous/BrightPointAnalyzer.cpp
> +BrightPointAnalyzer::ResultsVecOpt asst::BrightPointAnalyzer::analyze()
没人这么写

我是让你 using namespace asst 和 asst:: 二选一

2024-07-26 07:23 UTC, Alan-Charred commented on src/MaaCore/Vision/Miscellaneous/BrightPointAnalyzer.cpp
> +BrightPointAnalyzer::ResultsVecOpt asst::BrightPointAnalyzer::analyze()
okk

2024-07-26 07:39 UTC, zzyyyl commented
dev 的 pre-commit-ci 修好了，我觉得你可以 rebase 一下不然 ci 会一直是红叉叉

2024-07-26 20:51 UTC, Alan-Charred commented
**这个PR我觉得基本达到我的目的了，随时可以用。几个可能的未来研究方向：**
1. 希望可以从游戏中间开始识别之后的节点。（为什么要实现不一定有用的机制？因为山就在那里——）
那么可不可以知道当前节点是哪个呢？一种途径是识别这个“当前所在节点”的框。
<img width="534" alt="image" src="https://github.com/user-attachments/assets/0e87b701-4696-450b-8b82-2b2f871469fb">

好像有点难🤔️就算我精确到像素地抠图，这也。。。好像可以试试？

<img width="389" alt="image" src="https://github.com/user-attachments/assets/02120911-ac74-4f2b-bc69-069385d6e883">


就算无法识别这个框，依然可以辨别出当前节点。过去的节点、当前的节点、下一步的节点、未来的节点，都有略微的差别。（收集全图标就仿佛收集源石虫一样）

<img width="1220" alt="image" src="https://github.com/user-attachments/assets/6b3ac362-c95b-4d23-8234-f3e8c828e279">

2. 为第一层优化一下只用铭牌识别节点。用现在函数改一改加个offset就行。但是仅仅这样有点太不泛用了，最好能和（1）结合一下，做一个不滑动屏幕，动态更新地图信息的功能，作为贪心算法决策那种。

3. 补全各种节点 template（第一层现在够用了，但是之后几层的还得补）。
4. 识别已经点击的节点的类型，换成识别右侧的title，然后把关卡名也顺带识别一下。

<img width="276" alt="image" src="https://github.com/user-attachments/assets/730dfb71-b84f-4c1b-a652-acd78dd37aa8">

最后一排的节点点击后会被屏幕右侧的关卡信息挡住一些，为了泛用性，识别右边的title还是稳一些。

5. 可不可以不退出重进回到地图最初位置啊？可以，完全可以，尤其是可以利用点击节点后屏幕归位的特性消除滑动误差。但是又得计算滑动距离了……屏幕滑动距离和游戏内位移有没有什么计算公式啊QAQ？
6. 加个画图功能，截图并且在图上标记出识别出的节点和连接，可视化验证地图建模结果（看着0->1, 0->2, 1->2 这样的信息眼睛要瞎掉了）。
7. 算了别做梦了，还是早早 merge 掉然后摆烂，去生息演算刷源石虫吧。

2024-08-09 12:54 UTC, merged