feat: 隐藏托盘图标选项
MaaAssistantArknights/MaaAssistantArknights pull request #9819
Opened 2024-07-21 08:02 UTC by Icexbb

#9464

2024-07-21 14:31 UTC, SherkeyXD approved these changes

2024-07-21 14:35 UTC, SherkeyXD commented
在将 MAA 最小化至托盘后，再选择 `隐藏托盘图标`， 会导致 MAA 进入无法操作的状态

2024-07-21 14:38 UTC, SherkeyXD requested changes
在将 MAA 最小化至托盘后，再选择 `隐藏托盘图标`， 会导致 MAA 进入无法操作的状态

考虑在将 MAA 最小化至托盘后禁用 `隐藏托盘图标` 按钮，或是在隐藏托盘图标后弹出 MAA 窗口

2024-07-21 14:44 UTC, SherkeyXD commented on src/MaaWpfGui/Views/UserControl/GUISettingsUserControl.xaml
> +                IsEnabled="{Binding UseTray}"
考虑使用 `Visibility` 来直接更改选项可见性
```suggestion
                Visibility="{Binding UseTray}"
```

2024-07-21 14:45 UTC, SherkeyXD reviewed
前一个先改改吧（

2024-07-21 14:52 UTC, ABA2396 commented
> 在将 MAA 最小化至托盘后，再在托盘图标右键菜单中选择 `隐藏托盘图标`， 会导致 MAA 进入无法操作的状态

~~这样就可以变成流氓软件了~~ 可以用热键打开吧）

2024-07-21 14:53 UTC, SherkeyXD commented
> 可以用热键打开吧）

万一我忘了呢（

2024-07-21 15:48 UTC, SherkeyXD approved these changes

2024-07-21 15:49 UTC, Icexbb commented
好jb绕

2024-07-21 20:50 UTC, Rbqwow commented
这个在某种意义上是不是也算修了托盘图标有丝分裂的问题(

2024-07-22 10:31 UTC, SherkeyXD commented
> 这个在某种意义上是不是也算修了托盘图标有丝分裂的问题(

不算修吧 那个算是WPF的锅了

2024-07-22 10:32 UTC, Rbqwow commented
> > 这个在某种意义上是不是也算修了托盘图标有丝分裂的问题(
> 
> 不算修吧 那个算是WPF的锅了

托盘没了不就没了(((

2024-07-23 04:13 UTC, merged