add: 增加了任务完成关闭游戏的功能
MaaAssistantArknights/MaaAssistantArknights pull request #984
Opened 2022-06-25 16:40 UTC by AkagiYui

#959 
对旧PR的修改，在 夜神模拟器 测试能用

2022-06-25 16:48 UTC, MistEO requested changes

2022-06-25 16:48 UTC, MistEO commented on src/MeoAsstGui/ViewModels/TaskQueueViewModel.cs
> +                ret &= asstProxy.AsstStartCloseDown();
写在 `LinkStart` 里的话没法实时修改了，但是其他的退出动作都是可以实时改的。

放在 `CheckAfterCompleted` 里吧

2022-06-25 17:18 UTC, AkagiYui commented on src/MeoAsstGui/ViewModels/TaskQueueViewModel.cs
> +                ret &= asstProxy.AsstStartCloseDown();
因为`CheckAfterCompleted`是在所有任务结束后被执行的，将此行为放在`CheckAfterCompleted`会导致重新开一个任务队列，而这个任务结束后又会执行`CheckAfterCompleted`。

2022-06-25 18:07 UTC, MistEO commented on src/MeoAsstGui/ViewModels/TaskQueueViewModel.cs
> +                ret &= asstProxy.AsstStartCloseDown();
那就在回调处理这里多加一条 task id 的判断就好啦

https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/f00557834547989e6c9425799abbf0522b2d6e57/src/MeoAsstGui/Helper/AsstProxy.cs#L298

2022-06-26 09:03 UTC, MistEO requested changes

2022-06-26 09:03 UTC, MistEO commented on src/MeoAsstGui/Helper/AsstProxy.cs
> +            return id != 0 && !AsstStart();
为啥要用 `!AsstStart()` ?

2022-06-26 09:03 UTC, MistEO commented on src/MeoAsstGui/Helper/AsstProxy.cs
> +                    if (!_latestTaskId.TryGetValue(TaskType.CloseDown, out _))
直接清就好了，不用条件的

2022-06-26 09:11 UTC, AkagiYui commented on src/MeoAsstGui/Helper/AsstProxy.cs
> +                    if (!_latestTaskId.TryGetValue(TaskType.CloseDown, out _))
这里清掉的话会导致上面的`_latestTaskId.TryGetValue(TaskType.CloseDown, out var closeDownTaskId)`返回值为`false`，进不去`if`

2022-06-26 09:11 UTC, AkagiYui commented on src/MeoAsstGui/Helper/AsstProxy.cs
> +            return id != 0 && !AsstStart();
这里是`AsstStart()`返回的总是`false`，所以我把这个取反了，这里返回`false`是貌似是因为还没`Stop`

2022-06-26 09:28 UTC, MistEO commented on src/MeoAsstGui/Helper/AsstProxy.cs
> +            return id != 0 && !AsstStart();
哦是，还有这种问题，我没考虑到。但是取反是不对的，这个先不管了，回头我看看怎么改一下

2022-06-26 09:29 UTC, MistEO approved these changes

2022-06-26 09:29 UTC, MistEO commented on src/MeoAsstGui/Helper/AsstProxy.cs
> +                    if (!_latestTaskId.TryGetValue(TaskType.CloseDown, out _))
那这个相当于是上面那个的衍生问题，任务仍在运行中

2022-06-26 10:11 UTC, merged

2022-06-26 10:11 UTC, MistEO commented
Thanks for your contribution!