fix: 肉鸽插件内置my_enable，额外判断是否需要跳过
MaaAssistantArknights/MaaAssistantArknights pull request #9892
Opened 2024-07-23 12:25 UTC by status102

link to cdf5847bc991c8608de1a4874b898c586256cc33

2024-07-23 13:14 UTC, zzyyyl requested changes
我的建议是别，你真要加就给投资自己加一个，换个名字比如 deposit_full 之类

2024-07-23 13:45 UTC, zzyyyl requested changes
1. 没必要再拆 _verify，全写里面就行了；
2. 我还是建议你改个名字

2024-07-23 13:49 UTC, status102 commented
反正也不是什么重要东西，先搁着吧

2024-07-29 06:06 UTC, status102 commented
或者更阴间的实现，改task的max_time，直接不进task，也就不会触发plugin不用考虑my_enable还是m_enable了

2024-07-29 07:14 UTC, status102 commented
先迁移了.jpg
占着我的dev（

2024-07-29 07:15 UTC, closed without merging